---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 验证在使用ARL升级同一机箱中的控制器型号时、node1上node2的NAS数据LIFs是否已从node1重新定位到node2。 
---
= 将非根聚合和 NAS 数据 LIF 移回 node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在验证节点 2 上的网络配置后，需要将节点 2 拥有的 NAS 数据 LIF 从节点 1 迁移到节点 2，并确认 SAN LIF 存在于节点 2 上。

.关于此任务
远程 LIF 在升级过程中处理到 SAN LUN 的流量。升级过程中，迁移 SAN LIF 对集群或服务运行状况并非必要。除非需要将 SAN LIF 映射到新端口，否则不会移动它们。

在节点 2 上线后，您需要验证 LIF 是否健康以及是否位于正确的端口上。

.步骤
. 恢复重新定位操作：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下任务：

+
--
** 集群仲裁检查
** 系统 ID 检查
** 映像版本检查
** 目标平台检查
** 网络可访问性检查


--
+
系统在网络可达性检查的此阶段暂停操作。

. 恢复重新定位操作：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下检查：

+
--
** 集群运行状况检查
** 集群 LIF 状态检查


--
+
执行这些检查后、系统会将非根聚合和NAS数据RIFs重新定位回node2、而node2现在正在替代控制器上运行。

+
资源重新定位完成后，控制器更换操作将暂停。

. 检查聚合重新定位和 NAS 数据 LIF 移动操作的状态：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更换操作步骤已暂停，请检查并更正错误（如果有），然后选择问题描述 `reume` 继续操作。

. 如有必要，恢复和还原已移位的 LIF，或者手动迁移和修改未能自动迁移到 node2 的 node2 LIF。
+
[role="tabbed-block"]
====
.恢复和还原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果已替换任何 LIF ，请将主节点还原回 node2 ：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手动迁移和修改 LIF 文件
--
.. 将未能自动迁移到节点2的LIF迁移出去：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. 修改已迁移 LIF 的源节点和源端口：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. 恢复此操作以提示系统执行所需的后检查：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下后检查：

+
** 集群仲裁检查
** 集群运行状况检查
** 聚合重建检查
** 聚合状态检查
** 磁盘状态检查
** 集群 LIF 状态检查
** 卷检查



