---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/verify-node2-installation.html 
keywords: verifying, verify, node, install, installation, NVRAM, controller, module, modules 
summary: 使用ARL升级同一机箱中的控制器型号时、请使用更换模块验证node2的安装。 
---
= 验证 node2 安装
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必须使用替代系统模块验证node2安装。由于物理端口不变、您无需将物理端口从旧节点2映射到替换节点2。

.关于此任务
使用替代系统模块启动node1后、您需要验证其是否已正确安装。您必须等待node2加入仲裁、然后恢复控制器更换操作。

此时，在操作步骤中，操作将暂停，而 node2 加入仲裁。

.步骤
. 验证 node2 是否已加入仲裁：
+
`cluster show -node node2 -fields health`

+
`health` 字段的输出应为 `true` 。

. 此步骤适用于以下升级配置。对于所有其他系统升级，请跳过此步骤并转至<<verify-node2-step3,第 3 步>> ：
+
** 双节点无交换机集群
** 将连接的 AFF A250 或 AFF C250 系统升级到 AFF A50、AFF A30、AFF C30 或 AFF C60 系统。


+
--
如果 node2 没有自动加入仲裁：

.. 检查端口 e1a 和 e1b 的 IP 空间：
+
`network port show`

.. 如果 IP 空间不是“集群”，请在 e1a 和 e1b 上将 IP 空间更改为“集群”：
+
`network port modify -node <node_name> -port <port> -ipspace Cluster`

.. 验证端口 e1a 和 e1b 的 IP 空间是否为“集群”：
+
`network port show`

.. 将节点 2 集群 LIF 迁移到 e1a 和 e1b：
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node2_name> -destination-port <port_name`



--
. [[verify-node2-step3]]验证 node2 和 node1 是否属于同一个集群，以及该集群是否健康：
+
`cluster show`

. 切换到高级权限模式：
+
`set advanced`

. 此步骤仅适用于从 AFF A250 或 AFF C250 升级到 AFF A50、AFF A30、AFF C60 或 AFF C30 的双节点无交换机配置升级。对于所有其他系统升级，请跳过此步骤并转至<<verify-node2-step6,第 6 步>> ：
+
验证 e4a、e2a、e1a、e1b 端口或 e4a、e4b、e1a、e1b 端口是否为“集群”广播域中的集群端口。

+
AFF A50、AFF A30、AFF C30 和 AFF C60 系统共享集群和 HA 端口。您可以安全地将所有集群 LIF 迁移到节点 1 和节点 2 上的 e4a、e4b 或 e4a、e2a：

+
.. 列出所有集群 LIF 的主端口和当前端口：
+
`network interface show -role Cluster -fields home-port,curr-port`

.. [[migrate-cluster-lif-step-4b]]在节点 1 和节点 2 上，将使用 e1a 作为主端口的集群 LIF 迁移到 e4a：
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node> -destination-port e4a`

.. 在节点 1 和节点 2 上，修改迁移到的集群 LIF <<migrate-cluster-lif-step-4b,子步骤 b>>使用 e4a 作为主端口：
+
`network  interface modify -vserver Cluster -lif <cluster_lif> -home-port e4a`

.. 验证群集是否符合仲裁：
+
`cluster show`

.. 重复<<migrate-cluster-lif-step-4b,子步骤 b 和子步骤 c>>将每个节点上的第二个集群 LIF 迁移并修改为 e2a 或 e4b：
+
如果存在 e2a 且其为 100GbE 网络端口，则这是默认的第二个集群端口。如果 e2a 不是 100GbE 网络端口，则 ONTAP 使用 e4b 作为第二个集群和 HA 端口。

.. 从“集群”广播域中删除 e1a 和 e1b：
+
`broadcast-domain remove-ports -broadcast-domain Cluster -ipspace Cluster -ports <node_name>:e1a`

.. 验证只有集群端口 e4a、e2a 或 e4a、e4b 位于“集群”广播域中
+
`broadcast domain show`

.. 移除 e1a 节点 1 和 e1a 节点 2 以及 e1b 节点 1 和 e1b 节点 2 之间的电缆连接，以确保仅使用有效的集群 HA 连接并且没有冗余连接。


. [[verify-node2-step6]]检查控制器更换操作的状态，并验证它处于暂停状态，并且与 node2 暂停执行安装新控制器和移动电缆的物理任务之前的状态相同：
+
`ssystem controller replace show`

+
`s系统控制器更换 show-details`

. 恢复控制器更换操作：
+
`s系统控制器更换恢复`

. 控制器更换操作将暂停以进行干预，并显示以下消息：
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node2         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node1         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: 在此操作步骤 中， _re-creating VLANs ， ifgrp 和 broadcast domains_section 已重命名为 _Restore node2_ 上的网络配置。

. 在控制器更换处于暂停状态的情况下，继续执行 <<还原 node2 上的网络配置>>。




== 还原 node2 上的网络配置

确认 node2 处于仲裁状态并可与 node1 通信后，请确认 node2 上显示了 node1 的 VLAN ，接口组和广播域。此外，验证是否已在其正确的广播域中配置所有 node2 网络端口。

.关于此任务
有关创建和重新创建 VLAN ，接口组和广播域的详细信息，请参见 link:other_references.html["参考资料"] 链接到 _Network Management_ 内容。

.步骤
. 列出已升级的节点 2 上的所有物理端口：
+
`network port show -node node2`

+
此时将显示节点上的所有物理网络端口， VLAN 端口和接口组端口。在此输出中，您可以看到 ONTAP 已将任何物理端口移至 `集群` 广播域。您可以使用此输出来帮助确定应将哪些端口用作接口组成员端口， VLAN 基本端口或用于托管 LIF 的独立物理端口。

. 列出集群上的广播域：
+
`network port broadcast-domain show`

. 列出节点 2 上所有端口的网络端口可访问性：
+
`network port reachability show -node node2`

+
您应看到类似于以下示例的输出。端口和广播名称会有所不同。

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
在上述示例中， node2 已在更换控制器后启动并加入仲裁。它具有多个不可访问的端口，并且正在等待可访问性扫描。

. [[restore_node2_step4]] 使用以下命令按以下顺序修复 node2 上每个端口的可访问性状态不是 `ok` 的可访问性：
+
`network port reachability repair -node _node_name_-port _port_name_`

+
--
.. 物理端口
.. VLAN 端口


--
+
您应看到类似于以下示例的输出：

+
[listing]
----
Cluster ::> reachability repair -node node2 -port e9d
----
+
[listing]
----
Warning: Repairing port "node2:e9d" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
对于可访问性状态可能与当前所在广播域的可访问性状态不同的端口，应显示警告消息，如上例所示。根据需要查看端口和问题解答 `y` 或 `n` 的连接。

+
验证所有物理端口是否具有预期可访问性：

+
`网络端口可访问性显示`

+
在执行可访问性修复时， ONTAP 会尝试将端口放置在正确的广播域中。但是，如果无法确定某个端口的可访问性，并且该端口不属于任何现有广播域，则 ONTAP 将为这些端口创建新的广播域。

. 验证端口可访问性：
+
`网络端口可访问性显示`

+
如果所有端口均已正确配置并添加到正确的广播域中，则 `network port reachability show` 命令应将所有已连接端口的可访问性状态报告为 `ok` ，对于无物理连接的端口，此状态报告为 `no-reachability` 。如果任何端口报告的状态不是这两个端口，请按照中的说明执行可访问性修复并在其广播域中添加或删除端口 <<restore_node2_step4,第 4 步>>。

. 验证所有端口是否均已置于广播域中：
+
`network port show`

. 验证广播域中的所有端口是否配置了正确的最大传输单元（ MTU ）：
+
`network port broadcast-domain show`

. 使用以下步骤还原 LIF 主端口，指定需要还原的 Vserver 和 LIF 主端口（如果有）：
+
.. 列出所有已替换的 LIF ：
+
`displaced interface show`

.. 还原 LIF 主节点和主端口：
+
`displaced interface restore-home-node -node _node_name_-vserver _vserver_name_-lif-name _LIF_name_`



. 验证所有 LIF 是否都具有主端口且已由管理员启动：
+
`network interface show -fields home-port ， status-admin`


