---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,zh-tw,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: AFF 和 FAS 系统升级文档
    url: "/index.html"
  - section: upgrade
  - section: upgrade-arl
homepage:
  tiles:
  - title: 入门
    links:
    - title: "《 ONTAP 发行说明》"
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
  - title: 通过移动存储或卷（大多数系统）进行升级
    links:
    - title: 升级控制器硬件
      url: "/upgrade/upgrade-decide-to-use-this-guide.html"
  - title: 在运行 ONTAP 9.8 及更高版本的系统上移动聚合以进行升级
    links:
    - title: 使用 system controller replace 命令（ AFF A700 至 AFF A900 ）
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/
    - title: 使用 system controller replace 命令（大多数系统）
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/
    - title: 使用手动命令
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/
  - title: 通过在运行 ONTAP 9.7 及更早版本的系统上移动聚合进行升级
    links:
    - title: 使用 system controller replace 命令（大多数系统）
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/
    - title: 使用手动命令
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/
  - title: 升级 MetroCluster 配置中的系统
    links:
    - title: 为您的 MetroCluster 配置选择升级操作步骤
      url: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html
  - title: 更多资源
    links:
    - title: ONTAP 系统文档
      url: https://docs.netapp.com/us-en/ontap-systems/index.html
    - title: ONTAP 交换机文档
      url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
    - title: ONTAP 软件文档
      url: https://docs.netapp.com/us-en/ontap/index.html
    - title: NetApp Hardware Universe
      url: https://hwu.netapp.com/
    - title: NetApp Active IQ Config Advisor
      url: https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor
    - title: NetApp 互操作性表
      url: https://mysupport.netapp.com/matrix/#welcome
    - title: NetApp 社区
      url: https://community.netapp.com/t5/ONTAP-and-FAS/ct-p/fas-ontap-oncommand-and-related-plug-ins
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
