---
permalink: upgrade/migrate-fas2820-node4-lIfs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: '要完成升级，您需要将 FAS2820node3 连接到 node4，然后将 node4 上的数据逻辑接口 (LIF) 和数据聚合迁移到 node3。' 
---
= 将FAS2820节点 4 上的 LIF 和数据聚合迁移到节点 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要完成升级，您需要将FAS2820节点 3 连接到节点 4，然后将节点 4 上的数据逻辑接口 (LIF) 和数据聚合迁移到节点 3。

.关于此任务
在node3上执行以下步骤。

.步骤
. 在node3的加载程序提示符处、将节点启动至启动菜单：
+
[source, cli]
----
boot_ontap menu
----
. 选择选项 `6 Update flash from backup config` 将/var文件系统还原到node3。
+
这将使用上次备份到磁盘的时间来替换基于闪存的所有配置。

. 输入 `y` 以继续。
. 允许节点正常启动。
+
[NOTE]
====
节点会自动重新启动以加载/var文件系统的新副本。

节点报告系统ID不匹配的警告。输入 ... `y` 覆盖系统ID。

====
. 验证集群和 HA 端口是否在节点 3 和节点 4 之间连接。
. 显示节点3和节点4上的集群和HA端口：
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
. 修改集群广播域以包括所需的集群端口：
+
[source, cli]
----
network port broadcast-domain remove-ports -broadcast-domain <broadcast_domain_name> -ports <port_names>
----
+
[source, cli]
----
network port broadcast-domain add-ports -broadcast-domain Cluster -ports <port_names>
----
+

NOTE: 从ONTAP 9.8开始、可以为用于集群连接的现有物理端口指定新的IP空间以及一个或多个广播域。

. 修改集群IP空间以包括所需的集群端口、并将最大传输单元设置为9000 (如果尚未设置)：
+
[source, cli]
----
network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster
----
. 显示所有集群网络LUN：
+
[source, cli]
----
network interface show -role cluster
----
. 将两个节点上的所有集群网络 LIF 迁移到其计划的主端口：
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node_name> -destination-port <port_name>
----
. 显示所有集群网络LUN：
+
[source, cli]
----
network interface show -role cluster
----
. 配置集群网络 LIF 的主端口：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <port_name>
----
. 将用于 node3 的所有数据 LIF 迁移回 node3：
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node3> -destination-port <port_name>
----
. 显示所有数据网络LUN：
+
[source, cli]
----
network interface show -role data
----
. 为所有数据 LIF 配置主节点和主端口。如果任何 LIF 处于关闭状态，则将其管理状态设置为 `up`为每个 LIF 输入一次以下命令：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -status-admin up
----
. 迁移集群管理LIF：
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node3> -destination-port <port_name>
----
. 显示集群管理LIF的状态：
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. 显示集群中所有数据聚合的状态：
+
[source, cli]
----
storage aggregate show
----
. 在双节点集群中启用集群高可用性：
+
[source, cli]
----
cluster ha modify -configured true
----
. 启用并验证 node3 和 node4 的存储故障转移：
+
[source, cli]
----
storage failover modify -node <node3> -enabled true
----
+
[source, cli]
----
storage failover modify -node <node4> -enabled true
----
+
[source, cli]
----
storage failover show
----
. 迁移由 node4 拥有但本应由 node3 拥有的数据聚合：
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node4> -destination <node3>
----
. 显示集群中所有数据聚合的状态：
+
[source, cli]
----
storage aggregate show
----
. 在节点之间启用网络生命周期自动还原：
+
[source, cli]
----
network interface modify -lif * -auto-revert true
----
. 启用存储故障转移自动交还：
+
[source, cli]
----
storage failover modify -node * -auto-giveback true
----
. 显示集群状态：
+
[source, cli]
----
cluster show
----
. 显示故障转移资格：
+
[source, cli]
----
storage failover show
----
+

NOTE: 在集群报告输出中，一个节点可能错误地拥有属于另一个节点的聚合。如果发生这种情况，请从集群的两侧执行接管和交还。

. 显示集群中所有数据聚合的状态：
+
[source, cli]
----
storage aggregate show
----

