---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 此内容介绍如何通过移动存储或卷来升级集群中 AFF 系统或 FAS 系统的控制器硬件。 
---
= 确定是通过移动卷还是存储进行升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本内容介绍如何通过移动存储或卷来升级集群中AFF、FAS或ASA系统的控制器硬件。

如果要在以下情况下升级控制器硬件，请使用此操作步骤 ：

[NOTE]
====
* 不支持通过ASA升级到ASA R2替代系统。有关将数据从ASA迁移到ASA R2系统的信息，请参见link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["启用从SAN主机到ASA R2存储系统的数据访问"^]。
* 升级到9.15.1 9.151或更高版本中推出的系统时、ONTAP会转换现有卷的存储效率、并应用新的存储效率功能来利用硬件卸载功能。这是一个自动后台进程、不会对系统性能造成明显影响。
+
** 对于AFF A20、AFF A30、AFF A50、AFF A70、AFF A90、AFF A1K、AFF C30、AFF C60和AFF C80、ONTAP转换所有现有精简配置卷的存储效率、包括未使用存储效率的卷。
** 对于FAS70和FAS90系统、ONTAP仅转换在升级之前已启用存储效率的现有精简配置卷的存储效率。
+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["详细了解存储效率"^](英文)



* ONTAP 9.8 简化了硬件升级过程，引入了自动端口放置功能。


====
* 原始节点与新节点兼容并受支持。
* 原始节点和新节点运行的是ONTAP 9.0或更高版本。NetApp建议尽可能在原始节点和新节点上运行相同版本的ONTAP。
+
如果您的控制器升级包括混合ONTAP版本、请参见 https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["混合版本ONTAP集群"^] 有关详细信息 ...

* 您正在重新使用新节点上原始节点的 IP 地址，网络掩码和网关。
* 您计划通过移动存储或移动卷来升级控制器硬件。
* 如果您要通过移动存储进行升级，则可以执行中断操作步骤。
+
通过移动卷进行升级不会造成中断。

* 您计划将受支持型号的节点转换为磁盘架，然后将其连接到新节点。


如果要升级MetroCluster配置、请参见 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["升级、刷新或扩展MetroCluster 配置"^]。

.相关信息
* link:upgrade-considerations.html["升级控制器硬件的注意事项"]
* link:../choose_controller_upgrade_procedure.html["选择升级控制器硬件的方法"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["从何处查找 MetroCluster 维护任务的过程"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

