---
permalink: upgrade/upgrade_move_delete_recreate_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lif, re-create, move san lifs, create 
summary: 根据集群内容和集群环境的不同，您需要移动，删除或创建 SAN LIF ，或者重新创建已删除的 SAN LIF 。 
---
= 移动、删除或创建 SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据集群内容和集群环境的不同，您必须移动，删除或创建 SAN LIF ，或者重新创建已删除的 SAN LIF 。



== 移动 SAN LIF 的注意事项

只有在更改集群内容时才需要移动 SAN LIF ，例如，向集群添加节点或从集群中删除节点。移动 LIF 时，您无需重新对 FC 网络结构进行分区，也无需在集群连接的主机与新目标接口之间创建新的 iSCSI 会话。

您可以使用 `network interface modify` 命令移动 SAN LIF 。要移动 SAN LIF ，您必须使 LIF 脱机，将 LIF 移动到其他主节点或端口，然后将其重新联机到新位置。非对称逻辑单元访问（ Asymmetric Logical Unit Access ， ALUA ）可在任何 ONTAP SAN 解决方案中提供冗余路径和自动路径选择。因此，当 LIF 脱机进行移动时，不会发生 I/O 中断。主机只需重试，然后将 I/O 移动到另一个 LIF 即可。

在 LIF 移动期间，您可以无中断地执行以下任务：

* 将集群中的一个 HA 对替换为升级后的 HA 对，其方式对访问 LUN 数据的主机是透明的
* 升级目标接口卡
* 将 Storage Virtual Machine （ SVM ）的资源从集群中的一组节点移至同一集群中的另一组节点
* 当主机服务器联机时，您可以将 SAN LUN 移动到新的 HA 对，而不会中断主机服务器对 LUN 数据的访问


有关详细信息，请参见 https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["SAN LIF 移动"^] SAN 存储管理 _ 文档中的操作步骤。



== 删除不再需要的 SAN LIF

如果集群位于 SAN 环境中，则必须先从原始节点中删除不再需要的任何 SAN LIF，然后才能将原始节点从集群中移除。

.步骤
. 如果您有 iSCSI 启动程序，请完成以下步骤：
+
.. 显示当前连接到原始节点上SVM的活动启动程序的列表、对于每个旧LIF一次：+`iscsi connection show -vserver _vserver_name_-lif _old_lif_`
+
以下示例显示了一个活动启动程序连接到 SVM vs1 的命令输出：

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. 如果任何启动程序仍登录到原始节点，请从主机计算机注销会话。


. 显示端口集列表以确定原始节点上的任何 iSCSI 或 FC LIF 是否属于端口集：
+
`lun portset show`

+
以下示例显示了 `lun portset show` 命令的输出：

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. 如果原始节点上的任何 iSCSi 或 FC LIF 是端口集的成员，请将其从端口集中删除：
+
`lun portset remove -vserver _vserver_name_-portset _portset_name_-port-name _lif_name_`

. 删除原始节点上的 LIF ：
+
`network interface delete -vserver _vserver_name_-lif _lif_name_`





== 创建新的 SAN LIF 或重新创建已删除的 SAN LIF

根据集群环境要求，您可以决定创建新的 SAN LIF 或重新创建先前在此操作步骤中删除的 SAN LIF 。您可以使用创建或重新创建 SAN LIF https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_network_interfaces.html["创建网络接口"^] 使用 OnCommand ® System Manager_ 文档进行集群管理中的操作步骤。

.下一步是什么？
link:upgrade-remove-original-nodes.html["从集群中移除原始节点。"]
