---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: 您必须将属于 node1 和 node2 的磁盘分别重新分配给 node3 和 node4 。 
---
= 连接存储架并重新分配磁盘所有权
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须将属于 node1 和 node2 的磁盘分别重新分配给 node3 和 node4 。

.关于此任务
在 node3 和 node4 上执行本节中的步骤。在继续下一步之前，先在 node3 上完成每个步骤，然后再在 node4 上完成。

[[reassign-spare-disks-step1]]
.步骤
. 连接先前已连接的存储架中的存储架电缆：
+
** 将 node1 电缆连接到 node3
** 将 node2 电缆连接到 node4。
+

CAUTION: 在此升级过程中，请勿将新磁盘架连接到 node3 或 node4。完成控制器升级后，您可以无中断地将新磁盘架连接到系统。



. 验证电源和磁盘架的物理连接。
. 从 node3 LOADER 提示符处，启动到维护模式：
+
`boot_ontap maint`

. 显示 node3 的系统 ID ：
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
记录 node3 的系统 ID，以便在 <<reassign-disks-and-aggregates,第 5 步>> 中使用。



[[reassign-disks-and-aggregates]]
. 重新分配磁盘和数据聚合：
+
[role="tabbed-block"]
====
.重新分配给 node3
--
将 node1 的备用磁盘、属于根聚合的磁盘以及任何数据聚合重新分配给 node3：

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** 参数 `node1_sysid`是您在_关闭原始节点_中记录的值，link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["第 5 步"]。
** 仅当存在共享磁盘时才指定参数 `-p <node2_sysid>`。


--
.重新分配给 node4
--
将 node2 的备用磁盘、属于根聚合的磁盘以及任何数据聚合重新分配给 node4：

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** 参数 `node2_sysid`是您在_关闭原始节点_中记录的值，link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["第 5 步"]。
** 仅当存在共享磁盘时才指定参数 `-p <node3_sysid>`。


--
====
+
系统将显示类似于以下内容的消息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. 输入 `y` 以继续。
+
系统将显示类似于以下内容的消息：

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. 输入 `y` 以继续。
. 确认选项字段中 node1 的根聚合已设置为 `root` ，并且其他聚合已联机：
+
`聚合状态`

+
您应看到类似于以下内容的输出：

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]退出维护模式：
+
`halt`

. 在 node4 上重复 <<reassign-spare-disks-step1,第 1 步>> 到 <<reassign-spare-disks-step9,第 9 步>>。


.下一步是什么？
附加存储盘架并重新分配磁盘所有权后，link:upgrade-restore-root-volume-config.html["还原根卷配置"]。
