---
permalink: upgrade/upgrade-complete-move-volumes.html 
sidebar: sidebar 
keywords: complete, procedure, upgrading, upgrade, move, moving, volume, configure, service, processor, sp, license, autosupport, storage, encryption, fc, nca, port, complete the upgrade 
summary: 要通过移动卷完成操作步骤升级，您需要配置服务处理器 \ （ SP\ ），安装新许可证并设置 AutoSupport 。您可能还需要设置存储或卷加密并配置 FC 或 NCA 端口。 
---
= 完成移动卷升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要通过移动卷完成操作步骤 升级，您必须配置服务处理器（ SP ），安装新许可证并设置 AutoSupport 。您可能还需要设置存储或卷加密并配置 FC 或 NCA 端口。

. 根据需要在新节点上配置 SP ：
+
`ssystem service-processor network modify`

. 根据需要在新节点上安装新许可证：
+
`s系统许可证添加`

. 在新节点上设置 AutoSupport ：
+
`s系统节点 AutoSupport modify`

. 从每个新节点上，向技术支持发送升级后 AutoSupport 消息：
+
`ssystem node AutoSupport invoke -node node_name -type all -message "node_name successfully up级 从 platform_old 升级到 platform_new"`

. 根据您使用的是板载密钥管理还是外部密钥管理，使用以下任一过程恢复存储或卷加密功能：
+
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["还原板载密钥管理加密密钥"^]
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["还原外部密钥管理加密密钥"^]


. 如果新节点具有 FC 端口（板载或 FC 适配器上）、板载 CNA 端口或 CNA 卡，请通过在存储系统提示符下输入以下命令来配置 FC 或 CNA 端口：
+
`ssystem node hardware unified-connect modify -node node-name -adapter adapter-name -mode ｛ fc_CNA ｝ -type ｛ target_initiator ｝`

+
link:https://docs.netapp.com/us-en/ontap/san-admin/index.html["使用 CLI 进行 SAN 管理"^]

+
只有当 CNA 适配器脱机时，才能修改 CNA 配置。

. 如有必要，在新节点上设置无交换机集群。
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140536["迁移到使用 Cisco 集群交换机的双节点交换集群"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140535["迁移到使用 NetApp CN1610 集群交换机的双节点交换集群"^]

. 根据需要，通过 NetApp 支持站点停用原始系统，以通知 NetApp 这些系统不再运行，可以从支持数据库中删除：
+
.. 登录到 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"^] 站点
.. 单击链接 * 我已安装的系统 * 。
.. 在 * 已安装系统 * 页面上，以格式输入旧系统的序列号，然后单击 * 执行！ *
.. 在 " 弃用表单 " 页面上，填写表单并单击 * 提交 * 。



