---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: '在升级运行ONTAP 9.151或更高版本的控制器时、使用命令配置和管理存储加密、管理身份验证密钥并将SnapMirror关系静置 `system controller replace` 。' 
---
= 完成升级准备
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解有关使用板载密钥管理器 (OKM) 进行 ONTAP 许可和管理存储加密的信息。（可选）使 SnapMirror 关系静止。



== 了解 ONTAP 许可

有关ONTAP许可的详细信息，请参见 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["许可证管理"^]。


NOTE: 在控制器上使用未经许可的功能可能会使您无法遵守许可协议。



== 使用板载密钥管理器管理存储加密

使用板载密钥管理器 (OKM) 管理加密密钥。如果您已设置 OKM，则必须在开始升级之前记录密码短语和备份材料。

.步骤
. 记录集群范围的密码短语。
+
这是在使用命令行界面或REST API配置或更新OKM时输入的密码短语。

. 验证密码短语和密钥管理器操作：
+
`sSecurity key-manager 板载同步`

+
出现提示时，输入上一步中记录的群集范围的 OKM 密码短语。

. 通过查看以下命令的输出来验证 cc-mode 是否已启用：
+
`security key-manager config show`

. 备份密钥管理器信息：
+
`s安全密钥管理器板载 show-backup`





== 或者，静止 SnapMirror 关系

在继续使用操作步骤之前，您必须确认所有 SnapMirror 关系均已暂停。暂停 SnapMirror 关系后，它会在重新启动和故障转移后保持静默状态。

.步骤
. 验证目标集群上的 SnapMirror 关系状态：
+
`snapmirror show`

+
[NOTE]
====
如果状态为"Transferring"、则必须中止这些传输：`snapmirror abort -destination-vserver _vserver_name_`

====
+
如果 SnapMirror 关系未处于 " 正在传输 " 状态，则中止将失败。

. 暂停集群之间的所有关系：
+
`snapmirror quiesce -destination-vserver *`



.下一步是什么？
准备升级后，link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["将 node1 拥有的非根聚合和 NAS 数据 LIF 重新定位到 node2"]。
