---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: '使用命令确定是否使用ARL升级运行ONTAP 9.151或更高版本的控制器 `system controller replace` 。' 
---
= 确定是否使用聚合重新定位操作步骤
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
此过程介绍如何在保留现有数据和磁盘的同时、使用新控制器升级HA对中的存储控制器。这是一个复杂的操作步骤，只能由经验丰富的管理员使用。



== 支持 ARL 升级

在以下情况下、您可以升级一对节点：

* 您正在运行 ONTAP 9.15.1 或更高版本。
* 您不希望将新控制器作为新HA对添加到集群中、也不希望使用卷移动过程迁移数据。
* 您拥有管理 ONTAP 的经验，并对在诊断权限模式下工作的风险感到满意。



NOTE: 您可以对此操作步骤 使用NetApp存储加密(NSE)、NetApp卷加密(NVE)和NetApp聚合加密(NAE)。

[[sys_commands_9151_supported_systems]]下表显示了控制器升级支持的型号表。

|===
| 现有控制器 | 更换控制器 | 从ONTAP开始支持... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220、AFF A150 | AFF 2020 ^2^ | 9.16.1 ^1^ 


| FAS8200 ， FAS8300 ， FAS8700 ， FAS9000 | FAS70、FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300、AFF A400、AFF A700 | AFF A70 ^2^，AFF A90 ^2^，AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^、AFF A1K | 9.15.1 
|===
^1^要升级到AFF A20、必须先将AFF A150或AFF A220转换为DS224C磁盘架、方法是将控制器模块更换为IOM12模块。请参阅。 link:../upgrade/upgrade-convert-node-to-shelf.html["将原始节点转换为驱动器架"]

^2^ AFF A20、AFF A50、AFF A70和AFF A90是集成系统、在HA配置中具有两个控制器、在一个机箱中具有板载磁盘：

* 如果要升级到具有内部驱动器的AFF 2020、AFF A70或AFF A90、则必须在升级之前删除这些内部驱动器的所有权。完成升级后、您可以将内部驱动器分配给AFF A20、AFF A70或AFF A90节点、并使用它们创建数据聚合。不必将根聚合或数据聚合迁移到内部驱动器。
* 如果要升级到不带内部驱动器的AFF A20、AFF A70或AFF A90、则在完成升级后无需分配内部驱动器。


如果上表不包含您的控制器升级型号组合，请联系技术支持。



== ARL 不支持升级

在以下情况下、您不能使用ARL执行升级：

* 您正在执行以下升级之一：
+
|===
| 现有控制器 | 更换控制器 


| AFF A250 | AFF A50、AFF A30 


| AFF A800 | AFF A70、AFF A90 


| AFF C250 | AFF C30、AFF C60 


| AFF C800 | AFF C80 
|===
+
要执行上表中列出的升级、请参见link:other_references.html["参考资料"]以链接到_use "system controller Replace "命令升级同一机箱中的控制器型号_。

* 您要升级使用外部阵列作为后端存储的V系列系统或FlexArray虚拟化存储系统。有关V系列或FlexArray系统的升级选项、请联系技术支持。
* 您正在升级MetroCluster FC或IP配置。要升级MetroCluster配置、请参见 link:other_references.html["参考资料"] 以链接到_ MetroCluster升级和扩展文档_。


如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。

请参见 link:other_references.html["参考资料"] 可链接到 _ONTAP 9 文档中心 _ ，在此可以访问 ONTAP 9 产品文档。
