---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: '使用命令确定是否使用ARL升级运行ONTAP 9.151或更高版本的控制器 `system controller replace` 。' 
---
= 决定是否使用此聚合迁移程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升级控制器硬件有多种聚合重定位 (ARL) 方法。此 ARL 过程介绍如何在保留现有数据和磁盘的情况下，将 ONTAP 9.15.1 或更高版本中引入的 AFF 和 FAS 存储系统中的 HA 控制器对升级到新控制器。此过程比较复杂，仅应由经验丰富的 ONTAP 管理员使用。

为了帮助您确定此 ARL 程序是否适合您的控制器硬件升级，您应该检查以下所有支持和不支持升级的情况。



== 此 ARL 程序支持的升级

在以下情况下，您可以使用此 ARL 过程升级一对节点：

* 您运行的是9.15.1 9.151或更高版本。
* 您不希望将新控制器作为新HA对添加到集群中、也不希望使用卷移动过程迁移数据。
* 您在管理ONTAP方面经验丰富、并且可以承受在诊断权限模式下工作的风险。
* 您的硬件升级组合列在<<sys_commands_9151_supported_systems,支持模型矩阵>> 。



NOTE: 您可以对此操作步骤 使用NetApp存储加密(NSE)、NetApp卷加密(NVE)和NetApp聚合加密(NAE)。



== 此 ARL 程序不支持升级

在以下情况下，您不能使用此 ARL 过程来升级一对节点：

* 您正在执行以下升级之一：
+
|===
| 现有控制器 | 更换控制器 


| AFF A250 | AFF A50、AFF A30 


| AFF A800 | AFF A70、AFF A90 


| AFF C250 | AFF C30、AFF C60 


| AFF C800 | AFF C80 
|===
+
要执行上表中列出的升级、请参见link:other_references.html["参考资料"]以链接到_use "system controller Replace "命令升级同一机箱中的控制器型号_。

* 您正在升级MetroCluster FC或IP配置。要升级MetroCluster配置、请参见 link:other_references.html["参考资料"] 以链接到_ MetroCluster升级和扩展文档_。




== 支持的系统升级组合

下表显示了 ONTAP 9.15.1 或更高版本中引入的 AFF 和 FAS 系统使用 ARL 支持的控制器升级组合。如果您的控制器升级组合未列出，请联系技术支持。

|===
| 现有控制器 | 更换控制器 | 从ONTAP开始支持... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220、AFF A150 | AFF 2020 ^2^ | 9.16.1 ^1^ 


| AFF C400 | AFF C60和AFF C80 | 9.16.1 


| FAS8200、FAS8300、FAS9000 | FAS70、FAS90、FAS50 | 9.15.1P3用于FAS70、9.16.1P2用于FAS50 


| FAS8700 | FAS70、FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300、AFF A400、AFF A700 | AFF A70 ^2^，AFF A90 ^2^，AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^、AFF A1K | 9.15.1 
|===
^1^要升级到AFF A20、必须先将AFF A150或AFF A220转换为DS224C磁盘架、方法是将控制器模块更换为IOM12模块。请参阅。 link:../upgrade/upgrade-convert-node-to-shelf.html["将原始节点转换为驱动器架"]

^2^ AFF A20、AFF A50、AFF A70和AFF A90是集成系统、在HA配置中具有两个控制器、在一个机箱中具有板载磁盘：

* 如果要升级到具有内部驱动器的AFF A20、AFF A50、AFF A70或AFF A90、则必须在升级之前删除这些内部驱动器的所有权。完成升级后、您可以将内部驱动器分配给AFF A20、AFF A50、AFF A70或AFF A90节点、并使用它们创建数据聚合。您不必将根聚合或数据聚合迁移到内部驱动器。
* 如果要升级到不带内部驱动器的AFF A20、AFF A50、AFF A70或AFF A90、则在完成升级后无需分配内部驱动器。




== 选择不同的硬件升级程序

* link:../upgrade-arl/index.html["查看可用于升级控制器硬件的替代 ARL 方法"](英文)
* 如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。


.相关信息
参考link:other_references.html["参考资料"]链接到_ONTAP 9 文档_。
