---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: '了解是否可以使用 `system controller replace`命令升级到 ONTAP 9.15.1 或更高版本中引入的控制器。' 
---
= 使用 ARL 升级控制器的准则
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要了解是否可以使用 ARL 升级到 ONTAP 9.15.1 或更高版本中引入的一对控制器，取决于平台以及原始控制器和替换控制器的配置。



[[supported-upgrades-for-arl]]
== 支持 ARL 升级

在使用此ARL过程升级一对节点之前、请查看以下要求以确保您的配置受支持：

* 验证是否可以对原始控制器和更换用的控制器执行ARL。
* 检查原始系统支持的所有已定义聚合的大小和磁盘数量。然后将聚合大小和支持的磁盘数量与新系统支持的聚合大小和磁盘数量进行比较。请参阅 link:other-references.html["参考资料"] 以链接到提供此信息的 _Hardware Universe_。新系统支持的聚合大小和磁盘数量必须大于或等于原始系统支持的聚合大小和磁盘数量。
* 在集群混合规则中验证在替换原始控制器时，新节点是否可以与现有节点一起成为集群的一部分。有关集群混合规则的详细信息，请参见 link:other-references.html["参考资料"] 以链接到 _Hardware Universe_。
* 如果您的系统(例如AFF 700)具有以下配置、请将集群LUN迁移并重新归位到每个节点的两个集群端口：
* 每个节点两个以上的集群端口
* 以分支模式在插槽4中创建集群互连卡、用于创建端口e4a、e4b、e4c和e4D以及端口e4e、 e4f、e4g和e4h
+

NOTE: 如果执行控制器升级时每个节点的集群端口数超过两个、则可能会导致升级后新控制器上的集群丢失。

+
有关详细信息，请参阅知识库文章 link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["如何删除不需要或不必要的集群LUN"^]。



配置了 SnapLock 企业版和 SnapLock 合规性卷的系统支持使用 ARL 升级控制器。



[[two-node-switchless-clusters]]
== 双节点无交换机集群

如果要升级双节点无交换机集群中的节点，则可以在执行升级时将这些节点保留在无交换机集群中。您无需将其转换为交换集群。



[[upgrades-not-supported-for-arl]]
== ARL 不支持升级

您不能升级不支持连接到原始控制器的磁盘架的替代控制器。

请参阅 link:other-references.html["参考资料"] 以链接到 _Hardware Universe_ 获取磁盘支持信息。

如果要升级带有内部驱动器的入门级控制器，请参阅 link:other-references.html["参考资料"] 以链接到 _Upgrade by moving volumes or storage_，然后转到操作步骤 _Upgrading a pair of nodes running clustered Data ONTAP by moving volumes_。



[[troubleshoot]]
== 故障排除

如果在升级控制器过程中出现任何问题，请参阅link:aggregate_relocation_failures.html["故障排除"]了解更多信息和可能的解决方案。

如果您未找到与遇到的问题相关的解决方案 ，请联系技术支持。

.下一步是什么？
在查看使用 ARL 升级控制器的指南后，link:overview_of_the_arl_upgrade.html["了解 ARL 升级顺序"]。
