---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: '您可以使用命令升级运行ONTAP 9.151或更高版本的控制器硬件 `system controller replace` 、从而重新定位非根聚合的所有权。' 
---
= 了解 ARL 升级程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升级控制器硬件有多种聚合重定位 (ARL) 方法。此 ARL 过程介绍如何在保留现有数据和磁盘的情况下，使用新控制器升级 ONTAP 9.15.1 或更高版本中引入的 AFF 和 FAS 存储系统中的 HA 控制器对。


NOTE: 您不能使用此过程升级MetroCluster FC或IP配置。要升级MetroCluster配置、请参见 link:other_references.html["参考资料"] 以链接到_ MetroCluster升级和扩展文档_。

在操作步骤期间，您可以使用替代控制器硬件升级原始控制器硬件，从而重新定位非根聚合的所有权。您可以在节点之间多次迁移聚合，以确认在整个升级操作步骤 中至少有一个节点正在从聚合提供数据。您还可以迁移数据逻辑接口（ LIF ），并在继续操作时将新控制器上的网络端口分配给接口组。

.此信息中使用的术语
在此信息中，原始节点称为 "node1" 和 "node2" ，新节点称为 "node3" 和 "node4" 。在所述的操作步骤期间， node1 将替换为 node3 ， node2 将替换为 node4 。

术语 "node1" ， "node2" ， "node3" 和 "node4" 仅用于区分原始节点和新节点。在操作步骤之后，必须替换原始节点和新节点的实际名称。但是，实际上，节点名称不会更改：在升级控制器硬件后， node3 的名称为 node1 ， node4 的名称为 node2 。

.重要信息：
* 此操作步骤非常复杂，假定您具备高级 ONTAP 管理技能。您还必须阅读并理解link:guidelines_for_upgrading_controllers_with_arl.html["使用 ARL 升级控制器的指南"]和link:overview_of_the_arl_upgrade.html["ARL 升级序列"]在开始升级之前。
* 此操作步骤假定更换用的控制器硬件是新的，尚未使用。此过程不包括使用命令准备使用过的控制器所需的步骤 `wipeconfig` 。如果之前使用了替代控制器硬件、则必须联系技术支持。
* 您可以使用此操作步骤升级具有两个以上节点的集群中的控制器硬件；但是，您需要为集群中的每个高可用性（ HA ）对单独执行操作步骤。
* 升级到9.15.1 9.151或更高版本中推出的系统时、ONTAP会转换现有卷的存储效率、并应用新的存储效率功能来利用硬件卸载功能。这是一个自动后台进程、不会对系统性能造成明显影响。
+
** 对于AFF A20、AFF A30、AFF A50、AFF A70、AFF A90、AFF A1K、AFF C30、AFF C60和AFF C80系统、ONTAP可转换所有现有精简配置卷的存储效率、包括未使用存储效率的卷。
** 对于FAS70和FAS90系统、ONTAP仅转换在升级之前已启用存储效率的现有精简配置卷的存储效率。


+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["详细了解存储效率"^](英文)

* AFF A20、AFF A50、AFF A70、AFF A90、AFF A1K、FAS70和FAS90系统为集群和HA连接共享100GbE网络端口。这些系统可以支持与传统集群交换机建立10GbE或25GbE集群连接；但是、当不再需要10GbE和25GbE交换机时、NetApp建议更新到100GbE集群速度。有关详细信息，请参见以下知识库文章：
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["如何在新的集群设置中配置10G或25G集群端口"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["如何将现有10 G或25 G集群端口转换为40 G或100 G集群端口"^]


--
+
对于集群和HA连接、AFF 2020系统会共享10GbE和25GbE网络端口。这些是AFF A20系统支持的唯一网络端口集群连接。

+
如果无法将现有节点上的e0a或e0b集群端口链接到新节点上的集群端口，请参见 link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp错误在线中的错误ID COBTP-166978"^]。


