---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: '在运行ONTAP 9.151或更高版本的控制器上使用命令执行ARL升级的第6阶段过程顺序 `system controller replace` 。' 
---
= 第6阶段概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在第6阶段、您需要确认新节点设置正确、如果新节点启用了加密、则需要配置和设置存储加密或NetApp卷加密。您还应停用旧节点并恢复SnapMirror操作。

.步骤
. link:manage-authentication-using-kmip-servers.html["使用 KMIP 服务器管理身份验证"]
. link:ensure_new_controllers_are_set_up_correctly.html["确认新控制器设置正确"]
. link:set_up_storage_encryption_new_module.html["在新控制器模块上设置存储加密"]
. link:set_up_netapp_volume_encryption_new_module.html["在新控制器模块上设置NetApp卷或聚合加密"]
. link:decommission_old_system.html["停用旧系统"]
. link:resume_snapmirror_operations.html["恢复 SnapMirror 操作"]


[NOTE]
====
AFF A20、AFF A50、AFF A70、AFF A90、AFF A1K、FAS70和FAS90系统为集群和HA连接共享100GbE网络端口。这些系统可以支持与传统集群交换机建立10GbE或25GbE集群连接；但是、当不再需要10GbE和25GbE交换机时、NetApp建议更新到100GbE集群速度。有关详细信息，请参见以下知识库文章：

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["如何在新的集群设置中配置10G或25G集群端口"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["如何将现有10 G或25 G集群端口转换为40 G或100 G集群端口"^]


对于集群和HA连接、AFF 2020系统会共享10GbE和25GbE网络端口。这些是AFF A20系统支持的唯一网络端口集群连接。

如果无法将现有节点上的e0a或e0b集群端口链接到新节点上的集群端口，请参见 link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp错误在线中的错误ID COBTP-166978"^]。

====