---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: '使用 `ssystem controller replace` 命令确定是否使用 ARL 将运行 ONTAP 9.5 的控制器升级到 9.7 。' 
---
= 决定是否使用此聚合迁移程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升级控制器硬件有多种聚合重定位 (ARL) 方法。此过程介绍如何在运行 ONTAP 9.7、9.6 或 9.5 的系统上使用“系统控制器替换命令”通过 ARL 升级控制器硬件。只有经验丰富的 ONTAP 管理员才应使用此复杂过程。

为了帮助您确定此 ARL 程序是否适合您的控制器硬件升级，您应该检查以下所有情况以了解支持的升级：

* 您正在升级运行 ONTAP 9.5 ， 9.6 或 9.7 的 NetApp 控制器。本文档不适用于升级到 ONTAP 9.8 的情况。
* 您不希望将新控制器作为新的HA对添加到集群中、也不希望通过卷移动来迁移数据。
* 您拥有管理 ONTAP 的经验，并对在诊断权限模式下工作的风险感到满意。
* 您的硬件升级组合列在<<sys_commands_95_97_supported_systems,支持模型矩阵>> 。
* 如果要升级 MetroCluster 配置，则此配置为 4 节点或更高版本的 FC 配置，并且所有节点均运行 ONTAP 9.6 或 9.7 。


[NOTE]
====
* 如果您通过在同一机箱中交换控制器模块（例如AFF A800或AFF C800）来升级系统， NetApp强烈建议使用升级程序link:../upgrade-arl-auto-in-chassis/index.html["使用 ARL 升级控制器模型，保留现有的系统机箱和磁盘"]。此 ARL 过程包括在升级过程中移除和安装控制器时确保内部磁盘在机箱中保持安全的步骤。
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["了解使用 ARL 支持的系统升级组合，保留现有系统机箱和磁盘"]。

* 您可以对此操作步骤 使用NetApp存储加密(NSE)、NetApp卷加密(NVE)和NetApp聚合加密(NAE)。


====


== 支持的系统升级组合

下表显示了使用此 ARL 程序进行控制器升级所支持的型号矩阵。

[cols="50,50"]
|===
| 旧控制器 | 更换控制器 


| FAS8020 ， FAS8040 ， FAS8060 ， FAS8080 | FAS8200 ， FAS8300 ， FAS8700 ， FAS9000 


| AFF8020 ， AFF8040 ， AFF8060 ， AFF8080 | AFF A300 ， AFF A400 ， AFF A700^1^ ， AFF A800^2^ 


| FAS8200 | FAS8700 ， FAS9000 ， FAS8300^4^^ ，^ ^5^ 


| AFF A300 | AFF A700^1^ ， AFF A800^2^^ ，^ ^3^ ， AFF A400^4^^ ，^ ^5^ 
|===

NOTE: 如果上表不包含您的控制器升级型号组合，请联系技术支持。

^1^ONTAP 9.7P2 支持 AFF A700 系统的 ARL 自动升级。

^2^如果您要升级到AFF A800或支持内部和外部磁盘的系统，则必须按照内部 NVMe 磁盘上的根聚合的特定说明进行操作。请参阅link:reassign-node1-disks-to-node3.html#auto_check3_step9["将node1磁盘重新分配给node3、步骤9"]和link:reassign-node2-disks-to-node4.html#auto_check_4_step9["将node2磁盘重新分配给node4、步骤9"]。

^3^ONTAP 9.7P5 支持 ARL 自动从 AFF A300 升级到 AFF A800 系统。

^4^ONTAP 9.7P8 支持从 AFF A300 自动升级到 AFF A400 ， FAS8200 自动升级到 FAS8300 系统。

^5^如果要在双节点无交换机集群配置中从 AFF A300 升级到 AFF A400 或 FAS8200 到 FAS8300 系统，则必须选择临时集群端口进行控制器升级。AFF A400 和 FAS8300 系统采用两种配置：一种是以太网捆绑包，夹层卡端口为以太网类型；另一种是 FC 捆绑包，夹层端口为 FC 类型。

* 对于采用以太网类型配置的 AFF A400 或 FAS8300 ，您可以使用两个夹层端口中的任何一个作为临时集群端口。
* 对于采用 FC 类型配置的 AFF A400 或 FAS8300 ，您必须添加一个四端口 10GbE 网络接口卡（部件号 X1147A ）以提供临时集群端口。
* 使用临时集群端口完成控制器升级后，您可以无中断地将集群 LIF 迁移到 AFF A400 系统上的 E3a 和 e3b 100GbE 端口以及 FAS8300 系统上的 e0c 和 e0d 100GbE 端口。




== 选择不同的硬件升级程序

* link:../upgrade-arl/index.html["查看可用于升级控制器硬件的替代 ARL 方法"](英文)
* 如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。


.相关信息
参考link:other_references.html["参考资料"]链接到_ONTAP 9 文档_。
