---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: '了解是否可以使用 `ssystem controller replace` 命令将运行 ONTAP 9.5 的控制器升级到 9.7 。' 
---
= 使用 ARL 升级控制器的准则
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要了解是否可以使用聚合重新定位（ Aggregate Relocation ， ARL ）将一对运行 ONTAP 9.5 的控制器升级到 ONTAP 9.7 ，取决于原始控制器和更换控制器的平台和配置。



== 支持 ARL 升级

在使用适用于 ONTAP 9.5 的 ARL 操作步骤将一对节点升级到 ONTAP 9.7 时，您必须验证是否可以对原始控制器和替代控制器执行 ARL 。

您应检查所有已定义聚合的大小以及原始系统支持的磁盘数。然后，您必须将支持的聚合大小和磁盘数量与新系统支持的聚合大小和磁盘数量进行比较。请参见 link:other_references.html["参考资料"] 链接到可 Hardware Universe 提供此信息的 _SIL_ 。新系统支持的聚合大小和磁盘数必须等于或大于原始系统支持的聚合大小和磁盘数。

您应在集群混用规则中验证在更换原始控制器后，新节点是否可以成为现有节点集群的一部分。有关集群混合规则的详细信息，请参见 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe 。


NOTE: 在执行 AFF 系统升级之前，您必须将 ONTAP 升级到版本 9.5P1 或更高版本。要成功升级，需要这些版本级别。


NOTE: 如果要升级的系统支持内部驱动器（例如 FAS2700 或 AFF A250 ），但没有内部驱动器，请参见 link:other_references.html["参考资料"] 并使用 _aggregate relocation 中的操作步骤手动升级适用于您的 ONTAP 版本的控制器 Hardware_ 内容。

如果您使用的是 ONTAP 9.6P11 ， 9.7P8 或更高版本，建议启用连接，实时性和可用性监控（ ，简称 " 状态监控 " ）接管，以便在发生某些节点故障时将集群恢复为仲裁状态。`kernel-service` 命令需要高级权限级别访问。有关详细信息，请参见 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["NetApp 知识库文章 SU436 ： CLAMK takeover default configuration changed"^]。

配置了 SnapLock 企业版和 SnapLock 合规性卷的系统支持使用 ARL 升级控制器。



== 双节点无交换机集群

如果要升级双节点无交换机集群中的节点，则可以在执行升级时将这些节点保留在无交换机集群中。您无需将其转换为交换集群。



== ARL 不支持升级

您不能执行以下升级：

* 更换不支持与原始控制器相连的磁盘架的控制器
+
请参见 link:other_references.html["参考资料"] 链接到 _disk_ Hardware Universe 以获取磁盘支持信息。

* 具有内部驱动器的入门级控制器，例如： FAS 2500 。
+
如果要使用内部驱动器升级入门级控制器，请参见 link:other_references.html["参考资料"] 要链接到 _Upgrade by moving volumes or storage_ 并转到操作步骤 _upgrading a pair of nodes running candlused_by Data ONTAP moving volumes_ 。





== MetroCluster FC 配置

在MetroCluster FC配置中、您必须尽快更换灾难恢复/故障转移站点节点。MetroCluster 配置中的控制器型号不匹配不受支持，因为控制器型号不匹配可能会导致灾难恢复镜像脱机。使用 `-skip-metrocluster-check true`命令可在您替换第二个站点上的节点时绕过 MetroCluster 检查。



== 故障排除

升级节点对时可能会遇到故障。节点可能会崩溃，聚合可能无法重新定位或 LIF 可能无法迁移。故障的发生原因及其解决方案取决于升级操作步骤期间发生故障的时间。

请参阅 ARL 升级概述部分中描述该过程不同阶段的表格。有关可能发生的故障的信息按操作步骤的阶段列出。

如果在升级控制器过程中出现任何问题，请参阅以下内容：link:aggregate_relocation_failures.html["故障排除"]部分。流程各阶段列出的故障信息如下：link:overview_of_the_arl_upgrade.html["ARL 升级序列"] 。

如果您未找到与遇到的问题相关的解决方案 ，请联系技术支持。
