---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: '使用 `ssystem controller replace` 命令将运行 ONTAP 9.5 的控制器升级到 9.7 时，安装和启动 node4 并安装 ONTAP 软件。' 
---
= 安装并启动节点 4.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必须在机架中安装node4、将node2连接传输到node4、启动node4并安装ONTAP。然后、您必须重新分配node2上的任何备用磁盘、属于根卷的任何磁盘以及在此过程前面未重新定位到node3的任何非根聚合、如本节所述。

.关于此任务
重新定位操作在此阶段开始时暂停。此过程大部分是自动完成的；此操作将暂停以使您能够检查其状态。您必须手动恢复此操作。此外、您还必须验证NAS数据LIF是否已成功移至node4。

如果 node4 的 ONTAP 9 版本与 node2 上安装的版本不同，则需要对其进行网络启动。安装 node4 后，从 Web 服务器上存储的 ONTAP 9 映像启动它。然后，您可以按照中的说明将正确的文件下载到启动介质设备，以供后续系统启动 link:prepare_for_netboot.html["准备网络启动"]。

[IMPORTANT]
====
* 对于AFF A800或AFF C800控制器升级，在移除节点 2 之前，必须确保机箱中的所有驱动器都牢固地固定在中板上。有关详细信息，请参阅 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更换AFF A800或AFF C800控制器模块"]。
* 如果您要升级带有存储磁盘的系统，则必须完成整个部分，然后继续link:set_fc_or_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"] ，在集群提示符下输入命令。


====
.步骤
. 【 auto_install4_step1]] 确保 node4 具有足够的机架空间。
+
如果 node4 与 node2 位于不同的机箱中，则可以将 node4 与 node3 放在同一位置。如果 node2 和 node4 位于同一机箱中，则 node4 已位于其相应的机架位置。

. 按照节点型号的 _Installation and Setup Instructions_中 的说明，在机架中安装 node4 。
. 为节点 4 布线，将连接从节点 2 移至节点 4 。
+
使用 node4 平台的《安装和设置说明》、相应的磁盘架文档和《HA 对管理》文档连接以下连接。

+
参考link:other_references.html["参考资料"]链接到_HA 对管理_。

+
** 控制台（远程管理端口）
** 集群端口
** 数据端口
** 集群和节点管理端口
** 存储
** SAN 配置： iSCSI 以太网和 FC 交换机端口
+

NOTE: 您可能不需要将互连卡 /FC-VI 卡或互连 /FC-VI 缆线连接从 node2 移至 node4 ，因为大多数平台型号都具有唯一的互连卡型号。对于 MetroCluster 配置，必须将 FC-VI 缆线连接从 node2 移至 node4 。如果新主机没有 FC-VI 卡，则可能需要移动 FC-VI 卡。



. 打开 node4 的电源，然后在控制台终端按 Ctrl-C 以访问启动环境提示符，从而中断启动过程。
+

NOTE: 启动 node4 时，您可能会看到以下警告消息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 如果您在步骤 4 中看到警告消息，请执行以下操作：
+
.. 检查是否存在任何可能指示 NVRAM 电池电量低以外问题的控制台消息，如有必要，请采取任何必要的更正措施。
.. 让电池充电并完成启动过程。
+

WARNING: *请勿超越延迟；如果电池无法充电，可能会导致数据丢失。*

+

NOTE: 请参见 link:prepare_for_netboot.html["准备网络启动"]。





. 【第 6 步】选择以下操作之一，配置网络启动连接。
+

NOTE: 您必须使用管理端口和 IP 作为网络启动连接。请勿使用数据 LIF IP ，否则在执行升级期间可能会发生数据中断。

+
[cols="30,70"]
|===
| 动态主机配置协议（ DHCP ） | 那么 ... 


| 正在运行 | 在启动环境提示符处输入以下命令，以自动配置连接： `ifconfig e0M -auto` 


| 未运行 | 在启动环境提示符处输入以下命令、以手动配置连接：
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 是存储系统的IP地址(必填)。
`_netmask_` 是存储系统的网络掩码(必需)。
`_gateway_` 是存储系统的网关(必需)。
`_dns_addr_` 是网络上名称服务器的IP地址(可选)。
`_dns_domain_` 是域名服务(Domain Name Service、DNS)域名。如果使用此可选参数，则无需在网络启动服务器 URL 中使用完全限定域名；您只需要服务器的主机名。注意：您的接口可能需要其他参数。输入 ... `help ifconfig` 有关详细信息、请参见固件提示符。 
|===
. 对 node4 执行网络启动：
+
[cols="30,70"]
|===
| 针对 ... | 那么 ... 


| FAS/AFF8000 系列系统 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| 所有其他系统 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
` <path_to_the_web-accessible_directory>` 应指向您在本节第 1 步中下载 ` <ontap_version>_image.tgz` 的位置 link:prepare_for_netboot.html["准备网络启动"]。

+

NOTE: 请勿中断启动。

. 从启动菜单中，选择选项 ` （ 7 ） Install new software first` 。
+
此菜单选项可下载新的 ONTAP 映像并将其安装到启动设备中。

+
请忽略以下消息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
注意适用场景可无中断升级 ONTAP ，而不是升级控制器。

+

NOTE: 请始终使用 netboot 将新节点更新为所需映像。如果您使用其他方法在新控制器上安装映像，则可能会安装不正确的映像。此问题描述适用场景所有 ONTAP 版本。netboot操作步骤 与选项结合使用 `(7) Install new software` 擦除启动介质并将相同的ONTAP 版本放置在两个映像分区上。

. 如果系统提示您继续运行操作步骤，请输入 `y` ，并在系统提示您输入软件包时，输入 URL ：
+
` http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. 完成以下子步骤以重新启动控制器模块：
+
.. 出现以下提示时，输入 `n` 以跳过备份恢复：
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. 出现以下提示时，输入 `y` 以重新启动：
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
控制器模块重新启动，但停留在启动菜单处，因为启动设备已重新格式化，并且必须还原配置数据。



. 从启动菜单中选择维护模式 `5` ，并在系统提示您继续启动时输入 `y` 。
. 验证控制器和机箱是否已配置为 HA ：
+
`ha-config show`

+
以下示例显示了 `ha-config show` 命令的输出：

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: 系统会在 PROM 中记录它们是采用 HA 对还是独立配置。独立系统或 HA 对中的所有组件的状态都必须相同。

. 如果控制器和机箱未配置为 HA ，请使用以下命令更正配置：
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
如果您使用的是 MetroCluster 配置，请使用以下命令修改控制器和机箱：

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. 退出维护模式：
+
`halt`

+
在启动环境提示符处按Ctrl-C中断自动启动。

. 在 node3 上，检查系统日期，时间和时区：
+
`dATE`

. 在 node4 上，在启动环境提示符处使用以下命令检查日期：
+
`s如何选择日期`

. 如有必要，请在 node4 上设置日期：
+
`set date _MM/dd/yyy_`

. 在 node4 上，在启动环境提示符处使用以下命令检查时间：
+
`s时间`

. 如有必要，请在 node4 上设置时间：
+
`set time _hh：mm：ss_`

. 在启动加载程序中、设置node4上的配对系统ID：
+
`setenv partner-sysid _node3_sysid_`

+
对于node4、 `partner-sysid` 必须为node3的。

+
保存设置：

+
`saveenv`

. [[auto_install4_step21]]验证 `partner-sysid` 对于node4：
+
`printenv partner-sysid`



. [[auto_install4_step22]]如果您安装了NetApp存储加密 (NSE) 驱动器，请执行以下步骤：
+

NOTE: 如果您之前尚未在操作步骤 中执行此操作、请参见知识库文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判断驱动器是否已通过FIPS认证"^] 确定正在使用的自加密驱动器的类型。

+
.. 设置 `bootarg.storageencryption.support` to `true` 或 `false`：
+
[cols="35,65"]
|===
| 如果正在使用以下驱动器、请使用… | 然后选择… 


| 符合FIPS 140-2 2级自加密要求的NSE驱动器 | `setenv bootarg.storageencryption.support *true*` 


| NetApp非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
不能在同一节点或HA对上混用FIPS驱动器和其他类型的驱动器。您可以在同一节点或HA对上混用SED和非加密驱动器。

====
.. 请联系NetApp支持部门以帮助还原板载密钥管理信息。


. 将节点启动至启动菜单：
+
`boot_ontap 菜单`



.下一步是什么？
* 如果您的系统具有 FC 或 UTA/UTA2 配置，link:set_fc_or_uta_uta2_config_node4.html["在节点 4 上设置 FC 或 UTA/UTA2 配置"] 。
* 如果您没有 FC 或 UTA/UTA2 配置，link:reassign-node2-disks-to-node4.html#reassign-node2-node4-step1["将 node2 磁盘重新分配给 node4，步骤 1"]这样node4就可以识别node2的磁盘。
* 如果您有MetroCluster配置，link:set_fc_or_uta_uta2_config_node4.html["在节点 4 上设置 FC 或 UTA/UTA2 配置"]检测连接到节点的磁盘。

