---
sidebar: sidebar 
permalink: upgrade-arl-auto/reassign-node2-disks-to-node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: '在使用 `ssystem controller replace` 命令升级运行 ONTAP 9.5 的控制器时，配置 node4 板载 FC 端口， UTA/UTA2 端口或 UTA/UTA2 卡。' 
---
= 将node2磁盘重新分配给node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您需要先将属于node2的磁盘重新分配给node4、然后再验证node4安装。

.步骤
. [[reassign-node2-node4-step1]]验证node2已在启动菜单停止，并将node2的磁盘重新分配给node4：
+
`boot_after_controller_replacement`

+
经过短暂延迟后、系统将提示您输入要替换的节点的名称。如果存在共享磁盘(也称为高级磁盘分区(Advanced Disk Partitioning、ADP)或分区磁盘)、系统将提示您输入HA配对节点的节点名称。

+
这些提示可能会被埋在控制台消息中。如果未输入节点名称或输入的名称不正确、系统将提示您重新输入此名称。

+
.展开控制台输出示例
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu ...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement) Boot after controller upgrade
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login: ...
----
====
. 如果系统进入重启循环并显示以下消息 `no disks found`，这是因为它已将端口重置回目标模式，因此无法看到任何磁盘。履行<<auto_check_4_step3,第 3 步>>通过<<auto_check_4_step8,第 8 步>>在 node4 上解决此问题。
. [[auto_check_4_步骤3]]在自动启动期间按Ctrl-C在Loader提示符处停止节点。
. 在加载程序提示符处、进入维护模式：
+
`boot_ontap maint`

. 在维护模式下，显示先前设置的所有启动程序端口，这些端口现在处于目标模式：
+
`ucadmin show`

+
将端口改回启动程序模式：

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. 验证端口是否已更改为启动程序模式：
+
`ucadmin show`

. 退出维护模式：
+
`halt`

+
[NOTE]
====
如果要从支持外部磁盘的系统升级到也支持外部磁盘的系统，请转至。<<auto_check_4_step8,第 8 步>>

如果要从使用外部磁盘的系统升级到同时支持内部和外部磁盘的系统，例如AFF A800系统，请转至<<auto_check_4_step9,第 9 步>>。

====
. [[auto_check_4_步骤8]]在Loader提示符处、启动：
+
`boot_ontap 菜单`

+
现在，在启动时，节点可以检测到先前分配给它的所有磁盘，并可按预期启动。

+
如果要更换的集群节点使用根卷加密、则ONTAP无法从磁盘中读取卷信息。还原根卷的密钥：

+
.. 返回到特殊的启动菜单：
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. 选择*(10)设置板载密钥管理器恢复密钥*
.. 输入 ... `y` 在以下提示符处：
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. 在提示符处、输入密钥管理器密码短语。
.. 出现提示时、输入备份数据。
+

NOTE: 您必须已在中获取密码短语和备份数据 link:prepare_nodes_for_upgrade.html["准备要升级的节点"] section of this procedure.

.. 系统重新启动到特殊启动菜单后、运行选项*(1) Normal Boot*
+

NOTE: 您可能会在此阶段遇到错误。如果发生错误、请重复中的子步骤 <<auto_check_4_step22,第 22 步>> 直到系统正常启动。



. [[auto_check_4_step9]]如果要从具有外部磁盘的系统升级到支持内部和外部磁盘的系统（例如AFF A800系统），请将节点 2 聚合设置为根聚合，以确认节点 4 从节点 2 的根聚合启动。要设置根聚合，请转到 node4 上的启动菜单并选择选项 `5`进入维护模式。
+

WARNING: * 您必须按所示的确切顺序执行以下子步骤；否则可能发生原因会导致中断甚至数据丢失。 *

+
以下操作步骤会将 node4 设置为从 node2 的根聚合启动：

+
.. 进入维护模式。
+
`boot_ontap maint`

.. 检查 node2 聚合的 RAID ，丛和校验和信息：
+
`aggr status -r`

.. 检查 node2 聚合的状态：
+
`聚合状态`

.. 如有必要，将 node2 聚合置于联机状态：
+
`aggr_online root_aggr_from__node2_`

.. 阻止 node4 从其原始根聚合启动：
+
`aggr offline _root_aggr_on_node4_`

.. 将 node2 根聚合设置为 node4 的新根聚合：
+
`aggr options aggr_from__node2_ root`




