---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node3.html 
keywords: node3, interface group, VLANs, broadcast domains, re-create 
summary: '使用 `ssystem controller replace` 命令将运行 ONTAP 9.5 的控制器升级到 9.7 时，在 node3 上重新创建 node1 的 VLAN ，接口组和广播域。' 
---
= 在 node3 上重新创建 VLAN ，接口组和广播域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
确认 node3 处于仲裁状态并可与 node2 通信后，您必须在 node3 上重新创建 node1 的 VLAN ，接口组和广播域。您还必须将 node3 端口添加到新重新创建的广播域中。

有关创建和重新创建 VLAN ，接口组和广播域的详细信息，请访问 link:other_references.html["参考资料"] 并链接到 _Network Management_ 。

.步骤
. 使用中记录的 node1 信息在 node3 上重新创建 VLAN link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2"] 部分。
+
`network port vlan create -node <node_name> -vlan <vlan-name>`

. 使用中记录的 node1 信息在 node3 上重新创建接口组 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2"] 部分。
+
`network port ifgrp create -node <node_name> -ifgrp <port_ifgrp_name>-cluster-func`

. 使用中记录的 node1 信息在 node3 上重新创建广播域 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2"] 部分。
+
`network port broadcast-domain create -ipspace default -broadcast-domain <broadcast_domain_name> -mtu <mt_size> -ports <node_name ： port_name ， node_name ： port_name>`

. 将 node3 端口添加到新重新创建的广播域：
+
`network port broadcast-domain add-ports -broadcast-domain <broadcast_domain_name> -ports <node_name ： port_name ， node_name ： port_name>`


