---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node4.html 
keywords: node4, interface group, VLANs, broadcast domains, re-create 
summary: '使用 `ssystem controller replace` 命令将运行 ONTAP 9.5 的控制器升级到 9.7 时，在 node4 上重新创建 node2 的 VLAN ，接口组和广播域。' 
---
= 在 node4 上重新创建 VLAN ，接口组和广播域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
确认 node4 处于仲裁状态并可与 node3 通信后，您必须在 node4 上重新创建 node2 的 VLAN ，接口组和广播域。您还必须将 node3 端口添加到新重新创建的广播域中。

.关于此任务
有关创建和重新创建 VLAN ，接口组和广播域的详细信息，请访问 link:other_references.html["参考资料"] 并链接到 _Network Management_ 。

.步骤
. 使用中记录的 node2 信息在 node4 上重新创建 VLAN link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3"] 部分。
+
`网络端口vlan create -node _node4_-vlan _vlan-names_`

. 使用中记录的 node2 信息在 node4 上重新创建接口组 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3"] 部分。
+
`network port ifgrp create -node _node4_-ifgrp _port_ifgrp_names_-cluster-func`

. 使用中记录的 node2 信息在 node4 上重新创建广播域 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3"] 部分。
+
`network port broadcast-domain create -ipspace default -broadcast-domain _broadcast_domain_name_-mtu _mtu _size_-ports _node_name：port_name、node_name：port_name_`

. 将 node4 端口添加到新重新创建的广播域：
+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_name_-ports _node_name：port_name、node_name：port_name_`


