---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_nas_data_lifs_node1_node2.html 
keywords: relocate, non-root, nonroot, aggregates, NAS, data, lifs, node1, node2 
summary: 使用 system controller replace 命令将运行 ONTAP 9.5 的控制器升级到 9.7 时，将非根聚合和 NAS 数据 LIF 从 node1 移动到 node2 ，并将 node1 的资源移动到 node3 。 
---
= 将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在将 node1 替换为 node3 之前，必须先将非根聚合和 NAS 数据 LIF 从 node1 移动到 node2 ，然后再最终将 node1 的资源移动到 node3 。

.开始之前
在开始任务时，此操作必须已暂停；您必须手动恢复此操作。

.关于此任务
在升级操作步骤期间，远程 LIF 处理 SAN LUN 的流量。升级期间，集群或服务运行状况无需移动 SAN LIF 。使 node3 联机后，您必须验证 LIF 是否运行正常并位于相应的端口上。


NOTE: 不会修改聚合和 LIF 的主所有者；只会修改当前所有者。

.步骤
. 恢复聚合重新定位和 NAS 数据 LIF 移动操作：
+
`s系统控制器更换恢复`

+
所有非根聚合和 NAS 数据 LIF 都会从 node1 迁移到 node2 。

+
此操作将暂停，以便验证是否已将所有 node1 非根聚合和非 SAN 数据 LIF 迁移到 node2 。

. 检查聚合重新定位和 NAS 数据 LIF 移动操作的状态：
+
`s系统控制器更换 show-details`

. 在操作仍处于暂停状态的情况下，验证所有非根聚合在 node2 上的状态是否均处于联机状态：
+
`storage aggregate show -node <node2> -state online -root false`

+
以下示例显示 node2 上的非根聚合处于联机状态：

+
[listing]
----
cluster::> storage aggregate show -node node2 -state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
如果 node2 上的聚合脱机或变为外部聚合，请在 node2 上使用以下命令将其联机，每个聚合一次：

+
`storage aggregate online -aggregate <aggregate_name>`

. 在 node2 上使用以下命令并检查其输出，以验证 node2 上的所有卷是否联机：
+
`volume show -node <node2> -state offline`

+
如果 node2 上的任何卷脱机，请在 node2 上使用以下命令将其联机，每个卷一次：

+
`volume online -vserver <vserver_name> -volume <volume_name>`

+
这 `vserver_name`使用此命令的方法可以在上一个命令的输出中找到 `volume show`命令。



. 【第 5 步】如果新硬件上不存在当前托管数据 LIF 的端口，请将其从广播域中删除：
+
`network port broadcast-domain remove-ports`

. 如果任何 LIF 已关闭，请通过为每个 LIF 输入以下命令将 LIF 的管理状态设置为 "up" ：
+
`network interface modify -vserver _vserver_name -lif _LIF_name_` ` -home-node _nodename_ -status-admin up`

. 如果配置了接口组或 VLAN ，请完成以下子步骤：
+
.. 如果尚未保存这些 VLAN 和 ifgrp 信息，请记录 VLAN 和 ifgrp 信息，以便在启动 node3 后在 node3 上重新创建 VLAN 和 ifgrp 。
.. 输入以下命令，从接口组中删除 VLAN ：
+
`network port vlan delete -node _nodename_ -port _ifgrp_ -vlan-id _vlan_ID_`

+

NOTE: 按照更正操作解决 vlan delete 命令建议的任何错误。

.. 输入以下命令并检查其输出，以查看节点上是否配置了任何接口组：
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
系统将显示节点的接口组信息，如以下示例所示：

+
[listing]
----
cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                 Node: node1
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. 如果节点上配置了任何接口组，请记录这些组的名称以及分配给它们的端口，然后输入以下命令删除这些端口，每个端口输入一次：
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




