---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports 
summary: '在使用 `ssystem controller replace` 命令升级运行 ONTAP 9.5 的控制器时，配置 node3 板载 FC 端口， UTA/UTA2 端口或 UTA/UTA2 卡。' 
---
= 在 node3 上设置 FC 或 UTA/UTA2 配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果 node3 具有板载 FC 端口，板载统一目标适配器（ UTA/UTA2 ）端口或 UTA/UTA2 卡，则必须先配置这些设置，然后才能完成其余操作步骤。

.关于此任务
您可能需要完成此部分 <<在 node3 上配置 FC 端口>>，部分 <<检查并配置 node3 上的 UTA/UTA2 端口>>或这两个部分。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代融合网络适配器（ CNA ）适配器和端口。但是，命令行界面使用术语 CNA 。

如果node3没有板载FC端口、板载UTA/UTA2端口或UTA/UTA2卡，并且您要升级具有存储磁盘的系统，则可以跳至link:reassign-node1-disks-to-node3.html["将node1磁盘重新分配给node3"]。



== 在 node3 上配置 FC 端口

如果节点 3 具有 FC 端口（无论是板载的还是附加 FC 适配器上的），则必须在节点投入使用之前设置其端口配置，因为系统出厂时未预先配置端口。如果您不配置端口，则可能会遇到服务中断。

.开始之前
您必须具有在部分中保存的 node1 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则可以在中对其进行配置 <<检查并配置 node3 上的 UTA/UTA2 端口>>。


IMPORTANT: 在维护模式 shell 提示符下输入本节中的命令。

.步骤
. 将节点 3 上的 FC 设置与您之前从节点 1 捕获的设置进行比较。
. 根据需要执行以下操作之一来修改节点 3 上的 FC 端口：
+
在维护模式下（启动菜单中的选项 5）：

+
** 要作为目标端口进行编程：
+
`ucadmin modify -m fc -t target <adapter>`

+
例如： `ucadmin modify -m fc -t target 2a`

** 要对启动程序端口进行编程：
+
`ucadmin modify -m fc -t initiator <adapter>`

+
例如： `ucadmin modify -m fc -t initator 2b`



. 使用以下命令并检查输出来验证新设置：
+
`ucadmin show`

. 暂停节点：
+
`halt`

. 从加载程序提示符启动系统：
+
`boot_ontap 菜单`

. 输入命令后，请等待，直到系统停留在启动环境提示符处。
. 从维护模式的启动菜单中选择选项 `5` 。


. 执行以下操作之一：
+
** 如果 node3 具有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请转至 <<检查并配置 node3 上的 UTA/UTA2 端口>>。
** 如果node3没有UTA/UTA2卡或UTA/UTA2板载端口，请跳过<<检查并配置 node3 上的 UTA/UTA2 端口>>并转到link:reassign-node1-disks-to-node3.html["将node1磁盘重新分配给node3"]。






== 检查并配置 node3 上的 UTA/UTA2 端口

如果 node3 具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则必须检查这些端口的配置，并可能对其进行重新配置，具体取决于您希望如何使用升级后的系统。

.开始之前
您必须为 UTA/UTA2 端口配备正确的 SFP+ 模块。

.关于此任务
如果要对 FC 使用统一目标适配器（ UTA/UTA2 ）端口，则必须先验证此端口的配置方式。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代 CNA 适配器和端口。但是，命令行界面使用术语 CNA 。

您可以使用 `ucadmin show`命令查看或验证当前端口配置，如以下示例输出所示：

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2 端口可以配置为原生 FC 模式或 UTA/UTA2 模式。FC 模式支持 FC 启动程序和 FC 目标； UTA/UTA2 模式允许并发 NIC 和 FCoE 流量共享相同的 10GbE SFP+ 接口并支持 FC 目标。

您可能会在附加适配器或控制器主板上找到 UTA/UTA2 端口，并具有以下配置，但您应该检查 node3 上的 UTA/UTA2 端口配置，并在必要时进行更改：

* 订购控制器时订购的 UTA/UTA2 卡会在发货前配置为具有您请求的个性化设置。
* 与控制器分开订购的 UTA/UTA2 卡附带了默认的 FC 目标特性。
* 新控制器上的板载 UTA/UTA2 端口会在发货前配置为具有您请求的个性化设置。
+

WARNING: 您必须处于维护模式才能配置 UTA/UTA2 端口。在维护模式 shell 提示符下输入本节中的命令。



.步骤
. 如果当前 SFP+ 模块与所需用途不匹配，请将其更换为正确的 SFP+ 模块。
+
请联系您的 NetApp 代表以获取正确的 SFP+ 模块。

. 验证 UTA/UTA2 端口设置：
+
`ucadmin show`

+
检查输出并确定 UTA/UTA2 端口是否具有您想要的个性。

+
以下示例中的输出显示适配器“1b”的类型正在更改为启动器，并且适配器“2a”和“2b”的模式正在更改为“cna”。  CNA 模式允许您将该卡用作网络适配器。

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 执行以下操作之一：
+
[cols="30,70"]
|===
| 如果 UTA/UTA2 端口 ... | 然后选择… 


| 没有所需的个性化设置 | 前往<<auto_check3_step4,第 4 步>>。 


| 拥有所需的个性化特性 | 跳过步骤 4 至步骤 8，然后转到<<auto_check3_step9,第 9 步>>。 
|===
. [[auto_check3_step4]]请执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要配置 | 然后选择… 


| UTA/UTA2 卡上的端口 | 前往<<auto_check3_step5,第 5 步>> 


| 板载 UTA/UTA2 端口 | 跳过步骤 5 并转到<<auto_check3_step6,第 6 步>>。 
|===
. [[auto_check3_step5]]如果适配器处于启动器模式，并且 UTA/UTA2 端口处于在线状态，则将 UTA/UTA2 端口脱机：
+
`storage disable adapter <adapter_name>`

+
目标模式下的适配器会在维护模式下自动脱机。

. [[auto_check3_step6]]如果当前配置与所需用途不匹配，请根据需要更改配置：
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** ` -m` 是特性模式， `fc` 或 `CNA` 。
** ` -t` 是 FC4 类型， `target` 或 `initiator` 。
+

NOTE: 您必须对磁带驱动器和MetroCluster配置使用 FC 启动器。您必须对 SAN 客户端使用 FC 目标。



. 通过为每个端口输入以下命令，将所有目标端口置于联机状态：
+
`storage enable adapter <adapter_name>`

. 为端口布线。


[[auto_check3_step9]]
. 退出维护模式：
+
`halt`

. 通过运行以下命令将节点启动到启动菜单 `boot_ontap menu`。


.下一步是什么？
* 如果您要升级到AFF A800系统，请转至link:reassign-node1-disks-to-node3.html#auto_check3_step9["将node1磁盘重新分配给node3、步骤9"]。
* 对于所有其他系统升级，请访问link:reassign-node1-disks-to-node3.html["将node1磁盘重新分配给node3、步骤1"]。

