---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: '如果需要、请在使用将运行ONTAP 9.5的控制器升级到9.7时为NVE或NAE配置新控制器模块 `system controller replace` 命令' 
---
= 在新控制器模块上设置NetApp卷或聚合加密
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果新控制器的已更换控制器或高可用性(HA)配对系统使用NetApp卷加密(NVE)或NetApp聚合加密(NAE)、则必须为NVE或NAE配置新控制器模块。

.关于此任务
此操作步骤包含对新控制器模块执行的步骤。您必须在正确的节点上输入命令。

[role="tabbed-block"]
====
.ONTAP 9.6和9.7
--
*在运行ONTAP 9.6或9.7的控制器上配置NVE或NAE *

.步骤
. 验证密钥管理服务器是否仍可用，其状态及其身份验证密钥信息：
+
`sSecurity key-manager key query -node node`

. 将上一步中列出的密钥管理服务器添加到新控制器的密钥管理服务器列表中：
+
.. 添加密钥管理服务器：
+
`security key-manager -add _key_management_server_ip_address_`

.. 对列出的每个密钥管理服务器重复上述步骤。
+
您最多可以链接四个密钥管理服务器。

.. 验证是否已成功添加密钥管理服务器：
+
`sSecurity key-manager show`



. 在新控制器模块上，运行密钥管理设置向导以设置和安装密钥管理服务器。
+
您必须安装与现有控制器模块上安装的密钥管理服务器相同的密钥管理服务器。

+
.. 在新节点上启动密钥管理服务器设置向导：
+
`security key-manager setup -node _new_controller_name_`

.. 完成向导中的步骤以配置密钥管理服务器。


. 将所有链接的密钥管理服务器中的身份验证密钥还原到新节点：
+
** 还原外部密钥管理器的身份验证：
+
`s安全密钥管理器外部还原`

+
此命令需要板载密钥管理器（ OKM ）密码短语。

+
有关详细信息、请参见知识库文章 https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["如何从ONTAP 启动菜单还原外部密钥管理器服务器配置"^]。

** 还原OKM的身份验证：
+
`sSecurity key-manager 板载同步`





--
.ONTAP 9.5
--
*在运行ONTAP 9.5*的控制器上配置NVE或NAE

.步骤
. 验证密钥管理服务器是否仍可用，其状态及其身份验证密钥信息：
+
`sSecurity key-manager key show`

. 将上一步中列出的密钥管理服务器添加到新控制器的密钥管理服务器列表中：
+
.. 添加密钥管理服务器：
+
`security key-manager -add _key_management_server_ip_address_`

.. 对列出的每个密钥管理服务器重复上述步骤。
+
您最多可以链接四个密钥管理服务器。

.. 验证是否已成功添加密钥管理服务器：
+
`sSecurity key-manager show`



. 在新控制器模块上，运行密钥管理设置向导以设置和安装密钥管理服务器。
+
您必须安装与现有控制器模块上安装的密钥管理服务器相同的密钥管理服务器。

+
.. 在新节点上启动密钥管理服务器设置向导：
+
`security key-manager setup -node _new_controller_name_`

.. 完成向导中的步骤以配置密钥管理服务器。


. 将所有链接的密钥管理服务器中的身份验证密钥还原到新节点：
+
** 还原外部密钥管理器的身份验证：
+
`s安全密钥管理器外部还原`

+
此命令需要板载密钥管理器（ OKM ）密码短语。

+
有关详细信息、请参见知识库文章 https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["如何从ONTAP 启动菜单还原外部密钥管理器服务器配置"^]。

** 还原 OKM 的身份验证：
+
`sSecurity key-manager setup -node _node_name_`





--
====
.完成后
检查是否有任何卷因身份验证密钥不可用或无法访问外部密钥管理服务器而脱机。使用 `volume online` 命令将这些卷恢复联机。
