---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports, FlexArray Virtualization 
summary: '在使用 `ssystem controller replace` 命令升级运行 ONTAP 9.5 的控制器时，配置 node3 板载 FC 端口， UTA/UTA2 端口或 UTA/UTA2 卡。' 
---
= 在 node3 上设置 FC 或 UTA/UTA2 配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果 node3 具有板载 FC 端口，板载统一目标适配器（ UTA/UTA2 ）端口或 UTA/UTA2 卡，则必须先配置这些设置，然后才能完成其余操作步骤。

.关于此任务
您可能需要完成此部分 <<在 node3 上配置 FC 端口>>，部分 <<检查并配置 node3 上的 UTA/UTA2 端口>>或这两个部分。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代融合网络适配器（ CNA ）适配器和端口。但是，命令行界面使用术语 CNA 。

* 如果node3没有板载FC端口、板载UTA/UTA2端口或UTA/UTA2卡，并且您要升级具有存储磁盘的系统，则可以跳至link:reassign-node1-disks-to-node3.html["将node1磁盘重新分配给node3"]。
* 但是，如果您的V系列系统或安装了FlexArray虚拟化软件和存储阵列的系统，并且node3没有板载FC端口、板载UTA/UTA端口或UTA/UTA2卡，请返回到_Install and boot node3_并从继续link:install_boot_node3.html#auto_install3_step23["第 23 步"]。




== 在 node3 上配置 FC 端口

如果 node3 具有板载或 FC 适配器上的 FC 端口，则必须先在节点上设置端口配置，然后再将其投入使用，因为这些端口未经过预配置。如果未配置端口，则可能会发生服务中断。

.开始之前
您必须具有在部分中保存的 node1 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则可以在中对其进行配置 <<检查并配置 node3 上的 UTA/UTA2 端口>>。


IMPORTANT: 如果您的系统具有存储磁盘、请在集群提示符处输入本节中的命令。如果您使用的是 V 系列系统或 FlexArray 虚拟化软件并连接到存储阵列，请在维护模式下在此部分中输入命令。

. 【第 1 步】将 node3 上的 FC 设置与先前从 node1 中捕获的设置进行比较。
. 【第 2 步】执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要升级的系统 ... | 然后选择… 


| 具有存储磁盘  a| 
在维护模式（启动菜单中的选项 5 ）下，根据需要修改 node3 上的 FC 端口：

** 要对目标端口进行编程：


`ucadmin modify -m fc -t target _adapter_`

** 要对启动程序端口进行编程：


`ucadmin modify -m fc -t initiator _adapter_`

` -t` 是 FC4 类型： target 或 initiator 。



| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列  a| 
在维护模式（启动菜单中的选项 5 ）下，根据需要修改 node3 上的 FC 端口：

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` 是FC4类型、目标或启动程序。


NOTE: FC端口必须编程为启动程序。

|===
. 【第 3 步】执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要升级的系统 ... | 然后选择… 


| 具有存储磁盘 | 使用以下命令并检查输出，以验证新设置： `ucadmin show` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 使用以下命令并检查输出，以验证新设置： `ucadmin show` 
|===
. 【第 4 步】退出维护模式：
+
`halt`

. 从加载程序提示符启动系统：
+
`boot_ontap 菜单`

. 【第 6 步】输入命令后，请等待系统在启动环境提示符处停止。
. 从维护模式的启动菜单中选择选项 `5` 。


. 执行以下操作之一：
+
|===
| 如果要升级的系统 ... | 然后选择… 


| 具有存储磁盘  a| 
** 如果 node3 具有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请转至 <<检查并配置 node3 上的 UTA/UTA2 端口>>。
** 如果node3没有UTA/UTA2卡或UTA/UTA2板载端口，请跳过<<检查并配置 node3 上的 UTA/UTA2 端口>>并转到link:reassign-node1-disks-to-node3.html["将node1磁盘重新分配给node3"]。




| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列  a| 
** 如果 node3 具有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请转至 <<检查并配置 node3 上的 UTA/UTA2 端口>>。
** 如果node3没有UTA/UTA2卡或UTA/UTA2板载端口，请跳过<<检查并配置 node3 上的 UTA/UTA2 端口>>并返回到_Install并在以下位置的继续处启动node3_link:install_boot_node3.html#auto_install3_step23["第 23 步"]。


|===




== 检查并配置 node3 上的 UTA/UTA2 端口

如果 node3 具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则必须检查这些端口的配置，并可能对其进行重新配置，具体取决于您希望如何使用升级后的系统。

.开始之前
您必须为 UTA/UTA2 端口配备正确的 SFP+ 模块。

.关于此任务
如果要对 FC 使用统一目标适配器（ UTA/UTA2 ）端口，则必须先验证此端口的配置方式。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代 CNA 适配器和端口。但是，命令行界面使用术语 CNA 。

您可以使用 `ucadmin show` 命令验证当前端口配置：

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2 端口可以配置为原生 FC 模式或 UTA/UTA2 模式。FC 模式支持 FC 启动程序和 FC 目标； UTA/UTA2 模式允许并发 NIC 和 FCoE 流量共享相同的 10GbE SFP+ 接口并支持 FC 目标。

UTA/UTA2 端口可能位于适配器或控制器上，并且具有以下配置，但您应检查 node3 上的 UTA/UTA2 端口的配置，并根据需要进行更改：

* 订购控制器时订购的 UTA/UTA2 卡会在发货前配置为具有您请求的个性化设置。
* 与控制器分开订购的 UTA/UTA2 卡附带了默认的 FC 目标特性。
* 新控制器上的板载 UTA/UTA2 端口会在发货前配置为具有您请求的个性化设置。
+

WARNING: * 注意 * ：如果您的系统具有存储磁盘，除非指示您进入维护模式，否则您可以在集群提示符处输入本节中的命令。如果您使用的是 V 系列系统或 FlexArray 虚拟化软件并连接到存储阵列，则可以在维护模式提示符处在此部分中输入命令。要配置 UTA/UTA2 端口，您必须处于维护模式。



.步骤
. 【第 1 步】在 node3 上输入以下命令，以检查端口当前的配置方式：
+
[cols="30,70"]
|===
| 如果系统 ... | 然后选择… 


| 具有存储磁盘 | 无需执行任何操作。 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | `ucadmin show` 
|===
+
系统将显示类似于以下示例的输出：

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. 【第 2 步】如果当前 SFP+ 模块与所需用途不匹配，请将其更换为正确的 SFP+ 模块。
+
请联系您的 NetApp 代表以获取正确的 SFP+ 模块。

. `步骤 3]] 查看` ucadmin show 命令的输出，并确定 UTA/UTA2 端口是否具有所需的个性化设置。
. 【第 4 步】执行以下操作之一：
+
[cols="30,70"]
|===
| 如果 UTA/UTA2 端口 ... | 然后选择… 


| 没有所需的个性化设置 | 转至 <<auto_check3_step5,第 5 步>>。 


| 拥有所需的个性化特性 | 跳过步骤 5 到步骤 12 ，然后转到 <<auto_check3_step13,第 13 步>>。 
|===
. 【 auto_check3_step5]] 执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要配置 | 然后选择… 


| UTA/UTA2 卡上的端口 | 转至 <<auto_check3_step7,第 7 步>> 


| 板载 UTA/UTA2 端口 | 跳过第 7 步，转到 <<auto_check3_step8,第 8 步>>。 
|===
. 【第 6 步】如果适配器处于启动程序模式，并且 UTA/UTA2 端口处于联机状态，请使 UTA/UTA2 端口脱机：
+
`storage disable adapter _adapter_name_`

+
目标模式下的适配器会在维护模式下自动脱机。

. 【 auto_check3_step7]] 如果当前配置与所需用途不匹配，请根据需要更改配置：
+
`ucadmin modify -m fc|cna -t initiators|target _adapter_name_`

+
** ` -m` 是特性模式， `fc` 或 `CNA` 。
** ` -t` 是 FC4 类型， `target` 或 `initiator` 。
+

NOTE: 您必须对磁带驱动器， FlexArray 虚拟化系统和 MetroCluster 配置使用 FC 启动程序。您必须对 SAN 客户端使用 FC 目标。



. 【 auto_check3_step8]] 验证设置：
+
`ucadmin show`

. 【第 9 步】验证设置：
+
[cols="30,70"]
|===
| 如果系统 ... | 然后选择… 


| 具有存储磁盘 | `ucadmin show` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | `ucadmin show` 
|===
+
以下示例中的输出显示， FC4 类型的适配器 "1b" 更改为 `initiator` ，适配器 "2a" 和 "2b" 的模式更改为 `CNA` ：

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. 【第 10 步】输入以下命令之一，使所有目标端口联机，每个端口输入一次：
+
[cols="30,70"]
|===
| 如果系统 ... | 然后选择… 


| 具有存储磁盘 | `network fcp adapter modify -node _node_name_-adapter _adapter_name_-state up` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | `FCP config _adapter_name_ up` 
|===
. 【第 11 步】为端口布线。


. [[auto_check3_step12]] 执行以下操作之一：


[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘 | 转到。 link:reassign-node1-disks-to-node3.html["将node1磁盘重新分配给node3"] 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 返回到 _Install and boot node3_ 并继续中的部分 link:install_boot_node3.html#auto_install3_step23["第 23 步"]。 
|===
. 【 auto_check3_step13]] 退出维护模式：
+
`halt`

. [[STEP14]]通过运行将节点启动至启动菜单 `boot_ontap menu`。如果要升级到AFF A800系统，请转至link:reassign-node1-disks-to-node3.html#auto_check3_step9["将node1磁盘重新分配给node3、步骤9"]。

