---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: '在使用 `ssystem controller replace` 命令升级运行 ONTAP 9.5 的控制器时，配置 node4 板载 FC 端口， UTA/UTA2 端口或 UTA/UTA2 卡。' 
---
= 在 node4 上设置 FC 或 UTA/UTA2 配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果 node4 具有板载 FC 端口，板载统一目标适配器（ UTA/UTA2 ）端口或 UTA/UTA2 卡，则必须先配置这些设置，然后才能完成其余操作步骤。

.关于此任务
您可能需要完成<<在节点 4 上配置 FC 端口>>或者<<检查并配置 node4 上的 UTA/UTA2 端口>>或两个部分。

[NOTE]
====
如果node4没有板载FC端口、板载UTA/UTA2端口或UTA/UTA2卡，并且您要升级具有存储磁盘的系统，则可以跳至link:reassign-node2-disks-to-node4.html["将node2磁盘重新分配给node4"]。

确保 node4 具有足够的机架空间。如果 node4 与 node2 位于不同的机箱中，则可以将 node4 与 node3 放在同一位置。如果 node2 和 node4 位于同一机箱中，则 node4 已位于其相应的机架位置。

====


== 在节点 4 上配置 FC 端口

如果节点 4 具有 FC 端口（无论是板载的还是附加 FC 适配器上的），则必须在节点投入使用之前设置其端口配置，因为系统出厂时未预先配置端口。如果您没有按要求配置端口，则可能会遇到服务中断。

.开始之前
您必须具有在部分中保存的 node2 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 适配器，则可以在中对其进行配置 <<检查并配置 node4 上的 UTA/UTA2 端口>>。


IMPORTANT: 在维护模式 shell 提示符下输入本节中的命令。

.步骤
. 显示系统上所有 FC 和融合网络适配器的信息：
+
`ssystem node hardware unified-connect show`

. 将 node4 上的 FC 设置与先前从 node1 中捕获的设置进行比较。
. 根据需要修改 node4 上的 FC 端口：
+
** 要作为目标端口进行编程：
+
`ucadmin modify -m fc -t target _adapter_`

+
例如： `ucadmin modify -m fc -t target 2a`

** 要对启动程序端口进行编程：
+
`ucadmin modify -m fc -t initiator _adapter_`

+
` -t` 是 FC4 类型： target 或 initiator 。

+
例如： `ucadmin modify -m fc -t initator 2b`



. 暂停节点：
+
`halt`

. 从加载程序提示符启动系统：
+
`boot_ontap 菜单`

. 输入命令后，请等待，直到系统停留在启动环境提示符处。
. 从维护模式的启动菜单中选择选项 `5` 。


. [[step8]]跳过此部分并转到link:reassign-node2-disks-to-node4.html["将node2磁盘重新分配给node4"]如果 node4 没有 UTA/UTA2 卡或 UTA/UTA2 板载端口。




== 检查并配置 node4 上的 UTA/UTA2 端口

如果 node4 具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则必须检查这些端口的配置并进行配置，具体取决于您希望如何使用升级后的系统。

.开始之前
您必须为 UTA/UTA2 端口配备正确的 SFP+ 模块。

.关于此任务
UTA/UTA2 端口可以配置为原生 FC 模式或 UTA/UTA2 模式。FC 模式支持 FC 启动程序和 FC 目标； UTA/UTA2 模式允许并发 NIC 和 FCoE 流量共享相同的 10GbE SFP+ 接口并支持 FC 目标。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代 CNA 适配器和端口。但是，命令行界面使用术语 CNA 。

UTA/UTA2 端口可能位于具有以下配置的适配器或控制器上：

* 与控制器同时订购的 UTA/UTA2 卡会在发货前配置为具有您请求的个性化设置。
* 与控制器分开订购的 UTA/UTA2 卡附带了默认的 FC 目标特性。
* 新控制器上的板载 UTA/UTA2 端口（发货前）已配置为具有您请求的个性化设置。


但是，您应检查 node4 上的 UTA/UTA2 端口的配置，并根据需要进行更改。


WARNING: 在维护模式 shell 提示符下输入本节中的命令。

.步骤
. 检查 node4 上端口的当前配置情况：
+
`ssystem node hardware unified-connect show`

+
系统将显示类似于以下示例的输出：

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 如果当前 SFP+ 模块与所需用途不匹配，请将其更换为正确的 SFP+ 模块。
+
请联系您的 NetApp 代表以获取正确的 SFP+ 模块。

. 验证设置：
+
`ucadmin show`

+
检查 `ucadmin show` 命令的输出，并确定 UTA/UTA2 端口是否具有所需的个性化设置。

+
以下示例中的输出显示， FC4 类型的适配器 "1b" 更改为 `initiator` ，适配器 "2a" 和 "2b" 的模式更改为 `CNA` ：

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 执行以下操作之一：
+
[cols="30,70"]
|===
| 如果 CNA 端口 ... | 然后选择… 


| 没有所需的个性化设置 | 转至 <<auto_check_4_step5,第 5 步>>。 


| 拥有所需的个性化特性 | 跳过步骤 5 至步骤 9，然后转到<<auto_check_4_step10,第 10 步>>。 
|===
. 【 auto_check_4_step5]] 执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要配置 | 然后选择… 


| UTA/UTA2 卡上的端口 | 前往<<auto_check_4_step6,第 6 步>> 


| 板载 UTA/UTA2 端口 | 跳过第 6 步并转到<<auto_check_4_step7,第 7 步>>。 
|===
. [[auto_check_4_step6]]如果适配器处于启动器模式，并且 UTA/UTA2 端口处于在线状态，则将 UTA/UTA2 端口脱机：
+
`storage disable adapter _adapter_name_`

+
目标模式下的适配器会在维护模式下自动脱机。

. 【 auto_check_4_step7]] 如果当前配置与所需用途不匹配，请根据需要更改配置：
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** ` -m` 是个性化模式， FC 或 10GbE UTA 。
** ` -t` 是 FC4 类型， `target` 或 `initiator` 。
+

NOTE: 您必须对磁带驱动器和MetroCluster配置使用 FC 启动器。您必须对 SAN 客户端使用 FC 目标。



. 输入以下命令（每个端口一次），使任何目标端口联机：
+
`storage enable adapter <adapter_name>`

. 为端口布线。


. [[auto_check_4_step10]]退出维护模式：
+
`halt`

. 将节点启动至启动菜单：
+
`boot_ontap 菜单`



.下一步是什么？
* 如果要升级到AFF A800系统，请转至link:reassign-node2-disks-to-node4.html#auto_check_4_step9["将node2磁盘重新分配给node4、步骤9"]。
* 对于所有其他系统升级，请访问link:reassign-node2-disks-to-node4.html["将node2磁盘重新分配给node4、步骤1"]。

