---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node4_installation.html 
keywords: verify, node4, installation, MetroCluster, restore, key, manager 
summary: '使用 `ssystem controller replace` 命令将运行 ONTAP 9.5 的控制器升级到 9.7 时，验证 node4 是否加入仲裁，重新创建 node1 的 VLAN ，接口组和广播域，并还原密钥管理器配置。' 
---
= 验证 node4 安装
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
安装并启动 node4 后，您必须验证它是否已正确安装，是否属于集群，以及是否可以与 node3 通信。

此时，在操作步骤中，操作将暂停，因为 node4 加入仲裁。

.步骤
. 验证 node4 是否已加入仲裁：
+
`cluster show -node node4 -fields health`

. 输入以下命令，验证 node4 是否与 node3 属于同一集群且运行状况良好：
+
`cluster show`

. 检查操作状态，并验证 node4 的配置信息是否与 node2 相同：
+
`s系统控制器更换 show-details`

+
如果 node4 的配置不同，则稍后可能会在操作步骤中发生系统中断。

. 检查更换的控制器是否已正确配置 MetroCluster 配置，而不是处于切换模式。
+

CAUTION: * 注意： * 在此阶段， MetroCluster 配置将不会处于正常状态，您可能会遇到需要解决的错误。请参见 link:verify_health_of_metrocluster_config.html["验证 MetroCluster 配置的运行状况。"]。





== 在 node4 上重新创建 VLAN ，接口组和广播域

确认 node4 处于仲裁状态并可与 node3 通信后，您必须在 node4 上重新创建 node2 的 VLAN ，接口组和广播域。您还必须将 node3 端口添加到新重新创建的广播域中。

有关创建和重新创建 VLAN ，接口组和广播域的详细信息，请访问 link:other_references.html["参考资料"] 并链接到 _Network Management_ 。

.步骤
. 使用中记录的 node2 信息在 node4 上重新创建 VLAN link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3"] 部分。
+
`network port vlan create -node <node4> -vlan <vlan-name>`

. 使用中记录的 node2 信息在 node4 上重新创建接口组 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3"] 部分。
+
`network port ifgrp create -node <node4>-ifgrp <port_ifgrp_names>-cluster-func`

. 使用中记录的 node2 信息在 node4 上重新创建广播域 link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3"] 部分。
+
`network port broadcast-domain create -ipspace default -broadcast-domain <broadcast_domain_name> -mtu <mt_size> -ports <node_name ： port_name ， node_name ： port_name>`

. 将 node4 端口添加到新重新创建的广播域：
+
`network port broadcast-domain add-ports -broadcast-domain <broadcast_domain_name> -ports <node_name ： port_name ， node_name ： port_name>`





== 还原 node4 上的 key-manager 配置

如果使用 NetApp 卷加密（ NVE ）对要升级的系统上的卷进行加密，则加密配置必须与新节点同步。从 node2 到 node4 的 node1 聚合的 ARL 完成后，加密卷将脱机。

.步骤
. 要同步板载密钥管理器的加密配置，请在集群提示符处运行以下命令：
+
|===
| 对于此 ONTAP 版本… | 使用此命令 ... 


| ONTAP 9.6 或 9.7 | 安全密钥管理器板载同步 


| ONTAP 9.5 | security key-manager setup -node <node_name> 
|===
. 输入板载密钥管理器的集群范围密码短语。

