---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node3_installation.html 
keywords: install, boot, node3, join quorum, restore, key, manager 
summary: '使用 `ssystem controller replace` 命令将运行 ONTAP 9.5 的控制器升级到 9.7 时，验证 node3 是否加入仲裁，重新创建 node1 的 VLAN ，接口组和广播域，并还原密钥管理器配置。' 
---
= 验证 node3 安装
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
安装并启动 node3 后，您必须验证是否已正确安装它。您必须等待 node3 加入仲裁，然后恢复重新定位操作。

此时，在操作步骤中，操作将暂停，因为 node3 加入仲裁。

.步骤
. 验证 node3 是否已加入仲裁：
+
`cluster show -node node3 -fields health`

. 确认 node3 与 node2 属于同一集群，并且运行状况良好：
+
`cluster show`

. 检查操作状态，并验证 node3 的配置信息是否与 node1 相同：
+
`s系统控制器更换 show-details`

+
如果 node3 的配置不同，则稍后可能会在操作步骤中发生系统中断。

. 检查更换的控制器是否已针对 MetroCluster 配置正确配置， MetroCluster 配置应处于运行状况良好，而不是切换模式。请参见 link:verify_health_of_metrocluster_config.html["验证 MetroCluster 配置的运行状况。"]。




== 在 node3 上重新创建 VLAN ，接口组和广播域

确认 node3 处于仲裁状态并可与 node2 通信后，您必须在 node3 上重新创建 node1 的 VLAN ，接口组和广播域。您还必须将 node3 端口添加到新重新创建的广播域中。

有关创建和重新创建 VLAN ，接口组和广播域的详细信息，请访问 link:other_references.html["参考资料"] 并链接到 _Network Management_ 。

.步骤
. 使用中记录的 node1 信息在 node3 上重新创建 VLAN link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2"] 部分。
+
`网络端口vlan create -node _node_name_-vlan _vlan-name_`

. 使用中记录的 node1 信息在 node3 上重新创建接口组 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2"] 部分。
+
`network port ifgrp create -node _node_name_-ifgrp _port_ifgrp_name_-cluster-func`

. 使用中记录的 node1 信息在 node3 上重新创建广播域 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["将节点 1 拥有的非根聚合和 NAS 数据 LIF 重新定位到节点 2"] 部分。
+
`network port broadcast-domain create -ipspace default -broadcast-domain _broadcast_domain_name_-mtu _mtu _size_-ports _node_name：port_name、node_name：port_name_`

. 将 node3 端口添加到新重新创建的广播域：
+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_name_-ports _node_name：port_name、node_name：port_name_`





== 还原 node3 上的 key-manager 配置

如果使用 NetApp 卷加密（ NVE ）对要升级的系统上的卷进行加密，则加密配置必须与新节点同步。如果不还原key-manager、则在使用ARL将node1聚合从node2重新定位到node3时、加密卷将脱机。

.步骤
. 要同步板载密钥管理器的加密配置，请在集群提示符处运行以下命令：
+
|===
| 对于此 ONTAP 版本… | 使用此命令 ... 


| ONTAP 9.6 或 9.7 | `sSecurity key-manager 板载同步` 


| ONTAP 9.5 | `sSecurity key-manager setup -node _node_name_` 
|===
. 输入板载密钥管理器的集群范围密码短语。

