---
sidebar: sidebar 
permalink: upgrade-arl-auto-mendocino/install_a900_nvs_and_controller_on_node2.html 
keywords: install, nvs, aff, a900, node2, controller, module 
summary: 在节点 2 上安装 AFF A900 NVS 和控制器模块。 
---
= 在节点 2 上安装 AFF A900 NVS 和控制器模块
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必须在 node2 上安装为升级而收到的 AFF A900 NVS 和控制器模块。node2 是从系统背面查看控制器时位于机箱右侧的控制器 B 。

如果您尚未接地，请正确接地。



== 安装 AFF A900 NVS

使用以下操作步骤将 AFF A900 NVS 安装在节点 2 的插槽 6 中。

.步骤
. 将 NVS 与插槽 6 中机箱开口的边缘对齐。
. 将 NVS 轻轻滑入插槽，直到带字母和编号的 I/O 凸轮闩锁开始与 I/O 凸轮销啮合，然后将 I/O 凸轮闩锁一直向上推，以将 NVS 锁定到位。




== 在节点 2 中安装 AFF A900 控制器模块。

使用以下操作步骤在 node2 中安装 AFF A900 控制器模块。

.步骤
. 将控制器模块的末端与机箱中的托架 B 对齐，然后将控制器模块轻轻推入系统的一半。
+

TIP: 托架标签位于机箱上控制器模块正上方。

+

NOTE: 在系统指示您将控制器模块完全插入机箱之前，请勿将其插入。

. 使用缆线将管理和控制台端口连接到 node2 控制器模块。
+

NOTE: 由于机箱已启动，因此 Node2 在完全就位后即开始启动。为了避免 node2 启动，建议在将控制器模块完全插入插槽之前，先将控制台和管理缆线连接到 node2 控制器模块。

. Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
控制器模块完全就位后，锁定闩锁会上升。

+

WARNING: Do not use excessive force when sliding the controller module into the chassis to avoid damaging the connectors.

. 一旦模块就位，请立即连接串行控制台，并准备好中断 node1 的自动启动。
. 中断自动启动后， node2 将停留在 LOADER 提示符处。如果不中断自动启动，而 node2 开始启动，请等待提示符按 * Ctrl-C* 进入启动菜单。在节点停留在启动菜单后，使用选项 `8` 重新启动节点，并在重新启动期间中断自动启动。

