= 
:allow-uri-read: 


. 在自动启动期间按 `Ctrl-C` 在 `LOADER>` 提示符处停止节点。
. 在 LOADER 提示符处，进入维护模式：
+
`boot_ontap maint`

. 在维护模式下，显示先前设置的所有启动程序端口，这些端口现在处于目标模式：
+
`ucadmin show`

+
将端口改回启动程序模式：

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. 验证端口是否已更改为启动程序模式：
+
`ucadmin show`

. 退出维护模式：
+
`halt`

+
[NOTE]
====
如果要从支持外部磁盘的系统升级到也支持外部磁盘的系统、请转至 <<auto_check_4_step22,第 22 步>>。

如果要从使用外部磁盘的系统升级到同时支持内部和外部磁盘的系统、例如AFF A800系统、请转至 <<auto_check_4_step23,第 23 步>>。

====
. 在LOADER提示符处、启动：
+
`boot_ontap 菜单`

+
现在，在启动时，节点可以检测到先前分配给它的所有磁盘，并可按预期启动。

+
如果要替换的集群节点使用根卷加密、则ONTAP 软件将无法从磁盘读取卷信息。还原根卷的密钥：

+
.. 返回到特殊的启动菜单：
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. 选择*(10)设置板载密钥管理器恢复密钥*
.. 输入 ... `y` 在以下提示符处：
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. 在提示符处、输入密钥管理器密码短语。
.. 出现提示时、输入备份数据。
+

NOTE: 您必须已在中获取密码短语和备份数据 link:prepare_nodes_for_upgrade.html["准备要升级的节点"] section of this procedure.

.. 系统重新启动到特殊启动菜单后、运行选项*(1) Normal Boot*
+

NOTE: 您可能会在此阶段遇到错误。如果发生错误、请重复中的子步骤 <<auto_check_4_step22,第 22 步>> 直到系统正常启动。




