= 在 node3 上配置 FC 端口
:allow-uri-read: 




== 在 node3 上配置 FC 端口

如果 node3 具有板载或 FC 适配器上的 FC 端口，则必须先在节点上设置端口配置，然后再将其投入使用，因为这些端口未经过预配置。如果未配置端口，则可能会发生服务中断。

.开始之前
您必须具有在部分中保存的 node1 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则可以在中对其进行配置 <<检查并配置 node3 上的 UTA/UTA2 端口>>。

* 重要信息 * ：如果您的系统具有存储磁盘，请在集群提示符处输入本节中的命令。如果您使用的是 V 系列系统或 FlexArray 虚拟化软件并连接到存储阵列，请在维护模式下在此部分中输入命令。

. 【第 1 步】将 node3 上的 FC 设置与先前从 node1 中捕获的设置进行比较。
. 【第 2 步】执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要升级的系统 ... | 然后选择… 


| 具有存储磁盘  a| 
在维护模式（启动菜单中的选项 5 ）下，根据需要修改 node3 上的 FC 端口：

** 要对目标端口进行编程：


`ucadmin modify -m fc -t target _adapter_`

** 要对启动程序端口进行编程：


`ucadmin modify -m fc -t initiator _adapter_`

` -t` 是 FC4 类型： target 或 initiator 。



| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 在维护模式(启动菜单中的选项5)下、根据需要修改node3上的FC端口：`ucadmin modify -m fc -t initiator -f _adapter_port_name_``-t`是FC4类型、目标或启动程序。* 注 * ：必须将 FC 端口编程为启动程序。 
|===
. 【第 3 步】执行以下操作之一：
+
[cols="30,70"]
|===
| 如果要升级的系统 ... | 然后选择… 


| 具有存储磁盘 | 使用以下命令并检查输出，以验证新设置： `ucadmin show` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 使用以下命令并检查输出，以验证新设置： `ucadmin show` 
|===
. 【第 4 步】退出维护模式：
+
`halt`

. 从 LOADER 提示符启动系统：
+
`boot_ontap 菜单`

. 【第 6 步】输入命令后，请等待系统在启动环境提示符处停止。
. 从维护模式的启动菜单中选择选项 `5` 。

