= 
:allow-uri-read: 


如果 node4 的 ONTAP 9 版本与 node2 上安装的版本不同，则需要对其进行网络启动。安装 node4 后，从 Web 服务器上存储的 ONTAP 9 映像启动它。然后，您可以按照中的说明将正确的文件下载到启动介质设备，以供后续系统启动 link:prepare_for_netboot.html["准备网络启动"]。

[IMPORTANT]
====
* 对于 AFF A800 或 AFF C800 控制器升级，在移除节点 2 之前，必须确保机箱中的所有驱动器都牢固地固定在中板上。有关详细信息，请参见 link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["更换AFF A800或AFF C800控制器模块"]。
* 如果您要升级带有存储磁盘的系统，则必须完成整个部分，然后继续link:set_fc_or_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"] ，在集群提示符下输入命令。


====
.步骤
. 【 auto_install4_step1]] 确保 node4 具有足够的机架空间。
+
如果 node4 与 node2 位于不同的机箱中，则可以将 node4 与 node3 放在同一位置。如果 node2 和 node4 位于同一机箱中，则 node4 已位于其相应的机架位置。

. 按照节点型号的 _Installation and Setup Instructions_中 的说明，在机架中安装 node4 。
. 为节点 4 布线，将连接从节点 2 移至节点 4 。
+
使用 node4 平台的《安装和设置说明》、相应的磁盘架文档和《HA 对管理》文档连接以下连接。

+
参考link:other_references.html["参考资料"]链接到_HA 对管理_。

+
** 控制台（远程管理端口）
** 集群端口
** 数据端口
** 集群和节点管理端口
** 存储
** SAN 配置： iSCSI 以太网和 FC 交换机端口
+

NOTE: 您可能不需要将互连卡 /FC-VI 卡或互连 /FC-VI 缆线连接从 node2 移至 node4 ，因为大多数平台型号都具有唯一的互连卡型号。对于 MetroCluster 配置，必须将 FC-VI 缆线连接从 node2 移至 node4 。如果新主机没有 FC-VI 卡，则可能需要移动 FC-VI 卡。



. 打开 node4 的电源，然后在控制台终端按 Ctrl-C 以访问启动环境提示符，从而中断启动过程。
+

NOTE: 启动 node4 时，您可能会看到以下警告消息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 如果您在步骤 4 中看到警告消息，请执行以下操作：
+
.. 检查是否存在任何可能指示 NVRAM 电池电量低以外问题的控制台消息，如有必要，请采取任何必要的更正措施。
.. 让电池充电并完成启动过程。
+

WARNING: *请勿超越延迟；如果电池无法充电，可能会导致数据丢失。*

+

NOTE: 请参见 link:prepare_for_netboot.html["准备网络启动"]。




