= 
:allow-uri-read: 


您必须在机架中安装 node3 ，将 node1 的连接传输到 node3 ，启动 node3 并安装 ONTAP 。此外，您还必须重新分配 node1 的任何备用磁盘，属于根卷的任何磁盘以及先前未重新定位到 node2 的任何非根聚合。

.关于此任务
如果 node3 上没有安装与 node1 上相同版本的 ONTAP 9，则必须通过网络启动 node3。安装 node3 后，从 Web 服务器上存储的 ONTAP 9 映像启动它。然后，您可以将正确的文件下载到启动介质设备，以供后续系统启动。请参阅。 link:prepare_for_netboot.html["准备网络启动"]

但是，如果 node3 上安装的 ONTAP 9 与 node1 上安装的 ONTAP 9 相同或更高版本，则无需通过网络启动 node3。

[IMPORTANT]
====
* 对于AFF A800或AFF C800控制器升级，在移除节点 1 之前，必须确保机箱中的所有驱动器都牢固地固定在中板上。有关详细信息，请参阅 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更换AFF A800或AFF C800控制器模块"]。
* 如果您要升级带有存储磁盘的系统，则必须完成整个部分，然后转到link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在 node3 上配置 FC 端口"]和link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["检查并配置 node3 上的 UTA/UTA2 端口"] ，在集群提示符下输入命令。


====
.步骤
. 【 man_install3_step1]] 确保为 node3 预留机架空间。
+
如果 node1 和 node2 位于不同的机箱中，则可以将 node3 与 node1 放在同一机架位置。但是、如果node1与node2位于同一机箱中、则必须将node3放入其自身的机架空间、最好靠近node1的位置。

. 【第 2 步】按照适用于您的节点型号的 _Installation and Setup Instructions_ 在机架中安装 node3 。
+

NOTE: 如果要升级到两个节点位于同一机箱中的系统，请在机箱中安装 node4 以及 node3 。否则，在启动 node3 时，该节点的行为将如同处于双机箱配置中，而在启动 node4 时，节点之间的互连将不会启动。

. 【第 3 步】为节点 3 布线，将节点 1 的连接移至节点 3 。
+
以下参考资料可帮助您正确进行缆线连接。转至 link:other_references.html["参考资料"] 以链接到它们。

+
** node3 平台的_安装和设置说明_
** 相应的磁盘架操作步骤
** HA对管理文档


+
使用缆线连接以下连接：

+
** 控制台（远程管理端口）
** 集群端口
** 数据端口
** 集群和节点管理端口
** 存储
** SAN 配置： iSCSI 以太网和 FC 交换机端口
+

NOTE: 您可能不需要将互连卡或集群互连缆线连接从 node1 移至 node3 ，因为大多数平台型号都具有唯一的互连卡型号。对于MetroCluster 配置、必须将FC-VI缆线连接从node1移至node3。如果新主机没有 FC-VI 卡，则可能需要移动 FC-VI 卡。



. 【 man_install3_step4]] 打开 node3 的电源，然后在控制台终端上按 Ctrl-C 以访问启动环境提示符，从而中断启动过程。
+
如果要升级到两个节点位于同一机箱中的系统， node4 也会重新启动。但是，您可以忽略 node4 启动，直到稍后再启动。

+

NOTE: 启动 node3 时，您可能会看到以下警告消息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. 如果您在中看到警告消息，则需要执行以下操作 <<man_install3_step4,第 4 步>>，执行以下操作：
+
.. 检查是否存在任何可能指示 NVRAM 电池电量低以外问题的控制台消息，如有必要，请采取任何必要的更正措施。
.. 让电池充电并完成启动过程。
+

WARNING: *请勿超越延迟；如果电池无法充电，可能会导致数据丢失。*



. 在维护模式提示符下，输入以下命令：
+
`halt`

+
系统将在启动环境提示符处停止。

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级到的系统位于 ... | 那么 ... 


| 双机箱配置（控制器位于不同机箱中） | 前往<<man_install3_step8,第 8 步>>。 


| 单机箱配置（控制器位于同一机箱中）  a| 
.. 将控制台缆线从 node3 切换到 node4 。
.. 打开 node4 的电源，然后在控制台终端按 Ctrl-C 以访问启动环境提示符，从而中断启动过程。
+
如果两个控制器位于同一机箱中，则应已打开电源。

+

NOTE: 在启动环境提示符处保留node4；您将返回到中的node4 link:install_boot_node4.html["安装并启动节点 4."]。

.. 如果您在中看到警告消息，请执行此操作 <<man_install3_step4,第 4 步>>，按照中的说明进行操作 <<man_install3_step5,第 5 步>>
.. 将控制台缆线从 node4 切回到 node3 。
.. 前往<<man_install3_step8,第 8 步>>。


|===
. [[man_install3_step8]]为ONTAP配置 node3：
+
`set-defaults`


