= 检查并配置 node3 上的 UTA/UTA2 端口
:allow-uri-read: 




== 检查并配置 node3 上的 UTA/UTA2 端口

如果 node3 具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则必须检查这些端口的配置，并可能对其进行重新配置，具体取决于您希望如何使用升级后的系统。

.开始之前
您必须为 UTA/UTA2 端口配备正确的 SFP+ 模块。

.关于此任务
如果要对 FC 使用统一目标适配器（ UTA/UTA2 ）端口，则必须先验证此端口的配置方式。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代 CNA 适配器和端口。但是，命令行界面使用术语 CNA 。

您可以使用 `ucadmin show` 命令验证当前端口配置：

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
UTA/UTA2 端口可以配置为原生 FC 模式或 UTA/UTA2 模式。FC 模式支持 FC 启动程序和 FC 目标； UTA/UTA2 模式支持并发 NIC 和 FCoE 流量共享相同的 10GbE SFP+ 接口并支持 FC 目标。

UTA/UTA2 端口可能位于适配器或控制器上，并且具有以下配置，但您应检查 node3 上的 UTA/UTA2 端口的配置，并根据需要进行更改：

* 订购控制器时订购的 UTA/UTA2 卡会在发货前配置为具有您请求的个性化设置。
* 与控制器分开订购的 UTA/UTA2 卡附带了默认的 FC 目标特性。
* 新控制器上的板载 UTA/UTA2 端口会在发货前配置为具有您请求的个性化设置。
+

NOTE: 除非指示进入维护模式，否则请在集群提示符下输入本节中的命令。



.步骤
. 通过在 node3 上输入以下命令来检查当前端口配置：
+
`ssystem node hardware unified-connect show`

+
系统将显示类似于以下示例的输出：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. 【第 2 步】如果当前 SFP+ 模块与所需用途不匹配，请将其更换为正确的 SFP+ 模块。
+
请联系您的 NetApp 代表以获取正确的 SFP+ 模块。

. `s步骤 3]] 查看` system node hardware unified-connect show `或` ucadmin show 命令的输出，以确定 UTA/UTA2 端口是否具有所需的个性化设置。
. 【第 4 步】执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 UTA/UTA2 端口 ... | 那么 ... 


| 没有所需的个性化设置 | 转至 <<man_check_3_step5,第 5 步>>。 


| 拥有所需的个性化特性 | 跳过步骤 5 至步骤 13，然后转到<<man_check_3_step14,第 14 步>>。 
|===
. [[man_check_3_step5]]如果系统有存储磁盘并且正在运行集群模式Data ONTAP 8.3，则启动节点 3 并进入维护模式：
+
`boot_ontap maint`

. 验证设置：
+
`ucadmin show`

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要配置 | 那么 ... 


| UTA/UTA2 卡上的端口 | 前往<<man_check_3_step8,第 8 步>>。 


| 板载 UTA/UTA2 端口 | 跳过第 8 步并转到<<man_check_3_step9,第 9 步>>。 
|===
. [[man_check_3_step8]]如果适配器处于启动器模式，并且 UTA/UTA2 端口处于在线状态，则将 UTA/UTA2 端口脱机：
+
`storage disable adapter _adapter_name_`

+
目标模式下的适配器会在维护模式下自动脱机。

. [[man_check_3_step9]]如果当前配置与所需用途不匹配，请根据需要更改配置：
+
`ucadmin modify -m fc|cna -t initiators|target _adapter_name_`

+
** ` -m` 是特性模式， `fc` 或 `CNA` 。
** ` -t` 是 FC4 类型， `target` 或 `initiator` 。
+

NOTE: 您必须对磁带驱动器和MetroCluster配置使用 FC 启动器。您必须对 SAN 客户端使用 FC 目标。



. 停止系统：
+
`halt`

+
系统将在启动环境提示符处停止。

. 输入以下命令：
+
`boot_ontap`

. 【第 11 步】验证设置：
+
`ssystem node hardware unified-connect show`

+
以下示例中的输出显示， FC4 类型的适配器 "1b" 更改为 `initiator` ，适配器 "2a" 和 "2b" 的模式更改为 `CNA` ：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]通过对每个端口输入以下命令，将所有目标端口置于联机状态：
+
`network fcp adapter modify -node _node_name_-adapter _adapter_name_-state up`

. [[man_check_3_step14]]连接端口。

