= 在 node3 上配置 FC 端口
:allow-uri-read: 




== 在 node3 上配置 FC 端口

如果节点 3 具有 FC 端口（无论是板载的还是附加 FC 适配器上的），则必须在节点投入使用之前设置其端口配置，因为系统出厂时未预先配置端口。如果您不配置端口，则可能会遇到服务中断。

.开始之前
您必须具有保存在中的 node1 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则可以在中对其进行配置 <<检查并配置 node3 上的 UTA/UTA2 端口>>。


IMPORTANT: 在集群提示符下输入本节中的命令。

.步骤
. 显示有关系统上所有 FC 和融合网络适配器的信息。
+
`ssystem node hardware unified-connect show`

. 将节点 3 的 FC 设置与您之前从节点 1 捕获的设置进行比较。
. [[man_config_3_step3]]执行以下操作之一：
+
[cols="35,65"]
|===
| 新节点上的默认 FC 设置 | 那么 ... 


| 与您在 node1 上捕获的相同 | 前往<<man_config_3_step9,第 9 步>>。 


| 与您在 node1 上捕获的不同 | 前往<<man_config_3_step4,第 4 步>>。 
|===
. [[man_config_3_step4]]根据需要，通过输入以下命令之一修改 node3 上的 FC 端口：
+
** 要对目标端口进行编程：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** 要对启动程序端口进行编程：
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
` -t` 是 FC4 类型： target 或 initiator 。



. 通过输入以下命令并检查输出来验证新设置：
+
`ssystem node hardware unified-connect show`

. 退出维护模式：
+
`halt`

. 输入命令后，请等待，直到系统停留在启动环境提示符处。
. 在启动环境提示符下启动 node3：
+
`boot_ontap`

. [[man_config_3_step9]]执行以下操作之一：
+
** 如果 node3 具有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请转至 <<检查并配置 node3 上的 UTA/UTA2 端口>>。
** 如果 node3 没有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请跳过 <<检查并配置 node3 上的 UTA/UTA2 端口>> 然后转到 link:map_ports_node1_node3.html["将端口从 node1 映射到 node3"]。



