= 
:allow-uri-read: 


您必须在机架中安装 node4 ，将 node2 连接传输到 node4 以及启动 node4 。此外，还必须重新分配任何 node2 备用磁盘，属于 root 的任何磁盘以及先前未重新定位到 node3 的任何非根聚合。

.关于此任务
如果节点 4 上的ONTAP版本与节点 2 上的ONTAP版本不同，则必须对节点 4 进行网络启动。安装 node4 后，从存储在 Web 服务器上的ONTAP 9 映像启动它。然后，您可以按照说明将正确的文件下载到启动介质设备，以便后续系统启动。 link:prepare_for_netboot.html["准备网络启动"]

但是，如果 node4 上的ONTAP版本与 node2 上的ONTAP版本相同或更高，则无需对 node4 进行网络启动。

[IMPORTANT]
====
* 对于AFF A800或AFF C800控制器升级，在移除节点 2 之前，必须确保机箱中的所有驱动器都牢固地固定在中板上。有关详细信息，请参阅 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更换AFF A800或AFF C800控制器模块"]。
* 如果您要升级带有存储磁盘的系统，则必须完成整个部分，然后继续执行下一节link:set_fc_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"] ，在集群提示符下输入命令。


====
.步骤
. [[man_install4_Step1]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 node4 将位于 ... | 那么 ... 


| 与 node3 不同的机箱 | 转至 <<man_install4_Step2,第 2 步>>。 


| 具有 node3 的同一机箱 | 跳过步骤 2 和 3 ，然后转到 <<man_install4_Step4,第 4 步>>。 
|===
. [[man_install4_Step2]] 确保 node4 具有足够的机架空间。
+
如果 node4 与 node3 位于不同的机箱中，则可以将 node4 与 node2 放在同一位置。如果 node3 和 node4 位于同一机箱中，则 node4 已位于其相应的机架位置。

. 按照节点型号的 _Installation and Setup Instructions_中 的说明，在机架中安装 node4 。
. 【 man_install4_Step4]] 为节点 4 布线，将连接从节点 2 移动到节点 4 。
+
以下参考资料可帮助您正确进行缆线连接。转至 link:other_references.html["参考资料"] 以链接到它们。

+
** node4 平台的_安装和设置说明_
** 相应的磁盘架操作步骤
** HA对管理文档
+
使用缆线连接以下连接：

** 控制台（远程管理端口）
** 集群端口
** 数据端口
** 集群和节点管理端口
** 存储
** SAN 配置： iSCSI 以太网和 FC 交换机端口


+

NOTE: 您无需将互连卡 /FC_VI 卡或互连 /FC_VI 缆线连接从 node2 移至 node4 ，因为大多数平台型号都具有唯一的互连卡型号。

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 node4 位于 ... | 那么 ... 


| 与 node3 相同的机箱 | 转至 <<man_install4_Step8,第 8 步>>。 


| 与 node3 不同的机箱 | 转至 <<man_install4_Step6,第 6 步>>。 
|===
. [[man_install4_step6]]打开node4的电源、然后按Ctrl-C访问启动环境提示符以中断启动。
+

NOTE: 启动 node4 时，您可能会看到以下消息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. 【 ｛ man_install4_Step7]] 如果您在步骤 6 中看到警告消息，请执行以下操作：
+
.. 检查是否存在任何可能指示 NVRAM 电池电量低以外问题的控制台消息，如有必要，请采取任何必要的更正措施。
.. 让电池充电并完成启动过程。
+

WARNING: *不要覆盖延迟。如果电池无法充电，可能会导致数据丢失。*



. [[man_install4_Step8]]在维护模式提示符下，输入以下命令：
+
`halt`

+
系统将在启动环境提示符处停止。

. 为 ONTAP 配置 node4 ：
+
`set-defaults`


