= 在节点 4 上配置 FC 端口
:allow-uri-read: 




== 在节点 4 上配置 FC 端口

如果 node4 具有板载或 FC 适配器上的 FC 端口，则必须先在节点上设置端口配置，然后再将其投入使用，因为这些端口未经过预配置。如果未配置端口，则可能会发生服务中断。

.开始之前
您必须具有在部分中保存的 node2 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 适配器，则可以在中对其进行配置 <<检查并配置 node4 上的 UTA/UTA2 端口>>。


IMPORTANT: 在集群提示符下输入本节中的命令。

.步骤
. 显示系统上所有 FC 和融合网络适配器的信息：
+
`ssystem node hardware unified-connect show`

. 将新节点上的 FC 设置与先前从原始节点捕获的设置进行比较。
. 根据需要修改 node4 上的 FC 端口：
+
** 要对目标端口进行编程：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** 要对启动程序端口进行编程：
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
` 类型` 是 FC4 类型，目标或启动程序。



. 通过输入以下命令并检查输出来验证新设置：
+
`system node unified-connect show`

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 新节点上的默认 FC 设置 | 然后选择… 


| 与在原始节点上捕获的相同 | 前往<<man_config_4_Step9,第 9 步>>。 


| 与您在原始节点上捕获的不同 | 前往<<man_config_4_Step6,Step6>>。 
|===
. [[man_config_4_Step6]]退出维护模式：
+
`halt`

. 输入命令后，请等待，直到系统停留在启动环境提示符处。
. 在启动环境提示符下输入以下命令来启动 node4：
+
`boot_ontap`

. [[man_config_4_Step9]]执行以下操作之一：
+
** 转至 <<检查并配置 node4 上的 UTA/UTA2 端口>> 如果 node4 具有 UTA/UTA2 卡或 UTA/UTA2 板载端口。
** 跳过此部分，然后转到 link:map_ports_node2_node4.html["将端口从 node2 映射到 node4"] 如果 node4 没有 UTA/UTA2 卡或 UTA/UTA2 板载端口。



