= 
:allow-uri-read: 


. 【 man_lif_verif_3_step6]] 通过输入以下命令将每个 NAS 数据 LIF 迁移到 node3 ，每个 LIF 一次：
+
`network interface migrate -vserver _vserver_name_-lif _LIF_name_-destination-node _node3_-destination-port _netport_ifgrp_`

. 【 man_lif_verif_3_step7]] 确保数据迁移持久：
+
`network interface modify -vserver _vserver_name_-lif _LIF_name_-home-port _netport_ifgrp_-home-node _node3_`

. 【 man_lif_verif_3_step8]] 确认 SAN LIF 位于 node3 上的正确端口上：
+
.. 输入以下命令并检查其输出：
+
`network interface show -data-protocol iscsi_FCP -home-node _node3_`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. 通过将 `fcp adapter show` 命令的输出与您在工作表中记录的配置信息进行比较，验证新的和 `adapter` 和 `switch-port` 配置是否正确 <<worksheet_step2,第 2 步>>。
+
列出 node3 上的新 SAN LIF 配置：

+
`fcp adapter show -fields switch-port ， fc-wwpn`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node        adapter fc-wwpn                 switch-port
----------- ------- ----------------------- -------------
cluster1-01 0a      50:0a:09:82:9c:13:38:00 ACME Switch:0
cluster1-01 0b      50:0a:09:82:9c:13:38:01 ACME Switch:1
cluster1-01 0c      50:0a:09:82:9c:13:38:02 ACME Switch:2
cluster1-01 0d      50:0a:09:82:9c:13:38:03 ACME Switch:3
cluster1-01 0e      50:0a:09:82:9c:13:38:04 ACME Switch:4
cluster1-01 0f      50:0a:09:82:9c:13:38:05 ACME Switch:5
cluster1-01 1a      50:0a:09:82:9c:13:38:06 ACME Switch:6
cluster1-01 1b      50:0a:09:82:9c:13:38:07 ACME Switch:7
cluster1-02 0a      50:0a:09:82:9c:6c:36:00 ACME Switch:0
cluster1-02 0b      50:0a:09:82:9c:6c:36:01 ACME Switch:1
cluster1-02 0c      50:0a:09:82:9c:6c:36:02 ACME Switch:2
cluster1-02 0d      50:0a:09:82:9c:6c:36:03 ACME Switch:3
cluster1-02 0e      50:0a:09:82:9c:6c:36:04 ACME Switch:4
cluster1-02 0f      50:0a:09:82:9c:6c:36:05 ACME Switch:5
cluster1-02 1a      50:0a:09:82:9c:6c:36:06 ACME Switch:6
cluster1-02 1b      50:0a:09:82:9c:6c:36:07 ACME Switch:7
16 entries were displayed
----
+

NOTE: 如果新配置中的 SAN LIF 不在仍连接到同一个 `s交换机端口` 发生原因 的适配器上，则在重新启动节点时，它可能会导致系统中断。

.. 如果 node3 中的任何 SAN LIF 或 SAN LIF 组位于 node1 上不存在的端口上，或者需要映射到其他端口，请通过完成以下子步骤将其移动到 node3 上的相应端口：
+
... 将 LIF 状态设置为 "down" ：
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin down`

... 从端口集中删除 LIF ：
+
`portset remove -vserver _vserver_name_-portset _portset_name_-port-name _port_name_`

... 输入以下命令之一：
+
**** 移动单个 LIF ：
+
`network interface modify -vserver _vserver_name_-lif _LIF_name_-home-port _new_home_port_`

**** 将一个不存在或不正确的端口上的所有 LIF 移动到新端口：
+
`network interface modify｛-home-port _port_on_node1_-home-node _node1_-role data｝-home-port _new_home_port_on_node3_`

**** 将 LIF 重新添加到端口集：
+
`portset add -vserver _vserver_name_-portset _portset_name_-port-name _port_name_`

+

NOTE: 您必须将 SAN LIF 移动到与原始端口具有相同链路速度的端口。







. 将所有 LIF 的状态修改为 "up" ，以便 LIF 可以在节点上接受和发送流量：
+
`network interface modify -home-port _port_name_-home-node _node3_-lif data -status-admin up`

. 在任一节点上输入以下命令并检查其输出，以验证 LIF 是否已移至正确的端口，以及 LIF 的状态是否为 "up" ，具体方法是在任一节点上输入以下命令并检查输出：
+
`network interface show -home-node _node3_-role data`

. [[man_lif_verif_3_step11]] 如果任何 LIF 已关闭，请通过为每个 LIF 输入以下命令将 LIF 的管理状态设置为 "up" ：
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin up`

. 向 NetApp 发送 node1 的升级后 AutoSupport 消息：
+
`ssystem node AutoSupport invoke -node _node3_-type all -message "node1 successfully up级 从_platform_old_升级到_platform_new_"`


