---
sidebar: sidebar 
permalink: upgrade-arl-manual/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: 使用手动 ARL 升级操作步骤 升级运行 ONTAP 9.7 或更早版本的控制器硬件，从而重新定位非根聚合的所有权。 
---
= 了解 ARL 升级程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
此过程介绍如何在运行 ONTAP 9.7 或更早版本的系统上使用手动聚合重定位 (ARL) 升级控制器硬件。

如果您正在执行以下升级之一，则可以使用此 ARL 程序：

* FAS 系统到 FAS 系统
* AFF 系统到 AFF 系统


在操作步骤期间，您可以使用替代控制器硬件升级原始控制器硬件，从而重新定位非根聚合的所有权。您可以在节点之间多次迁移聚合，以确认在整个升级操作步骤 中至少有一个节点正在从聚合提供数据。您还可以迁移数据逻辑接口（ LIF ），并在继续操作时将新控制器上的网络端口分配给接口组。


NOTE: 在本文档中，原有节点称为_node1_和_node2_，新节点称为_node3_和_node4_。在所述过程中，节点 1 被节点 3 替换，节点 2 被节点 4 替换。术语 _node1_、_node2_、_node3_ 和 _node4_ 仅用于区分原始节点和新节点。按照该过程操作时，您必须替换原始节点和新节点的真实名称。但实际上，节点的名称并没有改变：在控制器硬件升级后，node3 的名称为 node1，node4 的名称为 node2。

.重要信息：
* 此操作步骤非常复杂，假定您具备高级 ONTAP 管理技能。您还必须阅读并理解link:guidelines_upgrade_with_arl.html["使用 ARL 升级控制器的指南"]和link:arl_upgrade_workflow.html["ARL 升级工作流"]在开始升级之前。
* 此操作步骤假定更换用的控制器硬件是新的，尚未使用。使用 `wipeconfig` 命令准备已用控制器所需的步骤不在此操作步骤中。如果先前使用的是替代控制器硬件，则必须联系技术支持，尤其是在控制器以 7- 模式运行 Data ONTAP 时。
* 您可以使用此操作步骤升级具有两个以上节点的集群中的控制器硬件；但是，您需要为集群中的每个高可用性（ HA ）对单独执行操作步骤。


* 此操作步骤适用场景 MetroCluster 四节点和八节点配置运行 ONTAP 9.5 及更早版本。对于运行 ONTAP 9.6 及更高版本的 MetroCluster 配置，请转至 link:other_references.html["参考资料"] 链接到_使用system controller Replace命令将运行ONTAP 9.5的控制器硬件升级到ONTAP 9.7_。

