---
sidebar: sidebar 
permalink: upgrade-arl-manual/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: 在运行 ONTAP 9.7 或更早版本的控制器上手动进行 ARL 升级期间，验证 node1 上的物理端口是否正确映射到 node3 。 
---
= 将端口从 node1 映射到 node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必须确保 node1 上的物理端口正确映射到 node3 上的物理端口，从而使 node3 能够在升级后与集群中的其他节点以及网络进行通信。

.开始之前
您必须已从 _Node_ 获得有关新节点上端口的信息 Hardware Universe 。转至 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe ）。您可以使用本节后面和中的信息 link:map_ports_node2_node4.html["将端口从 node2 映射到 node4"]。

node3的软件配置必须与node3的物理连接匹配、并且必须先还原网络连接、然后才能继续升级。

.关于此任务
端口设置可能因节点型号而异。

您必须使原始节点的端口和 LIF 配置与新节点的配置计划兼容。这是因为新节点在启动时会重放相同的配置，这意味着在启动 node3 时， ONTAP 将尝试在 node1 上使用的相同端口上托管 LIF 。

因此，如果 node1 上的物理端口不直接映射到 node3 上的物理端口，则需要更改软件配置，才能在启动后还原集群，管理和网络连接。此外，如果 node1 上的集群端口未直接映射到 node3 上的集群端口，则在重新启动时， node3 可能无法自动重新加入仲裁，直到对软件配置进行更改，以便将集群 LIF 托管在正确的物理端口上为止。

.步骤
. 【第 1 步】将 node1 ，端口，广播域和 IP 空间的所有 node1 布线信息记录在下表中：
+
[cols=""35"]
|===
| LIF | Node1 端口 | 节点 1 IP 空间 | Node1 广播域 | Node3 端口 | Node3 端口 | node3 广播域 


| 集群 1 |  |  |  |  |  |  


| 集群 2. |  |  |  |  |  |  


| 集群 3. |  |  |  |  |  |  


| 集群 4. |  |  |  |  |  |  


| 集群 5 |  |  |  |  |  |  


| 集群 6 |  |  |  |  |  |  


| 节点管理 |  |  |  |  |  |  


| 集群管理 |  |  |  |  |  |  


| 数据 1. |  |  |  |  |  |  


| 数据 2. |  |  |  |  |  |  


| 数据 3. |  |  |  |  |  |  


| 数据 4. |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| 集群间端口 |  |  |  |  |  |  
|===
+
请参见 link:record_node1_information.html["记录 node1 信息"] 获取此信息的步骤。

. 【第 2 步】使用中的相同操作步骤在上表中记录节点 3 ，端口，广播域和 IP 空间的所有布线信息 link:record_node1_information.html["记录 node1 信息"]。
. 【第 3 步】按照以下步骤验证设置是否为双节点无交换机集群：
+
.. 将权限级别设置为高级：
+
`cluster ：：： > set -privilege advanced`

.. 验证设置是否为双节点无交换机集群：
+
`network options switchless-cluster show`

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
此命令的值必须与系统的物理状态匹配。

.. 返回到管理权限级别：
+
[listing]
----
 cluster::*> set -privilege admin
 cluster::>
----


. 通过执行以下步骤，使 node3 进入仲裁状态：
+
.. 启动节点 3.请参见 link:install_boot_node3.html["安装并启动 node3"] 以启动节点（如果尚未启动）。
.. 验证新集群端口是否位于集群广播域中：
+
`network port show -node _node-name_-port _port-name_-fields broadcast-domain`

+
以下示例显示端口 "e0a" 位于 node3 上的 "Cluster" 域中：

+
[listing]
----
 cluster::> network port show -node node3 -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e1a  Cluster
----
.. 将正确的端口添加到集群广播域：
+
`network port modify -node _node-name_-port _port-name_-ipspace Cluster -MTU 9000`

+
此示例将在 node3 上添加集群端口 "e1b" ：

+
[listing]
----
 network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
+

NOTE: 对于 MetroCluster 配置，您可能无法更改某个端口的广播域，因为该端口与托管 sync-destination SVM 的 LIF 的端口相关联，并会看到类似于但不限于以下消息的错误` ：

+
[listing]
----
command failed: This operation is not permitted on a Vserver that is configured as the destination of a MetroCluster Vserver relationship.
----
+
在远程站点上对应的 sync-source SVM 中输入以下命令，将 sync-destination LIF 重新分配到相应的端口：

+
`MetroCluster SVM resync -vserver _vserver-name_`

.. 将每个 LIF 的集群 LIF 迁移到新端口一次：
+
`network interface migrate -vserver cluster -lif _LIF-name_-source-node _node3_-destination-node _node3_-destination-port _port-name_`

.. 修改集群 LIF 的主端口：
+
`network interface modify -vserver cluster -lif _LIF-name_–home-port _port-name_`

.. 如果集群端口不在集群广播域中，请添加它们：
+
`network port broadcast-domain add-ports -ipspace cluster -broadcast-domain cluster -ports _node：port_`

.. 从集群广播域中删除旧端口：
+
`network port broadcast-domain remove-ports`

+
以下示例将删除 node3 上的端口 "e0d" ：

+
[listing]
----
network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports <node3:e0d>
----
.. 验证 node3 是否已重新加入仲裁：
+
`cluster show -node _node3_-fields health`



. [[man_map_1_step5]] 调整托管集群 LIF 以及节点管理和 / 或集群管理 LIF 的广播域。确认每个广播域包含正确的端口。如果某个端口托管 LIF 或位于 LIF 的主目录中，则无法在广播域之间移动该端口，因此您可能需要按如下所示迁移和修改 LIF ：
+
.. 显示 LIF 的主端口：
+
`network interface show -fields _home-node、home-port_`

.. 显示包含此端口的广播域：
+
`network port broadcast-domain show -ports _node_name：port_name_`

.. 在广播域中添加或删除端口：
+
`网络端口 broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. 修改 LIF 的主端口：
+
`network interface modify -vserver _vserver-name_-lif _LIF-name_–home-port _port-name_`



. 【 man_map_1_step6]] 调整集群间广播域，并根据需要使用中所示的相同命令迁移集群间 LIF <<man_map_1_step5,第 5 步>>。
. 【第 7 步】调整任何其他广播域，并在必要时使用中所示的相同命令迁移数据 LIF <<man_map_1_step5,第 5 步>>。
. 【第 8 步】如果 node1 上有任何端口不再位于 node3 上，请按照以下步骤将其删除：
+
.. 访问任一节点上的高级权限级别：
+
`set -privilege advanced`

.. 删除端口：
+
`network port delete -node _node-name_-port _port-name_`

.. 返回到管理员级别：
+
`set -privilege admin`



. 【第 9 步】调整所有 LIF 故障转移组：
+
`network interface modify -failover-group _failover-group_-failover-policy _failover-policy_`

+
以下示例将故障转移策略设置为 " 广播域范围 " ，并使用故障转移组 "fg1" 中的端口作为 "node3" 上 LIF"data1" 的故障转移目标：

+
[listing]
----
network interface modify -vserver node3 -lif data1 failover-policy broadcast-domainwide -failover-group fg1
----
+
转至 link:other_references.html["参考资料"] 要链接到 _Network Management_ 或 _ONTAP 9 命令：手册页参考 _ 以了解详细信息。

. 验证 node3 上的更改：
+
`network port show -node node3`

. 每个集群 LIF 都必须侦听端口 7700 。验证集群 LIF 是否正在侦听端口 7700 ：
+
` ：：： > 网络连接侦听 show -vserver Cluster`

+
对于双节点集群，端口 7700 侦听集群端口是预期结果，如以下示例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 对于未侦听端口700的每个集群LIF、将LIF的管理状态设置为 `down` 然后 `up`：
+
`：：> net int modify -vserver cluster -lif _cluster-lif_-status-admin down；net int modify -vserver cluster -lif _cluster-lif_-status-admin up`

+
重复步骤 11 以验证集群 LIF 是否正在侦听端口 7700 。


