---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node1_node2.html 
keywords: node1, node3, nas, lifs, cluster, san 
summary: 在运行 ONTAP 9.7 或更早版本的控制器上手动升级 ARL 期间，如果您使用的是双节点集群，请将 node1 的 NAS 数据 LIF 移动到 node2 ；如果您的集群具有两个以上的节点，则移动到第三个节点。 
---
= 将 node1 拥有的 NAS 数据 LIF 移动到 node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在将 node1 替换为 node3 之前，如果您使用的是双节点集群，则必须将 node1 拥有的 NAS 数据 LIF 移动到 node2 ；如果您的集群具有两个以上的节点，则必须将此数据 LIF 移动到第三个节点。您使用的方法取决于集群是为 NAS 配置还是为 SAN 配置的。

在升级操作步骤期间，远程 LIF 处理 SAN LUN 的流量。升级期间，集群或服务运行状况无需移动 SAN LIF 。使 node3 联机后，您必须验证 LIF 是否运行正常并位于相应的端口上。

.步骤
. 输入以下命令并捕获输出，列出 node1 上托管的所有 NAS 数据 LIF ：
+
`network interface show -data-protocol nfs|cifs -curr-node _node1_`

+
系统将在 node1 上显示 NAS 数据 LIF ，如以下示例所示：

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. 执行以下操作之一：
+
[cols="40,60"]
|===
| 如果 node1... | 那么 ... 


| 已配置 VLAN 的接口组 | 转至 <<man_move_lif_1_2_step3,第 3 步>>。 


| 未配置接口组或 VLAN | 跳过步骤 3 ，然后转到 <<man_move_lif_1_2_step4,第 4 步>>。 
|===
+
使用 `network port vlan show` 命令显示连接到 VLAN 的网络端口的信息，并使用 `network port ifgrp show` 命令显示有关端口接口组的信息。

. [[man_move_lif_1_2_step3]] 执行以下步骤以迁移节点 1 上接口组和 VLAN 上托管的任何 NAS 数据 LIF ：
+
.. [[man_move_lif_1_2_substepa]] 通过为每个 LIF 输入以下命令，将任何接口组上托管的 LIF 以及 node1 上的 VLAN 迁移到 node2 上能够在与接口组相同的网络上托管 LIF 的端口：
+
`network interface migrate -vserver _vserver_name_-lif _LIF_name_-destination-node _node2_–destination-port _netport_ifgrp_`

.. 在中修改 LIF 和 VLAN 的主端口和主节点 <<man_move_lif_1_2_substepa,子步骤 A>> 输入以下命令，将 LIF 设置为当前托管 LIF 的端口和节点，每个 LIF 设置为一次：
+
`network interface modify -vserver _vserver_name_-lif _LIF_name_-home-node _node2_- home-port _netport_ifgrp_`



. [[man_move_lif_1_2_step4]] 执行以下操作之一：
+
[cols="20,80"]
|===
| 如果集群配置为 ... | 那么 ... 


| NAS | 完成 <<man_move_lif_1_2_step5,第 5 步>> 到 <<man_move_lif_1_2_step8,第 8 步>>。 


| SAN | 禁用节点上的所有SAN LIF以将其关闭以进行升级：`network interface modify -vserver _vserver-name_-lif _LIF_name_-home-node _node_to_upgrade_-home-port _netport_ifgrp_-status-admin down` 
|===
. 【 man_move_lif_1_2_step5]] 通过输入以下命令将 NAS 数据 LIF 从 node1 迁移到 node2 ，每个数据 LIF 输入一次：
+
`network interface migrate -vserver _vserver-name_-lif _LIF_name_-destination-node _node2_-destination-port _data_port_`

. 【第 6 步】输入以下命令并检查其输出，通过在任一节点上输入以下命令并检查输出来验证 LIF 是否已移至正确的端口以及 LIF 的状态是否为 up ：
+
`network interface show -curr-node _node2_-data-protocol nfs|cifs`

. 【第 7 步】输入以下命令，修改已迁移 LIF 的主节点：
+
`network interface modify -vserver _vserver-name_-lif _LIF_name_-home-node _node2_-home-port _port_name_`

. [[man_move_lif_1_2_step8]] 验证 LIF 是否正在使用此端口作为其主端口或当前端口。如果端口不是主端口或当前端口，请转到 <<man_move_lif_1_2_step9,第 9 步>>：
+
`network interface show -home-node _node2_-home-port _port_name_`

+
`network interface show -curr-node _node_name_-curr-port _port_name_`

. 【 ｛ man_move_lif_1_2_step9]] 如果 LIF 使用此端口作为主端口或当前端口，请修改此 LIF 以使用其他端口：
+
`network interface migrate -vserver _vserver-name_-lif _LIF_name_-destination–node _node_name_-destination-port _port_name_`

+
`network interface modify -vserver _vserver-name_-lif _LIF_name_-home–node _node_name_-home-port _port_name_`

. 【第 10 步】如果新硬件上不存在当前托管数据 LIF 的端口，请立即将其从广播域中删除：
+
`network port broadcast-domain remove-ports -ipspace default -broadcast-domain default -ports _node：port_`

. 【第 11 步】如果任何 LIF 已关闭，请输入以下命令，将 LIF 的管理状态设置为 "up" ，每个 LIF 一次：
+
`network interface modify -vserver _vserver-name_-lif _LIF_name_-home-node _nodename_-status-admin up`

+

NOTE: 对于 MetroCluster 配置，您可能无法更改端口的广播域，因为它与托管目标 Storage Virtual Machine （ SVM ） LIF 的端口相关联。从远程站点上对应的源SVM输入以下命令、将目标LIF重新分配到相应的端口：`MetroCluster vserver resync -vserver _vserver_name_`

. 【第 12 步】输入以下命令并检查其输出，以验证 node1 上是否没有剩余数据 LIF ：
+
`network interface show -curr-node _node1_-role data`

. 【第 13 步】如果配置了接口组或 VLAN ，请完成以下子步骤：
+
.. 输入以下命令，从接口组中删除 VLAN ：
+
`network port vlan delete -node _nodename_-port _ifgrp_name_-vlan-id _vlan_ID_`

.. 输入以下命令并检查其输出，以查看节点上是否配置了任何接口组：
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
系统将显示节点的接口组信息，如以下示例所示：

+
[listing]
----
  cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                   Node: node1
   Interface Group Name: a0a
  Distribution Function: ip
          Create Policy: multimode_lacp
            MAC Address: 02:a0:98:17:dc:d4
     Port Participation: partial
          Network Ports: e2c, e2d
               Up Ports: e2c
             Down Ports: e2d
----
.. 如果节点上配置了任何接口组，请记录这些组的名称以及分配给它们的端口，然后输入以下命令删除这些端口，每个端口输入一次：
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




