---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: '使用 `ssystem controller replace` 命令确定是否使用 ARL 升级运行 ONTAP 9.8 或更高版本的控制器。' 
---
= 决定是否使用此聚合迁移程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升级控制器硬件有多种聚合重定位 (ARL) 方法。此过程介绍如何在运行 ONTAP 9.8 或更高版本的系统上使用“系统控制器替换命令”通过聚合重定位 (ARL) 升级控制器硬件。只有经验丰富的 ONTAP 管理员才应使用此复杂过程。

为了帮助您确定此 ARL 程序是否适合您的控制器硬件升级，您应该检查以下所有情况以了解支持的升级：

* 您运行的是ONTAP 9.8或更高版本。
* 您不希望将新控制器作为新的HA对添加到集群中、也不希望通过卷移动来迁移数据。
* 您在管理ONTAP方面经验丰富、并且可以承受在诊断权限模式下工作的风险。
* 如果要升级MetroCluster配置、则该配置为四节点或更高FC配置、并且所有节点都运行ONTAP 9.8或更高版本。
+
有关升级MetroCluster IP配置的信息、请参阅link:other_references.html["参考资料"]链接至_ MetroCluster升级和扩展_。



[NOTE]
====
* 如果您通过在同一机箱中交换控制器模块（例如AFF A800或AFF C800）来升级系统， NetApp强烈建议使用升级程序link:../upgrade-arl-auto-in-chassis/index.html["使用 ARL 升级控制器模型，保留现有的系统机箱和磁盘"]。此 ARL 过程包括在升级过程中移除和安装控制器时确保内部磁盘在机箱中保持安全的步骤。
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["了解使用 ARL 支持的系统升级组合，保留现有系统机箱和磁盘"]。

* 您可以对此操作步骤 使用NetApp存储加密(NSE)、NetApp卷加密(NVE)和NetApp聚合加密(NAE)。


====


== 支持的系统升级组合

下表显示了使用此 ARL 程序执行控制器升级所支持的系统矩阵。

|===
| 旧控制器 | 更换控制器 


| FAS8020^3^、FAS8040^3^、FAS8060、FAS8080 | FAS8200 ， FAS8300 ， FAS8700 ， FAS9000 


| FAS8060^4^、FAS8080^4^ | FAS9500 


| AFF8020^3^、AFF8040^3^、AFF8060、AFF8080 | AFF A300 ， AFF A400 ， AFF A700 ， AFF A800^1^ 


| AFF8060^4^、AFF8080^4^ | AFF A900 


| FAS8200 | FAS8300^2^、FAS8700、FAS9000、FAS9500 


| FAS8300、FAS8700、FAS9000 | FAS9500 


| AFF A300 | AFF A400^2^、AFF A700、AFF A800^1^、AFF A900 


| AFF A320^4^ | AFF A400 


| AFF A400 ， AFF A700 | AFF A900 
|===

NOTE: 如果您的控制器升级型号组合不在上表中、请联系技术支持。

^1^有关AFF A800系统所需的其他步骤，请转至第节link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["将node1磁盘重新分配给node3、步骤9"]或中引用A800的步骤link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["将node2磁盘重新分配给node4、步骤9"]。

^2^如果要在双节点无交换机集群配置中从AFF A300升级到AFF A400或从FAS8200升级到FAS8300系统、则必须选择临时集群端口来进行控制器升级。AFF A400 和 FAS8300 系统采用两种配置：一种是以太网捆绑包，夹层卡端口为以太网类型；另一种是 FC 捆绑包，夹层端口为 FC 类型。

* 对于采用以太网类型配置的 AFF A400 或 FAS8300 ，您可以使用两个夹层端口中的任何一个作为临时集群端口。
* 对于采用 FC 类型配置的 AFF A400 或 FAS8300 ，您必须添加一个四端口 10GbE 网络接口卡（部件号 X1147A ）以提供临时集群端口。
* 使用临时集群端口完成控制器升级后，您可以无中断地将集群 LIF 迁移到 AFF A400 系统上的 E3a 和 e3b 100GbE 端口以及 FAS8300 系统上的 e0c 和 e0d 100GbE 端口。


^3^对于FAS8020、FAS8040、AFF8020和AFF8040系统升级到上表中列出的目标替代控制器、更换控制器必须与旧控制器运行相同的ONTAP 版本。请注意、FAS8020、FAS8040、AFF8020和AFF8040系统不支持ONTAP 9.8之后的ONTAP 版本。

^4^下表显示了这些控制器升级组合支持的最低及更高版本ONTAP。

[cols="20,30,20,30"]
|===
2+| 旧控制器 2+| 更换控制器 


| 系统 | ONTAP 版本 | 系统 | ONTAP 版本 


| AFF A320 | 9.9.1或更高版本 | AFF A400 | 9.9.1或更高版本 


| AFF8060 | 9.8P13或更高版本的修补程序 | AFF A900 | 9.10.1到9.12.1. 


| AFF8080 | 9.8P10或更高版本的修补程序 | AFF A900 | 9.10.1到9.12.1. 


| FAS8060 | 9.8P13或更高版本的修补程序 | FAS9500 | 9.10.1P3到9.12.1 


| FAS8080 | 9.8P12或更高版本的修补程序 | FAS9500 | 9.10.1P3到9.12.1 
|===
[NOTE]
====
对于上表所示的升级组合：

* 不要求在现有控制器和替代控制器上使用相同的ONTAP版本。ONTAP 软件升级是通过控制器升级来执行的。
* 升级时、您必须安装具有受支持的ONTAP 版本和修补程序级别的替代控制器。
* 在您启动控制器升级过程并升级第一个节点后、无法取消或退出此过程。


====


== 选择不同的硬件升级程序

* link:../upgrade-arl/index.html["查看可用于升级控制器硬件的替代 ARL 方法"](英文)
* 如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。


.相关信息
参考link:other_references.html["参考资料"]链接到_ONTAP 9 文档_。
