---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: '使用 `ssystem controller replace` 命令确定是否使用 ARL 升级运行 ONTAP 9.8 或更高版本的控制器。' 
---
= 确定是否使用聚合重新定位操作步骤
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此内容介绍如何使用新控制器升级 HA 对中的存储控制器，同时保留所有现有数据和磁盘。这是一个复杂的操作步骤，只能由经验丰富的管理员使用。

您可以在以下情况下使用此内容：

* 您运行的是 ONTAP 9.8 或更高版本。
* 您不希望将新控制器作为新的 HA 对添加到集群中，并使用卷移动来迁移数据。
* 您拥有管理 ONTAP 的经验，并对在诊断权限模式下工作的风险感到满意。
* 如果要升级 MetroCluster 配置，则此配置为四节点或更高版本的 FC 配置，并且所有节点均运行 ONTAP 9.8 或更高版本。
+
有关升级 MetroCluster IP 配置的信息，请参见 link:other_references.html["参考资料"] 链接到 _RAID MetroCluster 升级和扩展 _ 内容。




NOTE: 您可以对此操作步骤使用 NetApp 存储加密（ NSE ）和 NetApp 卷加密（ NVE ）。

下表显示了控制器升级支持的型号列表。

|===
| 旧控制器 | 更换控制器 


| FAS8020 ， FAS8040 ， FAS8060 ， FAS8080 | FAS8200 ， FAS8300 ， FAS8700 ， FAS9000 


| AFF8020 ， AFF8040 ， AFF8060 ， AFF8080 | AFF A300 ， AFF A400 ， AFF A700 ， AFF A800^1^ 


| FAS8200 | FAS8700 ， FAS9000 ， FAS8300^3^ 


| AFF A300 | AFF A700 ， AFF A800^1^ ， AFF A400^3^ 


| AFF A320 | AFF A400^2^ 
|===

NOTE: 如果上表不包含您的控制器升级型号组合，请联系技术支持。

^1^有关 AFF A800 系统所需的其他步骤，请转至第节中引用 A800 的步骤 link:set_fc_or_uta_uta2_config_on_node3.html#step23["检查并配置 node3 上的 UTA/UTA2 端口，步骤 23"]或 link:set_fc_or_uta_uta2_config_node4.html#step23["检查并配置 node4 上的 UTA/UTA2 端口，步骤 23"]。

^2^从 ONTAP 9.1.1 开始，支持 ARL 自动从 AFF A320 升级到 AFF A400 系统。

^3^如果要在双节点无交换机集群配置中从 AFF A300 升级到 AFF A400 或 FAS8200 到 FAS8300 系统，则必须选择临时集群端口进行控制器升级。AFF A400 和 FAS8300 系统采用两种配置：一种是以太网捆绑包，夹层卡端口为以太网类型；另一种是 FC 捆绑包，夹层端口为 FC 类型。

* 对于采用以太网类型配置的 AFF A400 或 FAS8300 ，您可以使用两个夹层端口中的任何一个作为临时集群端口。
* 对于采用 FC 类型配置的 AFF A400 或 FAS8300 ，您必须添加一个四端口 10GbE 网络接口卡（部件号 X1147A ）以提供临时集群端口。
* 使用临时集群端口完成控制器升级后，您可以无中断地将集群 LIF 迁移到 AFF A400 系统上的 E3a 和 e3b 100GbE 端口以及 FAS8300 系统上的 e0c 和 e0d 100GbE 端口。


如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。

请参见 link:other_references.html["参考资料"] 可链接到 _ONTAP 9 文档中心 _ ，在此可以访问 ONTAP 9 产品文档。
