---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/ensure_new_controllers_are_set_up_correctly.html 
keywords: confirm, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability 
summary: '使用 `ssystem controller replace` 命令升级运行 ONTAP 9.8 或更高版本的控制器后，启用 HA 对，验证 node3 和 node4 存储访问并确认聚合所有权。' 
---
= 确认新控制器设置正确
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要确认设置正确，必须启用 HA 对。此外，还必须验证 node3 和 node4 是否可以访问彼此的存储，并且它们都不拥有属于集群上其他节点的数据 LIF 。此外，您还必须确认 node3 拥有 node1 的聚合， node4 拥有 node2 的聚合，并且两个节点的卷均联机。

.步骤
. 在对 node2 执行后检之后，将为 node2 集群启用存储故障转移和集群 HA 对。操作完成后，两个节点均显示为已完成，系统将执行一些清理操作。
. 验证是否已启用存储故障转移：
+
`s存储故障转移显示`

+
以下示例显示了启用存储故障转移时命令的输出：

+
....
cluster::> storage failover show
                  Takeover
Node     Partner  Possible   State Description
-------- -----    -------    ------------------
node3    node4    true       Connected to node4
node4    node3    true       Connected to node3
....
. 使用以下命令并检查输出，验证 node3 和 node4 是否属于同一集群：
+
`cluster show`

. 使用以下命令并检查输出，验证 node3 和 node4 是否可以访问彼此的存储：
+
`storage failover show -fields local-missing-disks、partner-missing-disks`

. 使用以下命令并检查输出，验证 node3 和 node4 均不拥有集群中其他节点拥有的主数据 LIF ：
+
`network interface show`

+
如果 node3 或 node4 都不拥有集群中其他节点拥有的主数据 LIF ，请将数据 LIF 还原到其主所有者：

+
`网络接口还原`

. 确认 node3 拥有 node1 中的聚合，而 node4 拥有 node2 中的聚合：
+
`storage aggregate show -owner-name <node3>`

+
`storage aggregate show -owner-name <node4>`

. 确定是否有任何卷脱机：
+
`volume show -node <node3> -state offline`

+
`volume show -node <node4> -state offline`

. 如果任何卷处于脱机状态，请将其与您在部分中捕获的脱机卷列表进行比较 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]，并根据需要使用以下命令使每个卷的任何脱机卷联机一次：
+
`volume online -vserver <vserver_name> -volume <volume_name>`

. 对每个节点使用以下命令，为新节点安装新许可证：
+
`system license add -license-code <license_code,license_code,license_code…>`

+
license-code 参数接受一个包含 28 个大写字母字符密钥的列表。您可以一次添加一个许可证，也可以一次添加多个许可证，并以逗号分隔每个许可证密钥。

. 使用以下命令之一从原始节点中删除所有旧许可证：
+
`ssystem license clean-up -unused -expired`

+
`system license delete -serial-number <node_serial_number> -package <licensable_package>`

+
--
** 删除所有已过期的许可证：
+
`ssystem license clean-up -expired`

** 删除所有未使用的许可证：
+
`ssystem license clean-up -unused`

** 在节点上使用以下命令从集群中删除特定许可证：
+
`system license delete -serial-number <node1_serial_number> -package *`

+
`system license delete -serial-number <node2_serial_number> -package *`



--
+
此时将显示以下输出：

+
....
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
....
+
输入 `y` 删除所有软件包。

. 使用以下命令并检查输出，以验证是否已正确安装许可证：
+
`s系统许可证显示`

+
您可以将输出与在部分中捕获的输出进行比较 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

. 【unset_maxWait_system_commands】如果正在配置中使用自加密驱动器、并且您已设置 `kmip.init.maxwait` 变量设置为 `off` (例如、在中 link:install_boot_node4.html#auto_install4_step27["安装并启动 node4 步骤 27"])、您必须取消设置变量：
+
`set diag；systemshell -node _node_name_-command sudo kenv -u -p kmip.init.maxwait`



. 在两个节点上使用以下命令配置 SP ：
+
`ssystem service-processor network modify -node _node_name_`

+
请参见 link:other_references.html["参考资料"] 链接到 ONTAP `s管理参考 _ 以了解 SP 的相关信息，以及 _SP 9.8 命令：手册页参考 _ 以了解有关 system` service-processor network modify 命令的详细信息。

. 如果要在新节点上设置无交换机集群，请参见 link:other_references.html["参考资料"] 要链接到 _NetApp 支持站点 _ 并按照 _switchover to a two-node switchless cluster_ 中的说明进行操作。


.完成后
如果在 node3 和 node4 上启用了存储加密，请完成此部分 link:set_up_storage_encryption_new_module.html["在新控制器模块上设置存储加密"]。否则，请完成部分 link:decommission_old_system.html["停用旧系统"]。
