---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: '了解是否可以使用 `ssystem controller replace` 命令升级运行 ONTAP 9.8 或更高版本的控制器。' 
---
= 使用 ARL 升级控制器的准则
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要了解是否可以使用 ARL 升级一对运行 ONTAP 9.8 或更高版本的控制器，取决于原始控制器和替代控制器的平台和配置。



== 支持 ARL 升级

在使用适用于 ONTAP 9.8 或更高版本的 ARL 操作步骤升级一对节点时，您必须验证是否可以对原始控制器和替代控制器执行 ARL 。

您必须检查所有已定义聚合的大小以及原始系统支持的磁盘数。然后，您必须将支持的聚合大小和磁盘数量与新系统支持的聚合大小和磁盘数量进行比较。请参见 link:other_references.html["参考资料"] 链接到可 Hardware Universe 提供此信息的 _SIL_ 。新系统支持的聚合大小和磁盘数必须等于或大于原始系统支持的聚合大小和磁盘数。

您必须在集群混用规则中验证在更换原始控制器后，新节点是否可以加入现有节点的集群。有关集群混合规则的详细信息，请参见 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe 。


NOTE: 如果要升级的系统支持内部驱动器（例如 FAS2700 或 AFF A250 ），但没有内部驱动器，请参见 link:other_references.html["参考资料"] 并使用 _aggregate relocation 中的操作步骤手动升级适用于您的 ONTAP 版本的控制器 Hardware_ 内容。

如果您的系统每个节点具有两个以上的集群端口，例如 FAS8080 或 AFF8080 系统，则在开始升级之前，您必须将集群 LIF 迁移并重新设置为每个节点的两个集群端口。如果在每个节点上执行控制器升级时使用两个以上的集群端口，则在升级后，新控制器上可能会缺少集群 LIF 。

配置了 SnapLock 企业版和 SnapLock 合规性卷的系统支持使用 ARL 升级控制器。



== 双节点无交换机集群

如果要升级双节点无交换机集群中的节点，则可以在执行升级时将这些节点保留在无交换机集群中。您无需将其转换为交换集群。



== ARL 不支持升级

您不能执行以下升级：

* 更换不支持与原始控制器相连的磁盘架的控制器
+
请参见 link:other_references.html["参考资料"] 链接到 _disk_ Hardware Universe 以获取磁盘支持信息。

* 具有内部驱动器的入门级控制器，例如： FAS 2500 。
+
如果要使用内部驱动器升级入门级控制器，请参见 link:other_references.html["参考资料"] 要链接到 _Upgrade by moving volumes or storage_ 并转到操作步骤 _upgrading a pair of nodes running candlused_by Data ONTAP moving volumes_ 。





== MetroCluster FC 配置

在MetroCluster FC配置中、您必须尽快更换灾难恢复/故障转移站点节点。不支持 MetroCluster 中的控制器型号不匹配，因为控制器型号不匹配会使发生原因灾难恢复镜像脱机。在更换第二个站点上的节点时、使用 `-skip-metrocluster-check true` 命令绕过MetroCluster检查。



== 故障排除

升级节点对时可能会遇到故障。节点可能会崩溃，聚合可能无法重新定位或 LIF 可能无法迁移。故障的发生原因及其解决方案取决于升级操作步骤期间发生故障的时间。

如果出现任何问题，请参阅link:aggregate_relocation_failures.html["故障排除"]请参阅本过程末尾的部分，了解更多信息和可能的解决方案。有关可能发生的故障的信息按过程的阶段列出在link:overview_of_the_arl_upgrade.html["ARL 升级序列"] 。

如果您未找到与遇到的问题相关的解决方案 ，请联系技术支持。
