---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: '使用 `ssystem controller replace` 命令升级运行 ONTAP 9.8 或更高版本的控制器时，安装和启动 node4 并安装 ONTAP 软件。' 
---
= 安装并启动节点 4.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必须在机架中安装 node4 ，将 node2 的连接传输到 node4 ，启动 node4 并安装 ONTAP 。然后，您必须重新分配 node2 的任何备用磁盘，属于根卷的任何磁盘以及在此过程前面未重新定位到 node3 的任何非根聚合，如本节所述。

.关于此任务
重新定位操作在此阶段开始时暂停。此过程大部分是自动完成的；此操作将暂停以使您能够检查其状态。您必须手动恢复此操作。

如果 node4 的 ONTAP 9 版本与 node2 上安装的版本不同，则需要对其进行网络启动。安装 node4 后，从 Web 服务器上存储的 ONTAP 9 映像启动它。然后，您可以按照中的说明将正确的文件下载到启动介质设备，以供后续系统启动 link:prepare_for_netboot.html["准备网络启动"]。

.重要
* 如果要升级连接到存储阵列的 V 系列系统或安装了 FlexArray 虚拟化软件并连接到存储阵列的系统，则必须完成升级 <<auto_install4_step1,第 1 步>> 到 <<auto_install4_step21,第 21 步>>，然后退出本节并按照说明进行操作 link:set_fc_or_uta_uta2_config_node4.html#configure-fc-ports-on-node4["在节点 4 上配置 FC 端口"] 和到 link:set_fc_or_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["检查并配置 node4 上的 UTA/UTA2 端口"]，在维护模式下输入命令。然后，您必须返回到此部分并继续使用 <<auto_install4_step23,第 23 步>>。
* 但是，如果要升级具有存储磁盘的系统，则必须完成整个部分，然后继续 link:set_fc_or_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"]，在集群提示符处输入命令。


.步骤
. 【 auto_install4_step1]] 确保 node4 具有足够的机架空间。
+
如果 node4 与 node2 位于不同的机箱中，则可以将 node4 与 node3 放在同一位置。如果 node2 和 node4 位于同一机箱中，则 node4 已位于其相应的机架位置。

. 按照节点型号的 _Installation and Setup Instructions_中 的说明，在机架中安装 node4 。
. 为节点 4 布线，将连接从节点 2 移至节点 4 。
+
按照 node4 平台的 _Installation and Setup Instructions_or the _FlexArray 虚拟化安装要求和参考 _ 中的说明，使用缆线连接以下连接，并参考相应的磁盘架文档和 _High Availability Management_ 。

+
请参见 link:other_references.html["参考资料"] 链接到 _High Availability Management_ 和 _FlexArray 虚拟化安装要求和参考。

+
** 控制台（远程管理端口）
** 集群端口
** 数据端口
** 集群和节点管理端口
** 存储
** SAN 配置： iSCSI 以太网和 FC 交换机端口
+

NOTE: 您可能不需要将互连卡 /FC-VI 卡或互连 /FC-VI 缆线连接从 node2 移至 node4 ，因为大多数平台型号都具有唯一的互连卡型号。对于 MetroCluster 配置，必须将 FC-VI 缆线连接从 node2 移至 node4 。如果新主机没有 FC-VI 卡，则可能需要移动 FC-VI 卡。



. 打开 node4 的电源，然后在控制台终端按 `Ctrl-C` 以访问启动环境提示符，从而中断启动过程。
+

NOTE: 启动 node4 时，您可能会看到以下警告消息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 如果您在步骤 4 中看到警告消息，请执行以下操作：
+
.. 检查是否存在任何可能指示 NVRAM 电池电量低以外问题的控制台消息，如有必要，请采取任何必要的更正措施。
.. 让电池充电并完成启动过程。
+

WARNING: * 注意：请勿覆盖延迟；如果不允许电池充电，可能会导致数据丢失。 *

+

NOTE: 请参见 link:prepare_for_netboot.html["准备网络启动"]。





. 【第 6 步】选择以下操作之一，配置网络启动连接。
+

NOTE: 您必须使用管理端口和 IP 作为网络启动连接。请勿使用数据 LIF IP ，否则在执行升级期间可能会发生数据中断。

+
[cols="30,70"]
|===
| 动态主机配置协议（ DHCP ） | 那么 ... 


| 正在运行 | 在启动环境提示符处使用以下命令自动配置连接： `ifconfig e0M -auto` 


| 未运行  a| 
在启动环境提示符处输入以下命令、以手动配置连接：
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 是存储系统的IP地址(必填)。
`_netmask_` 是存储系统的网络掩码(必需)。
`_gateway_` 是存储系统的网关(必需)。
`_dns_addr_` 是网络上名称服务器的IP地址(可选)。
`_dns_domain_` 是DNS域名(可选)。


NOTE: 您的接口可能需要其他参数。有关详细信息，请在固件提示符处输入 `help ifconfig` 。

|===
. 对 node4 执行网络启动：
+
[cols="30,70"]
|===
| 针对 ... | 那么 ... 


| FAS/AFF8000 系列系统 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| 所有其他系统 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
` <path_to_the_web-accessible_directory>` 应指向您在本节第 1 步中下载 ` <ontap_version>_image.tgz` 的位置 link:prepare_for_netboot.html["准备网络启动"]。

+

NOTE: 请勿中断启动。

. 从启动菜单中，选择选项 ` （ 7 ） Install new software first` 。
+
此菜单选项可下载新的 ONTAP 映像并将其安装到启动设备中。

+
请忽略以下消息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
注意适用场景可无中断升级 ONTAP ，而不是升级控制器。

+

NOTE: 请始终使用 netboot 将新节点更新为所需映像。如果您使用其他方法在新控制器上安装映像，则可能会安装不正确的映像。此问题描述适用场景所有 ONTAP 版本。netboot操作步骤 与选项结合使用 `(7) Install new software` 擦除启动介质并将相同的ONTAP 版本放置在两个映像分区上。

. 如果系统提示您继续运行操作步骤，请输入 `y` ，并在系统提示您输入软件包时，输入 URL ：
+
` http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. 完成以下子步骤以重新启动控制器模块：
+
.. 出现以下提示时，输入 `n` 以跳过备份恢复：
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. 出现以下提示时，输入 `y` 以重新启动：
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
控制器模块重新启动，但停留在启动菜单处，因为启动设备已重新格式化，并且必须还原配置数据。



. 从启动菜单中选择维护模式 `5` ，并在系统提示您继续启动时输入 `y` 。
. 验证控制器和机箱是否已配置为 HA ：
+
`ha-config show`

+
以下示例显示了 `ha-config show` 命令的输出：

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: 系统会在 PROM 中记录它们是采用 HA 对还是独立配置。独立系统或 HA 对中的所有组件的状态都必须相同。

. 如果控制器和机箱未配置为 HA ，请使用以下命令更正配置：
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
如果您使用的是 MetroCluster 配置，请使用以下命令修改控制器和机箱：

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. 退出维护模式：
+
`halt`

+
在启动环境提示符处按 Ctrl-C 中断自动启动。

. 在 node3 上，检查系统日期，时间和时区：
+
`dATE`

. 在 node4 上，在启动环境提示符处使用以下命令检查日期：
+
`s如何选择日期`

. 如有必要，请在 node4 上设置日期：
+
`set date _MM/dd/yyy_`

. 在 node4 上，在启动环境提示符处使用以下命令检查时间：
+
`s时间`

. 如有必要，请在 node4 上设置时间：
+
`set time _hh：mm：ss_`

. 在启动加载程序中、设置node4上的配对系统ID：
+
`setenv partner-sysid _node3_sysid_`

+
对于node4、 `partner-sysid` 必须为node3的。

+
保存设置：

+
`saveenv`

. [[auto_install4_step21]]验证 `partner-sysid` 对于node4：
+
`printenv partner-sysid`

. 【第 22 步】执行以下操作之一：
+
[cols="30,70"]
|===
| 如果您的系统 ... | 那么 ... 


| 具有磁盘，无后端存储 | 转至 <<auto_install4_step23,第 23 步>>。 


| 是 V 系列系统或已将 FlexArray 虚拟化软件连接到存储阵列的系统  a| 
.. 转至第节 link:set_fc_or_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"] 并完成本节中的各小节。
.. 返回到此部分，完成从开始的其余步骤 <<auto_install4_step23,第 23 步>>。



IMPORTANT: 在使用FlexArray 虚拟化软件的V系列或系统上启动ONTAP 之前、必须重新配置FC板载端口、CNA板载端口和CNA卡。

|===


. 【 auto_install4_step23]] 将新节点的 FC 启动程序端口添加到交换机分区。
+
如果您的系统具有磁带 SAN ，则需要对启动程序进行分区。如果需要，请参考将板载端口修改为启动程序 link:set_fc_or_uta_uta2_config_node4.html#configure-fc-ports-on-node4["在节点 4 上配置 FC 端口"]。有关分区的详细说明，请参见存储阵列和分区文档。

. 将 FC 启动程序端口作为新主机添加到存储阵列，从而将阵列 LUN 映射到新主机。
+
有关说明，请参见存储阵列和分区文档。

. 修改与存储阵列上的阵列 LUN 关联的主机或卷组中的全球通用端口名称（ WWPN ）值。
+
安装新控制器模块会更改与每个板载 FC 端口关联的 WWPN 值。

. 如果您的配置使用基于交换机的分区，请调整分区以反映新的 WWPN 值。


. 如果您安装了NetApp存储加密(NSE)驱动器、请执行以下步骤。
+

NOTE: 如果您之前尚未在操作步骤 中执行此操作、请参见知识库文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判断驱动器是否已通过FIPS认证"^] 确定正在使用的自加密驱动器的类型。

+
.. 设置 `bootarg.storageencryption.support` to `true` 或 `false`。
+
[cols="35,65"]
|===
| 如果正在使用以下驱动器、请使用… | 然后选择… 


| 符合FIPS 140-2 2级自加密要求的NSE驱动器 | `setenv bootarg.storageencryption.support *true*` 


| NetApp非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
不能在同一节点或HA对上混用FIPS驱动器和其他类型的驱动器。您可以在同一节点或HA对上混用SED和非加密驱动器。

====
.. 转到专用启动菜单并选择选项 `(10) Set Onboard Key Manager recovery secrets`。
+
输入先前记录的操作步骤 密码短语和备份信息。请参见 link:manage_storage_encryption_using_okm.html["使用板载密钥管理器管理存储加密"]。



. 启动节点进入启动菜单：
+
`boot_ontap 菜单`

+
如果您没有 FC 或 UTA/UTA2 配置，请执行 link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15["检查并配置 node4 上的 UTA/UTA2 端口，步骤 15"] 以便 node4 可以识别 node2 的磁盘。

. 【第 29 步】对于 MetroCluster 配置， V 系列系统以及将 FlexArray 虚拟化软件连接到存储阵列的系统，您必须在 node4 上设置和配置 FC 或 UTA/UTA2 端口，以检测连接到节点的磁盘。要完成此任务，请转至第节 link:set_fc_or_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/Ut2 配置"]。

