---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: '使用升级运行ONTAP 9.8或更高版本的控制器时、验证node2上的node1 NAS数据LIF是否已从node2重新定位到node3 `system controller replace` 命令' 
---
= 将 node1 拥有的非根聚合和 NAS 数据 LIF 从 node2 移动到 node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在验证 node3 上的网络配置以及将聚合从 node2 重新定位到 node3 之前，您必须验证当前位于 node2 上的 node1 所属的 NAS 数据 LIF 是否已从 node2 重新定位到 node3 。您还必须验证 node3 上是否存在 SAN LIF 。

.关于此任务
在升级操作步骤期间，远程 LIF 处理 SAN LUN 的流量。升级期间，集群或服务运行状况无需移动 SAN LIF 。除非需要将 SAN LIF 映射到新端口，否则不会移动这些 LIF 。使 node3 联机后，您将验证 LIF 是否运行正常并位于相应的端口上。


NOTE: 如果您要更改基于以下基于的以太网接口卡或主板端口的端口速度、则可能会在速度转换后看到接收到格式错误的数据包。请参见 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp错误在线中的错误ID 1570339"^] 和知识库文章 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["从40GbE转换到100GbE后、在调整端口配置为36的端口上出现CRC错误"^] 以获得指导。

.步骤
. 恢复重新定位操作：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下任务：

+
** 集群仲裁检查
** 系统 ID 检查
** 映像版本检查
** 目标平台检查
** 网络可访问性检查


+
此操作将在网络可访问性检查的此阶段暂停。

. 恢复重新定位操作：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下检查：

+
** 集群运行状况检查
** 集群 LIF 状态检查


+
执行这些检查后，系统会将 node1 拥有的非根聚合和 NAS 数据 LIF 重新定位到新控制器 node3 。资源重新定位完成后，控制器更换操作将暂停。

. 检查聚合重新定位和 NAS 数据 LIF 移动操作的状态：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更换操作步骤已暂停，请检查并更正错误（如果有），然后选择问题描述 `reume` 继续操作。

. 如有必要，恢复和还原已移位的 LIF，或者手动迁移和修改未能自动迁移到 node3 的 node1 LIF。
+
[role="tabbed-block"]
====
.恢复和还原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果已替换任何 LIF ，请将主节点还原回 node3 ：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node3_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手动迁移和修改 LIF 文件
--
.. 将未能自动迁移到节点3的LIF迁移：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node3_nodename> -destination-port <port_on_node3>
----
.. 修改已迁移 LIF 的源节点和源端口：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node3_nodename> -home-port <home_port>
----


--
====
. 恢复此操作以提示系统执行所需的后检查：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下后检查：

+
** 集群仲裁检查
** 集群运行状况检查
** 聚合重建检查
** 聚合状态检查
** 磁盘状态检查
** 集群 LIF 状态检查
** 卷检查



