---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: '使用 `ssystem controller replace` 命令升级运行 ONTAP 9.8 或更高版本的控制器时，验证 node3 上的 node2 NAS 数据 LIF 是否已从 node3 重新定位到 node4 。' 
---
= 将 node2 拥有的非根聚合和 NAS 数据 LIF 从 node3 移动到 node4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在验证节点 4 上的网络配置后，需要将节点 2 拥有的 NAS 数据 LIF 从节点 3 迁移到节点 4，并确认 SAN LIF 存在于节点 4 上。

.关于此任务
远程 LIF 在升级过程中处理到 SAN LUN 的流量。升级过程中，迁移 SAN LIF 对集群或服务运行状况并非必要。除非需要将 SAN LIF 映射到新端口，否则不会移动它们。

在节点 4 上线后，您需要验证 LIF 是否健康并位于正确的端口上。


NOTE: 如果您要更改基于以下基于的以太网接口卡或主板端口的端口速度、则可能会在速度转换后看到接收到格式错误的数据包。请参见 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp错误在线中的错误ID 1570339"^] 和知识库文章 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["从40GbE转换到100GbE后、在调整端口配置为36的端口上出现CRC错误"^] 以获得指导。

.步骤
. 恢复重新定位操作：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下任务：

+
** 集群仲裁检查
** 系统 ID 检查
** 映像版本检查
** 目标平台检查
** 网络可访问性检查


+
系统在网络可达性检查阶段暂停操作。

. 恢复重新定位操作：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下检查：

+
** 集群运行状况检查
** 集群 LIF 状态检查


+
执行这些检查后，系统会将 node2 拥有的非根聚合和 NAS 数据 LIF 重新定位到新控制器 node4 。资源重新定位完成后，控制器更换操作将暂停。

. 检查聚合重新定位和 NAS 数据 LIF 移动操作的状态：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更换操作步骤已暂停，请检查并更正错误（如果有），然后选择问题描述 `reume` 继续操作。

. 如有必要，恢复和还原已移位的 LIF，或者手动迁移和修改未能自动迁移到 node4 的 node2 LIF。
+
[role="tabbed-block"]
====
.恢复和还原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果已替换任何 LIF ，请将主节点还原回 node4 ：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手动迁移和修改 LIF 文件
--
.. 将未能自动迁移到节点 4 的 LIF 迁移：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. 修改已迁移 LIF 的源节点和源端口：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. 恢复此操作以提示系统执行所需的后检查：
+
[source, cli]
----
system controller replace resume
----
+
系统将执行以下后检查：

+
** 集群仲裁检查
** 集群运行状况检查
** 聚合重建检查
** 聚合状态检查
** 磁盘状态检查
** 集群 LIF 状态检查
** 卷检查



