---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 确定是否使用ARL操作步骤升级同一机箱中的控制器型号。 
---
= 确定是否使用聚合重新定位操作步骤
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
此内容介绍如何在保留所有现有数据和磁盘的同时升级HA对中的存储控制器。这是一个复杂的操作步骤，只能由经验丰富的管理员使用。



== 支持ARL升级

您可以在以下情况下使用此操作步骤：

* 中列出了控制器升级link:index.html#supported-systems,["支持的系统列表"]。
* 您已向NetApp销售代表确认收到升级控制器所需的硬件：
+
** 两个AFF A90、AFF A70或AFF C80控制器以及所有I/O模块。所需的100GbE缆线长度。
** 两个AFF A50、AFF A30、AFF C30或AFF C60控制器和I/O模块。所需的缆线。
** ASA A150、AFF A150或FAS2820控制器
** ASA A900、AFF A900或FAS9500控制器和NVRAM模块及部件


* 您正在运行适用于升级的最低ONTAP版本。有关详细信息，请参见 link:index.html["概述"]。
* 您不希望将新控制器作为新的 HA 对添加到集群中，并使用卷移动来迁移数据。
* 您拥有管理 ONTAP 的经验，并对在诊断权限模式下工作的风险感到满意。
* 您的系统运行的是9.15.1 9.151或更高版本、并且正在使用以太网交换机连接到以太网连接的存储。




== ARL升级不支持

在以下情况下、您不能使用此操作步骤：

* 您正在升级的现有系统上使用FlexArray虚拟化软件。
* 您正在升级MetroCluster IP配置。
+
要升级MetroCluster IP配置、请参见link:other_references.html["参考资料"]以链接到_Upgrade MetroCluster and Expanation_内容。




NOTE: 您可以对此操作步骤 使用NetApp存储加密(NSE)、NetApp卷加密(NVE)和NetApp聚合加密(NAE)。

如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。

请参见 link:other_references.html["参考资料"] 可链接到 _ONTAP 9 文档中心 _ ，在此可以访问 ONTAP 9 产品文档。
