---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability, aff, a700, a900 
summary: 确定是否使用 ARL 操作步骤 将 AFF A700 升级到 AFF A900 。 
---
= 确定是否使用聚合重新定位操作步骤
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此内容介绍如何升级AFF A700 HA对中的存储控制器以及FAS9000 HA对中的新AFF A900控制器或控制器以及新的FAS9500控制器、同时保留所有现有数据和磁盘。这是一个复杂的操作步骤，只能由经验丰富的管理员使用。

在以下情况下使用此操作步骤 ：

* 您已向NetApp销售代表确认、您已收到AFF A900或FAS9500控制器和NVRAM模块以及升级所需的部件。
* 您正在为AFF A900控制器运行ONTAP 9.10.1或更高版本。
* 您正在为FAS9500控制 器运行ONTAP 9.10.1P3或更高版本。
* 您不希望将新控制器作为新的 HA 对添加到集群中，并使用卷移动来迁移数据。
* 您拥有管理 ONTAP 的经验，并对在诊断权限模式下工作的风险感到满意。


在以下情况下，请勿 * 使用此操作步骤 ：

* 您正在AFF A700或FAS9000系统上使用FlexArray 虚拟化软件。
* 您正在使用共享交换机进行集群互连和以太网连接存储。


有关升级 Fabric MetroCluster 或 MetroCluster IP 配置的信息，请参见 link:other_references.html["参考资料"] 链接到 _RAID MetroCluster 升级和扩展 _ 内容。


NOTE: 您可以对此操作步骤使用 NetApp 存储加密（ NSE ）和 NetApp 卷加密（ NVE ）。

如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。

请参见 link:other_references.html["参考资料"] 可链接到 _ONTAP 9 文档中心 _ ，在此可以访问 ONTAP 9 产品文档。
