---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 确定是否使用ARL操作步骤升级同一机箱中的控制器型号。 
---
= 确定是否使用聚合重新定位操作步骤
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此内容介绍如何在保留所有现有数据和磁盘的同时升级HA对中的存储控制器。这是一个复杂的操作步骤，只能由经验丰富的管理员使用。

在以下情况下使用此操作步骤 ：

* 您正在执行以下控制器升级之一：
+
[cols="50,50"]
|===
| 旧控制器 | 更换控制器 


| 配置为ASA的AFF A220 | ASA A150 


| AFF A220、AFF A200或AFF C190 | AFF A150 


| FAS2620或FAS2720 | FAS2820 


| 配置为ASA的AFF A700 | ASA A900 


| AFF A700 | AFF A900 


| FAS9000 | FAS9500 
|===
* 您已向NetApp销售代表确认收到用于控制器升级的硬件：
+
** ASA A150、AFF A150或FAS2820控制器
** ASA A900、AFF A900或FAS9500控制器和NVRAM模块以及升级所需的部件


* 您正在运行适用于升级的最低ONTAP版本。有关详细信息，请参见 link:index.html["概述"]。
* 您不希望将新控制器作为新的 HA 对添加到集群中，并使用卷移动来迁移数据。
* 您拥有管理 ONTAP 的经验，并对在诊断权限模式下工作的风险感到满意。


在以下情况下，请勿 * 使用此操作步骤 ：

* 您正在AFF A700或FAS9000系统上使用FlexArray 虚拟化软件。
* 您正在使用共享交换机进行集群互连和以太网连接存储。


有关升级AFF A700或FAS9000系统上的光纤MetroCluster或MetroCluster IP配置、请参见 link:other_references.html["参考资料"] 链接到 _RAID MetroCluster 升级和扩展 _ 内容。


NOTE: 您可以对此操作步骤 使用NetApp存储加密(NSE)、NetApp卷加密(NVE)和NetApp聚合加密(NAE)。

如果您希望使用其他方法升级控制器硬件并愿意执行卷移动，请参见 link:other_references.html["参考资料"] 通过移动卷或存储链接到 _Upgrade 。

请参见 link:other_references.html["参考资料"] 可链接到 _ONTAP 9 文档中心 _ ，在此可以访问 ONTAP 9 产品文档。
