---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/ensure_new_controllers_are_set_up_correctly.html 
keywords: ensure, controllers, new, setup, ha, pair, node1, node2, lif, cluster, high, availability 
summary: 在将 AFF A700 升级到 AFF A900 后，验证是否已启用 HA 对，验证 node1 和 node2 存储访问和 LIF ，并确认聚合所有权。 
---
= 确认新控制器设置正确
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要确认设置是否正确，您必须验证是否已启用 HA 对。此外，还必须验证 node1 和 node2 是否可以访问彼此的存储，并且它们都不拥有属于集群上其他节点的数据 LIF 。此外，您还必须验证所有数据聚合是否位于其正确的主节点上，以及两个节点的卷是否联机。如果其中一个新节点具有统一目标适配器，则必须还原任何端口配置，并且可能需要更改此适配器的使用。

.步骤
. 在对 node2 执行后检之后，将为 node2 集群启用存储故障转移和集群 HA 对。操作完成后，两个节点均显示为已完成，系统将执行一些清理操作。
. 验证是否已启用存储故障转移：
+
`s存储故障转移显示`

+
以下示例显示了启用存储故障转移时命令的输出：

+
[listing]
----
cluster::> storage failover show
                                Takeover
Node	         Partner	        Possible	      State Description
-------------  --------------   --------------  ------------------
node1	         node2            true	           Connected to node2
node2	         node1            true	           Connected to node1
----
. 使用以下命令并检查输出，验证 node1 和 node2 是否属于同一集群：
+
`cluster show`

. 使用以下命令并检查输出，验证 node1 和 node2 是否可以访问彼此的存储：
+
`storage failover show -fields local-missing-disks ， partner-missing-disks`

. 使用以下命令并检查输出，验证 node1 和 node2 均不拥有集群中其他节点拥有的主数据 LIF ：
+
`network interface show`

+
如果 node1 或 node2 均不拥有集群中其他节点拥有的主数据 LIF ，请将数据 LIF 还原到其主所有者：

+
`网络接口还原`

. 验证聚合是否属于其各自的主节点。
+
`storage aggregate show -owner-name _node1_`

+
`storage aggregate show -owner-name _node2_`

. 确定是否有任何卷脱机：
+
`volume show -node _node1_-state offline`

+
`volume show -node _node2_-state offline`

. 如果任何卷处于脱机状态，请将其与您在部分中捕获的脱机卷列表进行比较 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]，并根据需要使用以下命令使每个卷的任何脱机卷联机一次：
+
`volume online -vserver _vserver_name_-volume _volume_name_`

. 对每个节点使用以下命令，为新节点安装新许可证：
+
`ssystem license add -license-code _license_code、license_code、license_code..._`

+
license-code 参数接受一个包含 28 个大写字母字符密钥的列表。您可以一次添加一个许可证，也可以一次添加多个许可证，并以逗号分隔每个许可证密钥。

. 使用以下命令之一从原始节点中删除所有旧许可证：
+
`ssystem license clean-up -unused -expired`

+
`ssystem license delete -serial -number _node_serial _number_-package _licensable_package_`

+
--
** 删除所有已过期的许可证：
+
`ssystem license clean-up -expired`

** 删除所有未使用的许可证：
+
`ssystem license clean-up -unused`

** 在节点上使用以下命令从集群中删除特定许可证：
+
`ssystem license delete -serial -number _node1_serial _number_-package *``ssystem license delete -serial -number _node2_serial _number_-package *`



--
+
此时将显示以下输出：

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
输入 `y` 删除所有软件包。

. 使用以下命令并检查其输出，以验证是否已正确安装许可证：
+
`s系统许可证显示`

+
您可以将输出与中捕获的输出进行比较 link:prepare_nodes_for_upgrade.html["准备要升级的节点"] 部分。

. 如果在配置中使用了NetApp存储加密(NSE)、并且您将`setenv bootarg.storageencryption.support`命令设置为`true` with the `kmip.init.maxwait` variable `off`(in _Boot node2 with the AFF A900 or the FAS9500controller and NVRAM modules_、 link:boot_node2_with_a900_controller_and_nvs.html#A900_boot_node2["第 1 步"]），必须重置变量：
+
`set diag；systemshell -node _node_name_-command sudo kenv -u -p kmip.init.maxwait`

. 在两个节点上使用以下命令配置 SP ：
+
`ssystem service-processor network modify -node _node_name_`

+
请参见 link:other_references.html["参考资料"] 链接到 ONTAP `s管理参考 _ 以了解 SP 的相关信息，以及 _SP 9 命令：手册页参考 _ 以了解有关 system` service-processor network modify 命令的详细信息。

. 如果要在新节点上设置无交换机集群，请参见 link:other_references.html["参考资料"] 要链接到 _NetApp 支持站点 _ 并按照 _switchover to a two-node switchless cluster_ 中的说明进行操作。


.完成后
如果在 node1 和 node2 上启用了存储加密，请完成此部分 link:set_up_storage_encryption_new_module.html["在新控制器模块上设置存储加密"]。否则，请完成部分 link:decommission_old_system.html["停用旧系统"]。
