---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 在 AFF A700 升级到 AFF A900 期间，配置和管理存储加密，管理身份验证密钥并暂停 SnapMirror 关系。 
---
= 获取用于存储加密的外部密钥管理服务器的 IP 地址
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
升级后，您必须立即配置存储加密并建立集群范围的身份验证密钥，以替换先前的节点级别身份验证密钥。

.步骤
. 安装与密钥管理服务器通信所需的客户端和服务器安全套接字层（ SSL ）证书：
+
`s安全证书安装`

. 在每个节点上使用以下命令，在所有节点上配置存储加密：
+
`s安全密钥管理器外部启用`

. 添加每个密钥管理服务器的 IP 地址：
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. 验证是否已在集群中的所有节点上配置相同的密钥管理服务器并使其可用：
+
`s安全密钥管理器外部 show-status`

. 创建新的集群范围身份验证密钥：
+
`s安全密钥管理器密钥创建`

. 记下新的身份验证密钥 ID 。
. 使用新的身份验证密钥重新设置所有自加密驱动器的密钥：
+
`storage encryption disk modify -disk *-data-key-id _authentication_key_id_`





== 使用 KMIP 服务器管理身份验证

从 ONTAP 9.10.1 开始，您可以使用密钥管理互操作性协议（ Key Management Interoperability Protocol ， KMIP ）服务器管理身份验证密钥。

.步骤
. 添加新控制器：
+
`s安全密钥管理器外部启用`

. 添加密钥管理器：
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. 验证密钥管理服务器是否已配置且可供集群中的所有节点使用：
+
`s安全密钥管理器外部 show-status`

. 将所有链接的密钥管理服务器中的身份验证密钥还原到新节点：
+
`sSecurity key-manager external restore -node _new_controller_name_`

. 使用新的身份验证密钥重新设置所有自加密磁盘的密钥：
+
`storage encryption disk modify -disk * （ -data-key-id nonMSID AK ）`

. 如果使用联邦信息处理标准（ FIPS ），请使用新的身份验证密钥重新设置所有自加密磁盘的密钥：
+
`storage encryption disk modify -disk * （ -fips-key-id nonMSID AK ）`


