---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: 了解是否可以在升级配置中使用ARL来保留旧系统机箱和磁盘。 
---
= 升级控制器的准则
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要了解是否可以使用聚合重新定位(ARL)、保留旧系统机箱和磁盘、取决于系统升级配置和ONTAP版本。



== 支持 ARL 升级

某些系统配置支持控制器升级。请参阅link:decide_to_use_the_aggregate_relocation_guide.html#supported-systems["支持的系统升级组合"]以获取受支持的系统和最低 ONTAP 版本的列表。

如果您已收到完整的全新AFF A30、AFF A150 A50、AFF A900、AFF A90、AFF、AFF A70、AFF C30、AFF C60、AFF C80、FAS2820或FAS9500系统(包括新机箱)、请参阅link:other_references.html["参考资料"]链接以使用"system controller replace"命令升级运行ONTAP 9.8或更高版本的控制器硬件_。

配置了 SnapLock 企业版和 SnapLock 合规性卷的系统支持使用 ARL 升级控制器。



== 双节点无交换机集群

如果要升级双节点无交换机集群中的节点，则可以在执行升级时将这些节点保留在无交换机集群中。您无需将其转换为有交换机集群。



== 交换机连接的集群

如果您要升级连接到集群交换机的集群中的节点、则必须验证升级后交换机上运行的制造商、型号、固件版本、RCIF和ONTAP版本是否与替代控制器上运行的版本相同。如果需要、您必须先执行交换机升级、然后再使用ARL升级控制器。

有关详细信息，请参见 link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["连接到交换机连接的集群"]。



== 故障排除

升级节点对时可能会遇到故障。节点可能会崩溃，聚合可能无法重新定位或 LIF 可能无法迁移。故障的发生原因及其解决方案取决于升级操作步骤期间发生故障的时间。

如果出现任何问题，请参阅link:aggregate_relocation_failures.html["故障排除"]请参阅本过程末尾的部分，了解更多信息和可能的解决方案。有关可能发生的故障的信息按过程的阶段列出在link:overview_of_the_arl_upgrade.html["ARL 升级序列"] 。

如果您没有找到所遇到问题的解决方案，请联系技术支持。
