---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 您可以通过将旧系统转换为替代系统来升级控制器硬件、并保留旧系统机箱和磁盘。 
---
= 概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以通过使用聚合重新定位(ARL)并将现有系统转换为替代系统来无中断升级HA对上的控制器硬件、从而保留现有系统机箱和磁盘。


WARNING: 此操作步骤严格适用场景以下升级配置。请勿*使用此过程在任何其他系统组合之间执行升级。

[cols="20,20,40"]
|===
| 现有系统 | 更换系统 | 支持的ONTAP版本 


| AFF A800 ^1^ | AFF A90或AFF A70 | 9.15.1 


| 配置为全SAN阵列(ASA)的AFF A220 | ASA A150 | 9.13.1P1及更高版本 


| AFF A220 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5及更高版本 


| AFF A200 | AFF A150  a| 
9.10.1P15、9.11.1P11及更高版本^2^



| AFF C190 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5及更高版本 


| FAS2620 | FAS2820  a| 
9.11.1P7 (FAS2620)^2^μ m

9.13.1及更高版本(FAS2820)



| FAS2720 | FAS2820 | 9.13.1及更高版本 


| 配置为ASA的AFF A700 | ASA A900 | 9.13.1P1及更高版本 


| AFF A700 | AFF A900 | 9.10.1P10、9.11.1P6及更高版本 


| FAS9000 | FAS9500 | 9.10.1P10、9.11.1P6及更高版本 
|===
^1^升级到ONTAP 9.151中推出的系统时、ONTAP会转换所有现有精简配置卷(包括未使用存储效率的卷)的存储效率、并应用利用硬件卸载功能的新存储效率功能。这是一个自动后台进程、不会对系统性能造成明显影响。 https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["了解更多信息。"^](英文)

^2^ AFF A200和FAS2620系统不支持9.11.1之后的ONTAP版本。

[NOTE]
====
如果可能、NetApp建议您在旧系统和替代系统上使用相同的ONTAP版本。

上表中的最低ONTAP版本为必填项。这些ONTAP版本具有支持在升级期间在机箱内混用不同类型控制器所需的服务处理器或底板管理控制器(BMC)固件版本。

====
在操作步骤期间、您可以在旧控制器节点之间迁移非根聚合。安装后、您可以将非根聚合从旧控制器节点迁移到替代控制器节点。在升级操作步骤期间，您可以访问要升级的节点上托管的数据。

.关于此任务
在此控制器升级操作步骤期间、您可以执行以下升级之一：

[cols="30,70"]
|===
| 现有... | 执行以下操作... 


| AFF A800 | 将两个AFF A800控制器、NVRAM和所有I/O模块交换为新控制器和I/O模块。 


| AFF A220、AFF A200、AFF C190、FAS2620或FAS2720 | 将旧控制器上每个节点上的控制器模块交换为新模块。^1^ 


| AFF A700或FAS9000 | 将旧控制器上每个节点上的控制器和NVRAM模块交换为新模块。^1^ 
|===
^1^您无需移动、断开或重新连接I/O卡、数据线、磁盘架和磁盘。

此过程使用一种称为聚合重新定位(ARL)的方法。ARL可以利用HA配置和集群互连通信、如果非根聚合在同一集群中共享存储、则可以将这些聚合的所有权从一个节点移动到另一个节点。

在操作步骤期间，您可以使用替代控制器硬件升级原始控制器硬件，从而重新定位非根聚合的所有权。您可以在节点之间多次迁移聚合，以确认在整个升级操作步骤 中至少有一个节点正在从聚合提供数据。在继续操作时，您还可以在集群中的节点之间迁移数据 LIF 。


NOTE: 术语 * 节点 1 * 和 * 节点 2 * 仅用作本文档中节点名称的参考。按照此过程进行操作时、您必须替换节点的实际名称。

.重要信息
* 此操作步骤非常复杂，假定您具备高级 ONTAP 管理技能。您还应阅读并了解 link:guidelines_for_upgrading_controllers_with_arl.html["升级控制器的准则"] 和 link:overview_of_the_arl_upgrade.html["ARL 升级概述"] 开始升级前的章节。
* 此操作步骤假定更换用的控制器硬件是新的，尚未在其他系统中使用。使用 `wipeconfig` 命令准备已用控制器所需的步骤不在此操作步骤中。如果更换用的控制器硬件先前已用作另一个 ONTAP 集群的一部分或用作独立的单节点系统，则必须联系技术支持。
* 您可以使用此操作步骤升级具有两个以上节点的集群中的控制器硬件；但是，您需要为集群中的每个 HA 对单独执行操作步骤。
* 如果您的交换机不受ONTAP版本和要升级到的替代系统支持、请参阅 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe 。
* 对于集群和HA连接、AFF A70和AFF A90系统共享100GbE网络端口。这些系统可以支持与传统集群交换机建立10GbE或25GbE集群连接；但是、当不再需要10GbE和25GbE交换机时、NetApp建议更新到100GbE集群速度。有关详细信息，请参见以下知识库文章：
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["如何在FAS/FASA1K、A90、A70、AFF 90、ASA上的新集群设置中配置10G或25G集群端口"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["如何将FAS/FASA1K、A90、A70、AFF 90、ASA上的现有集群端口从10G或25G转换为40G或100G集群端口"^]


--
+
如果无法将现有节点上的e0a或e0b集群端口链接到新节点上的集群端口，请参见 link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp错误在线中的错误ID COBTP-166978"^]。

* 此过程仅适用于AFF A800、AFF A200、AFF A220、AFF C190、FAS2620、 FAS2720、AFF A700和FAS9000系统。对于需要升级到AFF A90、AFF A70、AFF A150、FAS2820、AFF A900的所有其他控制器型号、 或FAS9500系统、请参见 link:other_references.html["参考资料"] 链接到_use "system controller replace"命令升级运行ONTAP 9.8或更高版本的控制器硬件_以及_using聚合重新定位手动升级运行ONTAP 9.8或更高版本的控制器硬件_内容。
* ASA A900、AFF A900和FAS9500系统仅支持高端电源(200V至240V)。如果您的AFF A700或FAS9000系统使用低端电源(100V到120V)运行、则必须先转换AFF A700或FAS9000输入电源、然后才能使用此操作步骤。
* 如果要从AFF A800、AFF A200、AFF A220、AFF C190、FAS2620升级、 FAS2720、AFF A700或FAS9000系统停机时、您可以通过移动存储来升级控制器硬件、也可以联系技术支持。请参见 link:other_references.html["参考资料"] 链接到_Upgrade by Moving volumes"或"storage"。




== 自动执行控制器升级过程

此操作步骤提供了自动化操作步骤的步骤、该步骤使用自动磁盘分配和网络端口可访问性检查来简化控制器升级体验。
