---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install_replacement_system_modules_on_node2.html 
keywords: install, NVRAM, node2, controller, module, modules, replacement 
summary: 在对同一机箱中的控制器型号进行ARL升级期间、在node2上安装替代系统模块。 
---
= 在node2上安装替代系统模块
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在node2上安装您收到的用于升级的替代系统模块。Node2 是从系统背面查看控制器时位于机箱右侧的控制器 B 。

* <<在node2上安装AFF A150或FAS2820控制器模块>>
* <<在节点2上安装AFF A900或FAS9500NVRAM和控制器模块>>




== 在node2上安装AFF A150或FAS2820控制器模块

在node2上安装您收到的用于升级的AFF A150或FAS2820控制器模块。Node2 是从系统背面查看控制器时位于机箱右侧的控制器 B 。

.开始之前
* 如果您尚未接地，请正确接地。
* 从要卸下的控制器上断开所有缆线、包括控制台、管理、SAS存储和数据网络缆线。


.步骤
. 将控制器模块的末端与机箱中的托架 B 对齐，然后将控制器模块轻轻推入系统的一半。
+

TIP: 托架B位于机箱底部。

+

WARNING: 请勿将控制器模块完全插入机箱，直到稍后在操作步骤 中指示您这样做为止。

. 使用缆线将管理和控制台端口连接到 node2 控制器模块。
+

NOTE: 由于机箱已启动，因此 Node2 在完全就位后即开始启动。为避免node2启动、NetApp建议您先将控制台和管理缆线连接到node2控制器模块、然后再将控制器模块完全插入插槽。

. Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
控制器模块完全就位后，锁定闩锁会上升。

+

NOTE: 为避免损坏连接器，请勿在将控制器模块滑入机箱时用力过大。

. 一旦模块就位，请立即连接串行控制台，并准备好中断 node1 的自动启动。
. 中断自动启动后、node2将停留在加载程序提示符处。如果不中断自动启动，而 node2 开始启动，请等待提示符，然后按 * Ctrl-C * 进入启动菜单。在节点停留在启动菜单处后、使用选项8重新启动节点、并在重新启动期间中断自动启动。




== 在节点2上安装AFF A900或FAS9500NVRAM和控制器模块

在node2上安装为升级而收到的AFF A900或FAS9500NVRAM和控制器模块。Node2 是从系统背面查看控制器时位于机箱右侧的控制器 B 。

执行安装时、必须注意以下事项：

* 将插槽6-1和6-2中的所有空白填充模块从旧NVRAM模块移至新的NVRAM模块。
* 请勿将核心转储设备从AFF A700 NVRAM模块移至AFF A900 NVRAM模块。
* 将FAS9000 NVRAM模块中安装的所有闪存缓存模块移至FAS9500NVRAM模块。


.开始之前
如果您尚未接地，请正确接地。



=== 安装AFF A900或FAS9500NVRAM模块

使用以下操作步骤 将AFF A900或FAS9500NVRAM模块安装在节点2的插槽6中。

.步骤
. 将 NVRAM 模块与插槽 6 中机箱开口的边缘对齐。
. 将 NVRAM 模块轻轻滑入插槽，直到带字母和编号的 I/O 凸轮闩锁开始与 I/O 凸轮销啮合，然后将 I/O 凸轮闩锁一直向上推，以将 NVRAM 模块锁定到位。




=== 在节点2中安装AFF A900或FAS9500控制 器模块

使用以下操作步骤 在node2中安装AFF A900或FAS9500控制 器模块。

.步骤
. 将控制器模块的末端与机箱中的托架 B 对齐，然后将控制器模块轻轻推入系统的一半。
+

TIP: 托架标签位于机箱上控制器模块正上方。

+

NOTE: 请勿将控制器模块完全插入机箱，直到稍后在操作步骤 中指示您这样做为止。

. 使用缆线将管理和控制台端口连接到 node2 控制器模块。
+

NOTE: 由于机箱已启动，因此 Node2 在完全就位后即开始启动。为了避免 node2 启动，建议在将控制器模块完全插入插槽之前，先将控制台和管理缆线连接到 node2 控制器模块。

. Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
控制器模块完全就位后，锁定闩锁会上升。

+

WARNING: 为避免损坏连接器，请勿在将控制器模块滑入机箱时用力过大。

. 一旦模块就位，请立即连接串行控制台，并准备好中断 node1 的自动启动。
. 中断自动启动后， node2 将停留在 LOADER 提示符处。如果不中断自动启动，而 node2 开始启动，请等待提示符，然后按 * Ctrl-C * 进入启动菜单。在节点停留在启动菜单后，使用选项 `8` 重新启动节点，并在重新启动期间中断自动启动。
. 在node2的loader>提示符处、设置默认环境变量：
+
`set-defaults`

. 保存默认环境变量设置：
+
`saveenv`


