---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1. aff, a900, NVRAM, controller 
summary: 在将 AFF A700 升级到 AFF A900 期间，将节点 2 的非根聚合重新定位到节点 1 。 
---
= 将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在将node2更换为AFF A900或FAS9500控制 器模块和NVRAM模块之前、必须先将node2所拥有的非根聚合重新定位到node1。

上一阶段的后处理检查完成后， node2 的资源释放将自动启动。非根聚合和非 SAN 数据 LIF 将从 node2 迁移到新的 node1 。

迁移聚合和 LIF 后，此操作将暂停以进行验证。在此阶段，您必须验证所有非根聚合和非 SAN 数据 LIF 是否均已迁移到新的节点 1 。

不会修改聚合和 LIF 的主所有者；只会修改当前所有者。

.步骤
. 验证所有非根聚合是否均已联机及其在 node1 上的状态：
+
`storage aggregate show -node node1 -state online -root false`

+
以下示例显示 node1 上的非根聚合处于联机状态：

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	 #Vols	 Nodes	  RAID	   Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB      744.8GB	 0%	 online	  5	 node1	  raid_dp  normal
aggr_2	      825.0GB	    825.0GB	 0%	 online	  1	 node1	  raid_dp  normal
2 entries were displayed.
----
+
如果 node1 上的聚合脱机或变为外部聚合，请在新的 node1 上使用以下命令将其联机，每个聚合一次：

+
`storage aggregate online -aggregate _aggr_name_`

. 在 node1 上使用以下命令并检查其输出，以验证 node1 上的所有卷是否联机：
+
`volume show -node node1 -state offline`

+
如果 node1 上的任何卷脱机，请在 node1 上使用以下命令将其联机，每个卷一次：

+
`volume online -vserver _vserver-name_-volume _volume-name_`

+
要与此命令结合使用的 ` <vserver-name>` 可在上一个 `volume show` 命令的输出中找到。

. 验证 LIF 是否已移至正确的端口且状态为 `up` 。如果任何 LIF 已关闭，请通过为每个 LIF 输入以下命令将 LIF 的管理状态设置为 up ：
+
`network interface modify -vserver _vserver_name_-lif _LIF_name_-home-node _nodename_- status-admin up`

. 使用以下命令并检查输出，以验证 node2 上是否没有剩余数据 LIF ：
+
`network interface show -curr-node _node2_-role data`


