---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: '如果需要、请在将AFF A700升级到AFF A900期间为NVE或NAE配置新控制器模块。"' 
---
= 在新控制器模块上设置NetApp卷或聚合加密
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果新控制器的已更换控制器或高可用性(HA)配对系统使用NetApp卷加密(NVE)或NetApp聚合加密(NAE)、则必须为NVE或NAE配置新控制器模块。

.关于此任务
此操作步骤包含对新控制器模块执行的步骤。您必须在正确的节点上输入命令。

[role="tabbed-block"]
====
.板载密钥管理器
--
*使用板载密钥管理器配置NVE或NAE *

.步骤
. 将所有链接的密钥管理服务器中的身份验证密钥还原到新节点：
+
`sSecurity key-manager 板载同步`



--
.外部密钥管理
--
*使用外部密钥管理配置NVE或NAE *

.步骤
. 验证密钥管理服务器是否仍可用，其状态及其身份验证密钥信息：
+
`sSecurity key-manager key query -node node`

. 将上一步中列出的密钥管理服务器添加到新控制器的密钥管理服务器列表中：
+
.. 添加密钥管理服务器：
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

.. 对列出的每个密钥管理服务器重复上述步骤。您最多可以链接四个密钥管理服务器。
.. 验证是否已成功添加密钥管理服务器：
+
`security key-manager external show`



. 在新控制器模块上，运行密钥管理设置向导以设置和安装密钥管理服务器。
+
您必须安装与现有控制器模块上安装的密钥管理服务器相同的密钥管理服务器。

+
.. 在新节点上启动密钥管理服务器设置向导：
+
`s安全密钥管理器外部启用`

.. 完成向导中的步骤以配置密钥管理服务器。


. 将所有链接的密钥管理服务器中的身份验证密钥还原到新节点：
+
`s安全密钥管理器外部还原`

+
此命令需要OKM密码短语

+
有关详细信息、请参见知识库文章 https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["如何从ONTAP 启动菜单还原外部密钥管理器服务器配置"^]。



--
====
.完成后
检查是否有任何卷因身份验证密钥不可用或无法访问 EKM 服务器而脱机。使用 `volume online` 命令将这些卷恢复联机。

.完成后
检查是否有任何卷因身份验证密钥不可用或无法访问外部密钥管理服务器而脱机。使用 `volume online` 命令将这些卷恢复联机。
