---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node1_installation.html 
keywords: verifying, verify, node1, install, installation, aff, a900, nvs, controller 
summary: 使用 AFF A900 控制器模块和 NVS 验证 node1 安装。 
---
= 验证 node1 安装
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必须使用 AFF A900 控制器模块和 NVS 验证 node1 安装。由于物理端口不变，您无需将物理端口从 AFF A700 node1 映射到 AFF A900 node1 。

使用 AFF A900 控制器模块启动 node1 后，必须验证是否已正确安装它。您必须等待 node1 加入仲裁，然后恢复控制器更换操作。

此时，在操作步骤中，控制器升级操作应已暂停，因为 node1 会自动尝试加入仲裁。

.步骤
. 验证 node1 是否已加入仲裁：
+
`cluster show -node node1 -fields health`

+
`health` 字段的输出应为 `true` 。

. 验证 node1 是否与 node2 属于同一集群，并且其运行状况是否良好：
+
`cluster show`

. 切换到高级权限模式：
+
`set advanced`

. 检查控制器更换操作的状态，并验证其是否处于暂停状态，以及是否处于 node1 暂停之前的状态，以便执行安装新控制器和移动缆线的物理任务：
+
`ssystem controller replace show`

+
`s系统控制器更换 show-details`

. 恢复控制器更换操作：
+
`s系统控制器更换恢复`

. 控制器更换操作将暂停以进行干预，并显示以下消息：
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node1         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node2         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: 在本指南中， _re-creating VLAN ， ifgrp 和 broadcast domains_has been re命名 为 _Restore network configuration on node1_ 。

. 在控制器更换处于暂停状态的情况下，继续执行 <<Restore network configuration on node1>>。




== 还原 node1 上的网络配置

确认 node1 处于仲裁状态并可与 node2 通信后，请确认 node1 上显示了 node1 的 VLAN ，接口组和广播域。此外，验证所有 node1 网络端口是否均已配置在其正确的广播域中。

有关创建和重新创建 VLAN ，接口组和广播域的详细信息，请参见 link:other_references.html["参考资料"] 链接到 _Network Management_ 内容。

.步骤
. 列出已升级的节点 1 上的所有物理端口：
+
`network port show -node node1`

+
此时将显示节点上的所有物理网络端口， VLAN 端口和接口组端口。在此输出中，您可以看到 ONTAP 已将任何物理端口移至 `集群` 广播域。您可以使用此输出来帮助确定应将哪些端口用作接口组成员端口， VLAN 基本端口或用于托管 LIF 的独立物理端口。

. 列出集群上的广播域：
+
`broadcast-domain show`

. 列出节点 1 上所有端口的网络端口可访问性：
+
`network port reachability show -node node1`

+
您应看到类似于以下示例的输出：

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e11a     -                                    no-reachability
          e11b     -                                    no-reachability
          e11c     -                                    no-reachability
          e11d     -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e4a      Cluster:Cluster                      ok
          e4e      Cluster:Cluster                      ok
          e5a      -                                    no-reachability
          e7a      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
22 entries were displayed.
----
+
在上述示例中， node1 在更换控制器后启动。某些端口不具有可访问性，因为没有物理连接。您必须修复状态为 `ok` 以外的可访问性的任何端口。

+

NOTE: 在将 AFF A700 升级到 AFF A900 控制器期间，网络端口及其连接不应发生变化。所有端口都应驻留在正确的广播域中，并且网络端口可访问性不应更改。但是，在将 LIF 从 node2 移回 node1 之前，您必须验证网络端口的可访问性和运行状况。

. [[restore_node1_step4]] 使用以下命令按以下顺序修复 node1 上每个端口的可访问性状态不是 `ok` 的可访问性：
+
`network port reachability repair -node <node_name> -port <port_name>`

+
--
.. 物理端口
.. VLAN 端口


--
+
您应看到类似于以下示例的输出：

+
[listing]
----
Cluster ::> reachability repair -node node1 -port e11b
----
+
[listing]
----
Warning: Repairing port "node1:e11b" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
对于可访问性状态可能与当前所在广播域的可访问性状态不同的端口，应显示一条警告消息，如上所示。根据需要查看端口和问题解答 `y` 或 `n` 的连接。

+
验证所有物理端口是否具有预期可访问性：

+
`网络端口可访问性显示`

+
在执行可访问性修复时， ONTAP 会尝试将端口放置在正确的广播域中。但是，如果无法确定某个端口的可访问性，并且该端口不属于任何现有广播域，则 ONTAP 将为这些端口创建新的广播域。

. 验证端口可访问性：
+
`网络端口可访问性显示`

+
如果所有端口均已正确配置并添加到正确的广播域中，则 `network port reachability show` 命令应将所有已连接端口的可访问性状态报告为 `ok` ，对于无物理连接的端口，此状态报告为 `no-reachability` 。如果任何端口报告的状态不是这两个端口，请按照中的说明执行可访问性修复并在其广播域中添加或删除端口 <<restore_node1_step4,第 4 步>>。

. 验证所有端口是否均已置于广播域中：
+
`network port show`

. 验证广播域中的所有端口是否配置了正确的最大传输单元（ MTU ）：
+
`network port broadcast-domain show`

. 使用以下步骤还原 LIF 主端口，指定需要还原的 Vserver 和 LIF 主端口（如果有）：
+
.. 列出所有已替换的 LIF ：
+
`displaced interface show`

.. 还原 LIF 主节点和主端口：
+
`displaced interface restore-home-node -node node_name -vserver vserver_name -lif-name LIF_name`



. 验证所有 LIF 是否都具有主端口且已由管理员启动：
+
`network interface show -fields home-port ， status-admin`


