---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade 
summary: 了解是否可以对运行 ONTAP 9.8 或更高版本的控制器使用手动 ARL 升级操作步骤 。 
---
= 使用 ARL 升级控制器的准则
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要了解是否可以使用聚合重新定位（ Aggregate Relocation ， ARL ）升级一对运行 ONTAP 9.8 的控制器，取决于原始控制器和替代控制器的平台和配置。



== 支持 ARL 升级

在以下情况下，您可以使用 ARL 升级一对节点：

* 在升级之前，原始控制器和替代控制器必须运行相同版本的 ONTAP 9.8 。
* 替代控制器的容量必须等于或高于原始控制器。容量等于或更大是指 NVRAM 大小，卷， LUN 或聚合计数限制等属性；它也是指新节点的最大卷或聚合大小。
* 您可以升级以下类型的系统：
+
** FAS 系统到 FAS 系统。
** 将 FAS 系统连接到使用 FlexArray 虚拟化软件的系统或 V 系列系统。
** AFF 系统到 AFF 系统。
** 将安装了 FlexArray 虚拟化软件或 V 系列系统的系统连接到 FAS 系统，前提是安装了 FlexArray 虚拟化软件或 V 系列系统的系统没有阵列 LUN 。
** V 系列系统到使用 FlexArray 虚拟化软件的系统或 V 系列系统。


* 对于某些 ARL 控制器升级，您可以使用替代控制器上的临时集群端口进行升级。例如，如果您从 AFF A300 升级到 AFF A400 系统，则根据 AFF A400 配置，您可以使用两个夹层端口中的任何一个，也可以添加一个四端口 10GbE 网络接口卡来提供临时集群端口。使用临时集群端口完成控制器升级后，您可以无中断地将集群迁移到替代控制器上的 100GbE 端口。
* 配置了 SnapLock 企业版和 SnapLock 合规性卷的系统支持使用 ARL 升级控制器。


您必须验证是否可以对原始控制器和更换控制器执行 ARL 。您必须检查所有已定义聚合的大小以及原始系统支持的磁盘数。然后将其与新系统支持的聚合大小和磁盘数进行比较。要访问此信息，请参见 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe 。新系统支持的聚合大小和磁盘数必须等于或大于原始系统支持的聚合大小和磁盘数。

您必须在集群混用规则中验证在更换原始控制器后，新节点是否可以加入现有节点的集群。有关集群混合规则的详细信息，请参见 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe 。


NOTE: 这两个系统要么是高可用性（ HA ），要么是非 HA 。两个节点都必须启用或禁用此特性；您不能将启用了全闪存优化特性的节点与未在同一 HA 对中启用此特性的节点组合使用。如果个性化设置不同，请联系技术支持。


NOTE: 如果新系统的插槽数少于原始系统，或者端口数较少或不同，则可能需要向新系统添加适配器。请参见 link:other_references.html["参考资料"] 链接到 Hardware Universe 支持站点上的 _NetApp 支持站点以了解有关特定平台的详细信息。

如果您的系统每个节点具有两个以上的集群端口，例如 FAS8080 或 AFF8080 ，则必须先将集群 LIF 整合为每个节点两个集群端口，然后再开始控制器升级。如果在每个节点上执行控制器升级时使用两个以上的集群端口，则在升级后，新控制器上可能会缺少集群 LIF 。



== ARL 不支持升级

您不能执行以下升级：

* 与无法运行 ONTAP 9.8 或更高版本的控制器之间的连接。
* 更换不支持与原始控制器相连的磁盘架的控制器
+
有关磁盘支持信息，请参见 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe 。

* 来自具有根聚合或内部驱动器上的数据聚合的控制器。
+
如果要升级内部磁盘驱动器上具有根聚合或数据聚合的控制器，请参见 link:other_references.html["参考资料"] 要链接到 _Upgrade by moving volumes or storage_ 并转到操作步骤 _upgrading a pair of nodes running candlused_by Data ONTAP moving volumes_ 。

+

NOTE: 如果要升级集群中节点上的 ONTAP ，请参见 link:other_references.html["参考资料"] 链接到 _Upgrade ONTAP 。





== 假设和术语

本文档的编写假设如下：

* 替代控制器硬件是新的，尚未使用。
+

WARNING: * 注意 * ：由于此操作步骤假定更换用的控制器硬件是新的，尚未使用，因此使用 `wipeconfig` 命令准备已用控制器所需的步骤不会包含在此操作步骤中。如果先前使用的是替代控制器硬件，则必须联系技术支持，尤其是在控制器以 7- 模式运行 Data ONTAP 时。

* 您已阅读并了解升级节点对的准则。
+

WARNING: * 注意 * 请勿尝试清除 NVRAM 内容。如果需要清除 NVRAM 的内容，请联系 NetApp 技术支持。

* 您正在执行 `m修改` 命令前后的相应命令，并比较两个 `show` 命令的输出以验证 `m修改` 命令是否成功。
* 如果您具有 SAN 配置，则 HA 对上的每个 Storage Virtual Machine （ SVM ）都具有本地和配对 LIF 。如果每个 SVM 没有本地和配对 LIF ，则应在开始升级之前在该 SVM 的远程和本地节点上添加 SAN 数据 LIF 。
* 如果 SAN 配置中有端口集，则必须已验证每个绑定端口集是否至少包含 HA 对中每个节点的一个 LIF 。


此操作步骤使用术语 _boot environment prompt_ 来表示节点上可从中执行某些任务的提示，例如重新启动节点以及打印或设置环境变量。此提示有时会非正式地称为 _boot loader prompts_ 。

以下示例显示了启动环境提示符：

[listing]
----
LOADER>
----


== ONTAP 9.8 或更高版本中的许可

设置集群时，设置向导会提示您输入集群基础许可证密钥。但是，某些功能需要额外的许可证，这些许可证以 _packages_ 的形式发布，其中包括一个或多个功能。集群中的每个节点都必须有自己的密钥，才能在集群中使用每个功能。

如果没有新的许可证密钥，则新控制器可以使用集群中当前已获得许可的功能，这些功能将继续正常工作。但是，在控制器上使用未经许可的功能可能会使您不符合您的许可协议，因此，您必须在升级完成后为新控制器安装新的许可证密钥。

所有许可证密钥的长度均为 28 个大写字母字符。请参见 link:other_references.html["参考资料"] 链接到 _NetApp 支持站点 _ ，在此可以获取 ONTAP 9.8 的 28 个字符的新许可证密钥。或更高版本。这些密钥位于 _Software licenses_ 下的 _My Support_ 部分中。如果此站点没有所需的许可证密钥，请联系您的 NetApp 销售代表。

有关许可的详细信息，请访问 link:other_references.html["参考资料"] 链接到系统管理参考。



== 存储加密

原始节点或新节点可能已启用存储加密。在这种情况下，您必须在此操作步骤 中执行其他步骤，以验证是否已正确设置存储加密。

如果要使用存储加密，与节点关联的所有磁盘驱动器都必须具有自加密磁盘驱动器。



== 双节点无交换机集群

如果要升级双节点无交换机集群中的节点，则可以在执行升级时将这些节点保留在无交换机集群中。您无需将其转换为交换集群。



== 故障排除

此操作步骤包含故障排除建议。

如果在升级控制器时出现任何问题，请参见 link:troubleshoot.html["故障排除"] 部分，请参见操作步骤末尾的详细信息和可能的解决方案。

如果您未找到与遇到的问题相关的解决方案 ，请联系技术支持。
