---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster 
summary: 使用手动 ARL 升级操作步骤 升级运行 ONTAP 9.8 或更高版本的控制器硬件，重新定位非根聚合的所有权。 
---
= 概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此操作步骤 介绍了如何在以下系统配置中使用聚合重新定位（ Aggregate Relocation ， ARL ）升级控制器硬件：

[cols="20,20,60"]
|===
| 方法 | ONTAP 版本 | 支持的系统 


| 使用 ARL 手动升级 | 9.8 或更早版本  a| 
* FAS 系统到 FAS 系统
* 将 FAS 系统连接到使用 FlexArray 虚拟化软件的系统或 V 系列系统
* AFF 系统到 AFF 系统
* 使用 FlexArray 虚拟化软件或 V 系列系统的系统连接到 FAS 系统，前提是使用 FlexArray 虚拟化软件或 V 系列系统的系统没有阵列 LUN 。
* V 系列系统到使用 FlexArray 虚拟化软件的系统或 V 系列系统


|===
在操作步骤期间，您可以使用替代控制器硬件升级原始控制器硬件，从而重新定位非根聚合的所有权。您可以在节点之间多次迁移聚合，以确认在整个升级操作步骤 中至少有一个节点正在从聚合提供数据。您还可以迁移数据逻辑接口（ LIF ），并在继续操作时将新控制器上的网络端口分配给接口组。


NOTE: 在本文档中，原始节点称为 _node1_ 和 _node2_ ，新节点称为 _node3_ 和 _node4_ 。在所述的操作步骤期间， node1 将替换为 node3 ， node2 将替换为 node4 。术语 _node1_ ， _node2_ ， _node3_ 和 _node4_ 仅用于区分原始节点和新节点。在操作步骤之后，必须替换原始节点和新节点的实际名称。但是，实际上，节点名称不会更改：在升级控制器硬件后， node3 的名称为 node1 ， node4 的名称为 node2 。本文档使用术语 _systems with FlexArray Virtualization Software_ 来指属于这些新平台的系统。它使用术语 _V 系列系统 _ 来表示可以连接到存储阵列的不同硬件系统

.重要信息：
* 此操作步骤非常复杂，假定您具备高级 ONTAP 管理技能。您还必须阅读并了解 link:guidelines_upgrade_with_arl.html["使用 ARL 升级控制器的准则"] 和 link:arl_upgrade_workflow.html["ARL 升级工作流"] 开始升级前的章节。
* 此操作步骤假定更换用的控制器硬件是新的，尚未使用。使用 `wipeconfig` 命令准备已用控制器所需的步骤不在此操作步骤中。如果先前使用的是替代控制器硬件，则必须联系技术支持，尤其是在控制器以 7- 模式运行 Data ONTAP 时。
* 您可以使用此操作步骤升级具有两个以上节点的集群中的控制器硬件；但是，您需要为集群中的每个高可用性（ HA ）对单独执行操作步骤。
* 此操作步骤适用场景 FAS 系统， V 系列系统， AFF 系统以及安装了 FlexArray 虚拟化软件的系统。如果安装了所需的许可证，则在 ONTAP 9 之后发布的 FAS 系统可以连接到存储阵列。ONTAP 9 支持现有 V 系列系统。有关存储阵列和 V 系列型号的信息，请参见 link:other_references.html["参考资料"] 要链接到 _V Hardware Universe 系列支持表 _ 并查看 _V 系列支持表 _ 。


* 除了非 MetroCluster 配置之外，这种运行 ONTAP 9.8 及更高版本的操作步骤适用场景光纤 MetroCluster 四节点和八节点配置。
+
** 对于运行 ONTAP 9.7 及更早版本的 MetroCluster 配置，请转至 link:other_references.html["参考资料"] 链接到 _ 使用聚合重新定位手动升级运行 ONTAP 9.7 或更早版本的控制器硬件 _ 。
** 有关 MetroCluster IP 配置以及适用于 Fabric MetroCluster 配置的其他升级选项，请转至 link:other_references.html["参考资料"] 链接到 _RAID MetroCluster 升级和扩展 _ 内容。



