---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/install_boot_node4.html 
keywords: node4, install ONTAP, boot, node4, relocate, non-root aggregates, disks 
summary: 在运行 ONTAP 9.8 或更高版本的控制器上手动升级 ARL 期间，安装和启动 node4 并安装 ONTAP 软件。 
---
= 安装并启动节点 4.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必须在机架中安装 node4 ，将 node2 连接传输到 node4 以及启动 node4 。此外，还必须重新分配任何 node2 备用磁盘，属于 root 的任何磁盘以及先前未重新定位到 node3 的任何非根聚合。

.关于此任务
如果节点 4 上安装的 ONTAP 9 版本与节点 2 上安装的 ONTAP 9 版本不同，则必须安装 node4 后，从 Web 服务器上存储的 ONTAP 9 映像启动它。通过网络启动节点 4。然后，您可以按照link:prepare_for_netboot.html["准备网络启动"] 。

但是，如果 node4 上安装的 ONTAP 9 与 node2 上安装的相同或更高版本，则无需通过网络启动 node4。

[IMPORTANT]
====
* 对于AFF A800或AFF C800控制器升级，在移除节点 2 之前，必须确保机箱中的所有驱动器都牢固地固定在中板上。有关详细信息，请参阅 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更换AFF A800或AFF C800控制器模块"]。
* 如果您要升级带有存储磁盘的系统，则必须完成整个部分，然后继续执行下一节link:set_fc_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"] ，在集群提示符下输入命令。


====
.步骤
. [[man_install4_Step1]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 node4 将位于 ... | 那么 ... 


| 与 node3 不同的机箱 | 转至 <<man_install4_Step2,第 2 步>>。 


| 具有 node3 的同一机箱 | 跳过步骤 2 和 3 ，然后转到 <<man_install4_Step4,第 4 步>>。 
|===
. [[man_install4_Step2]] 确保 node4 具有足够的机架空间。
+
如果 node4 与 node3 位于不同的机箱中，则可以将 node4 与 node2 放在同一位置。如果 node3 和 node4 位于同一机箱中，则 node4 已位于其相应的机架位置。

. 按照节点型号的 _Installation and Setup Instructions_中 的说明，在机架中安装 node4 。
. 【 man_install4_Step4]] 为节点 4 布线，将连接从节点 2 移动到节点 4 。
+
以下参考资料可帮助您正确进行缆线连接。转至 link:other_references.html["参考资料"] 以链接到它们。

+
** node4 平台的_安装和设置说明_
** 相应的磁盘架操作步骤
** HA对管理文档
+
使用缆线连接以下连接：

** 控制台（远程管理端口）
** 集群端口
** 数据端口
** 集群和节点管理端口
** 存储
** SAN 配置： iSCSI 以太网和 FC 交换机端口


+

NOTE: 您无需将互连卡 /FC_VI 卡或互连 /FC_VI 缆线连接从 node2 移至 node4 ，因为大多数平台型号都具有唯一的互连卡型号。

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 node4 位于 ... | 那么 ... 


| 与 node3 相同的机箱 | 转至 <<man_install4_Step8,第 8 步>>。 


| 与 node3 不同的机箱 | 转至 <<man_install4_Step6,第 6 步>>。 
|===
. [[man_install4_step6]]打开node4的电源、然后按Ctrl-C访问启动环境提示符以中断启动。
+

NOTE: 启动 node4 时，您可能会看到以下消息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. 【 ｛ man_install4_Step7]] 如果您在步骤 6 中看到警告消息，请执行以下操作：
+
.. 检查是否存在任何可能指示 NVRAM 电池电量低以外问题的控制台消息，如有必要，请采取任何必要的更正措施。
.. 让电池充电并完成启动过程。
+

WARNING: *不要覆盖延迟。如果电池无法充电，可能会导致数据丢失。*



. [[man_install4_Step8]]在维护模式提示符下，输入以下命令：
+
`halt`

+
系统将在启动环境提示符处停止。

. 为 ONTAP 配置 node4 ：
+
`set-defaults`

. 如果您安装了 NetApp 存储加密 (NSE) 驱动器，请执行以下步骤：
+

NOTE: 如果您之前尚未在操作步骤 中执行此操作、请参见知识库文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判断驱动器是否已通过FIPS认证"^] 确定正在使用的自加密驱动器的类型。

+
.. 设置 `bootarg.storageencryption.support` to `true` 或 `false`：
+
[cols="35,65"]
|===
| 如果正在使用以下驱动器、请使用… | 然后选择… 


| 符合FIPS 140-2 2级自加密要求的NSE驱动器 | `setenv bootarg.storageencryption.support *true*` 


| NetApp非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
不能在同一节点或HA对上混用FIPS驱动器和其他类型的驱动器。

您可以在同一节点或HA对上混用SED和非加密驱动器。

====
.. 转到专用启动菜单并选择选项 `(10) Set Onboard Key Manager recovery secrets`。
+
输入先前记录的操作步骤 密码短语和备份信息。请参见 link:manage_authentication_okm.html["使用板载密钥管理器管理身份验证密钥"]。



. 如果 node4 上安装的 ONTAP 版本与 node2 上安装的 ONTAP 9 版本相同或更高，请输入以下命令：
+
`boot_ontap 菜单`

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| node4 上的 ONTAP 版本不正确或当前不正确 | 前往<<man_install4_Step13,第 13 步>>。 


| node4 上的 ONTAP 版本正确或最新 | 前往<<man_install4_Step18,第 18 步>>。 
|===
. [[man_install4_Step13]]通过选择以下操作之一来配置网络启动连接。
+

NOTE: 您必须使用管理端口和 IP 地址作为网络启动连接。请勿使用数据 LIF IP 地址，否则在执行升级期间可能会发生数据中断。

+
[cols="35,75"]
|===
| 动态主机配置协议（ DHCP ） | 那么 ... 


| 正在运行  a| 
在启动环境提示符处输入以下命令，以自动配置连接： `ifconfig e0M -auto`



| 未运行  a| 
在启动环境提示符处输入以下命令、以手动配置连接：
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` 是存储系统的IP地址(必填)。
`_netmask_` 是存储系统的网络掩码(必需)。
`_gateway_` 是存储系统的网关(必需)。
`_dns_addr_` 是网络上名称服务器的IP地址(可选)。
`_dns_domain_` 是域名服务(Domain Name Service、DNS)域名。如果使用此可选参数，则无需在网络启动服务器 URL 中使用完全限定域名；您只需要服务器的主机名。


NOTE: 您的接口可能需要其他参数。有关详细信息，请在固件提示符处输入 `help ifconfig` 。

|===
. 对 node4 执行网络启动：
+
[cols="30,70"]
|===
| 针对 ... | 那么 ... 


| FAS/AFF8000 系列系统 | `netboot \http://web_server_ip/path_to_webaccessible_directory/netboot/kernel` 


| 所有其他系统 | `netboot \http://web_server_ip/path_to_webaccessible_directory/ontap_version_image.tgz` 
|===
+
`path_to_the_web-accessible_directory` 应指向下载 `ontap_version_image.tgz` 的位置 link:prepare_for_netboot.html#man_netboot_Step1["第 1 步"] 在 _prepare for netboot_ 一节中。

+

NOTE: 请勿中断启动。

. 从启动菜单中，选择 `option （ 7 ） Install new software first` 。
+
此菜单选项可下载新的 Data ONTAP 映像并将其安装到启动设备中。

+
请忽略以下消息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
注意适用场景可无中断升级 Data ONTAP ，而不是升级控制器。

+

NOTE: 请始终使用 netboot 将新节点更新为所需映像。如果您使用其他方法在新控制器上安装映像，则可能会安装不正确的映像。此问题描述适用场景是 ONTAP 的所有版本。netboot操作步骤 与选项结合使用 `(7) Install new software` 擦除启动介质并将相同的ONTAP 版本放置在两个映像分区上。

. 【 ｛ man_install4_step23]] 如果系统提示您继续运行操作步骤，请输入 y ，当系统提示您输入软件包时，请输入 URL ：
+
` http://web_server_ip/path_to_web-accessible_directory/ontap_version_image.tgz`

. 完成以下子步骤：
+
.. 出现以下提示时，输入 `n` 以跳过备份恢复：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 出现以下提示时，输入 `y` 以重新启动：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
控制器模块重新启动，但停留在启动菜单处，因为启动设备已重新格式化，需要还原配置数据。



. [[man_install4_Step18]]选择维护模式 `5`从启动菜单并输入 `y`当提示您继续启动时。
. [[man_install4_Step19]]继续之前，请转到link:set_fc_uta_uta2_config_node4.html["在 node4 上设置 FC 或 UTA/UTA2 配置"]对节点上的 FC 或 UTA/UTA2 端口进行任何必要的更改。按照这些部分中建议的进行更改，重新启动节点，然后进入维护模式。
. 输入以下命令并检查输出以查找 node4 的系统 ID ：
+
`d` 展示 -A

+
系统将显示节点的系统 ID 及其磁盘信息，如以下示例所示：

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. 重新分配 node2 的备用磁盘，属于根的磁盘以及第节前面未重新定位到 node3 的任何非根聚合 link:relocate_non_root_aggr_node2_node3.html["将非根聚合从 node2 重新定位到 node3"]：
+

NOTE: 如果系统上有共享磁盘、混合聚合或这两者、则必须使用正确的 `disk reassign` 下表中的命令。

+
[cols="35,65"]
|===
| Disk type | 运行命令 ... 


| 共享磁盘 | `dreassign -s`` node2_sysid_-d _node4_sysid_-p _node3_sysid_` 


| 无共享 | `disks disk reassign -s`` node2_sysid_-d _node4_sysid_` 
|===
+
。 `<node2_sysid>` 值、请使用中捕获的信息 link:record_node2_information.html#man_record_2_step10["第 10 步"] 记录 node2 信息 _ 部分的。适用于 `_node4_sysid_`，请使用中捕获的信息 <<man_install4_step23,第 23 步>>。

+

NOTE: 只有当存在共享磁盘时，才需要在维护模式下使用 ` -p` 选项。

+
`d`` reassign`命令将仅重新分配node2_sysid_是当前所有者的磁盘。

+
系统将显示以下消息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
当系统要求中止磁盘重新分配时，输入 `n` 。

+
当系统要求您中止磁盘重新分配时，您必须按照以下步骤所示问题解答一系列提示：

+
.. 系统将显示以下消息：
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. 输入 `y` 以继续。
+
系统将显示以下消息：

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. 输入 `y` 以允许更新磁盘所有权。


. 如果要从具有外部磁盘的系统升级到支持内部和外部磁盘的系统（例如， A800 系统），请将 node4 设置为 root ，以确认它从 node2 的根聚合启动。
+

WARNING: * 警告：必须按所示的确切顺序执行以下子步骤；否则可能发生原因会导致中断甚至数据丢失。 *

+
以下操作步骤会将 node4 设置为从 node2 的根聚合启动：

+
.. 检查 node2 聚合的 RAID ，丛和校验和信息：
+
`aggr status -r`

.. 检查 node2 聚合的整体状态：
+
`聚合状态`

.. 如有必要，将 node2 聚合置于联机状态：
+
`aggr_online root_aggr_from__node2_`

.. 阻止 node4 从其原始根聚合启动：
+
`aggr offline _root_aggr_on_node4_`

.. 将 node2 根聚合设置为 node4 的新根聚合：
+
`aggr options aggr_from__node2_ root`



. 输入以下命令并观察输出，以验证控制器和机箱是否配置为 `ha` ：
+
`ha-config show`

+
以下示例显示了 `ha-config show` 命令的输出：

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
系统会在 PROM 中记录它们是采用 HA 对还是独立配置。独立系统或 HA 对中的所有组件的状态都必须相同。

+
如果控制器和机箱未配置为 `ha` ，请使用以下命令更正配置：

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha` 。

+
如果您使用的是 MetroCluster 配置，请使用以下命令更正此配置：

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. 销毁 node4 上的邮箱：
+
`m邮箱销毁本地`

. 退出维护模式：
+
`halt`

+
系统将在启动环境提示符处停止。

. 在 node3 上，检查系统日期，时间和时区：
+
`dATE`

. 在 node4 上，在启动环境提示符处检查日期：
+
`s如何选择日期`

. 如有必要，请在 node4 上设置日期：
+
`set date _MM/dd/yyy_`

. 在 node4 上，在启动环境提示符处检查时间：
+
`s时间`

. 如有必要，请在 node4 上设置时间：
+
`set time _hh：mm：ss_`

. 验证合作伙伴系统 ID 是否按照<<man_install4_Step19,第 19 步>>在选项下。
+
`printenv partner-sysid`

. 如有必要，请在 node4 上设置配对系统 ID ：
+
`setenv partner-sysid _node3_sysid_`

+
.. 保存设置：
+
`saveenv`



. 在启动环境提示符处输入启动菜单：
+
`boot_ontap 菜单`

. 在启动菜单中，在提示符处输入 `6` ，选择选项 * （ 6 ） Update flash from backup config* 。
+
系统将显示以下消息：

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. 在提示符处输入 `y` 。
+
启动正常进行，系统会提示您确认系统 ID 不匹配。

+

NOTE: 系统可能会重新启动两次，然后才会显示不匹配警告。

. 确认不匹配。节点可能会在正常启动之前完成一轮重新启动。
. 登录到 node4 。

