---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: 在运行 ONTAP 9.8 或更高版本的控制器上手动进行 ARL 升级期间，验证 node1 上的物理端口是否正确映射到 node3 。 
---
= 将端口从 node1 映射到 node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必须确保 node1 上的物理端口正确映射到 node3 上的物理端口，从而使 node3 能够在升级后与集群中的其他节点以及网络进行通信。

您必须已从 _Node_ 获得有关新节点上端口的信息 Hardware Universe 。转至 link:other_references.html["参考资料"] 链接到 _SIL_ Hardware Universe ）。您可以使用本节后面和中的信息 link:map_ports_node2_node4.html["将端口从 node2 映射到 node4"]。

node3 的软件配置必须与 node3 的物理连接匹配，并且必须先还原 IP 连接，然后才能继续升级。

端口设置可能因节点型号而异。

.步骤
. 【第 1 步】执行以下步骤，验证设置是否为双节点无交换机集群：
+
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 验证设置是否为双节点无交换机集群：
+
`network options switchless-cluster show`

+
例如：

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
此命令的值必须与系统的物理状态匹配。

.. 返回到管理权限级别：
+
`set -privilege admin`



. 【第 2 步】进行以下更改：
+
.. 修改将属于集群广播域的端口：
+
`network port modify -node _node_name_-port _port_name_-mtu 9000 -ipspace Cluster`

+
此示例将在 "node1" 上添加集群端口 e1b ：

+
[listing]
----
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000
----
.. 将每个 LIF 的集群 LIF 迁移到新端口一次：
+
`network interface migrate -vserver _vserver_name_-lif _lif_name_-source-node _node1_-destination-node _node1_-destination-port _port_name_`

+
迁移所有集群 LIF 并建立集群通信后，集群应达到仲裁状态。

.. 修改集群 LIF 的主端口：
+
`network interface modify -vserver cluster -lif _lif_name_–home-port _port_name_`

.. 从集群广播域中删除旧端口：
+
`network port broadcast-domain remove-ports -ipspace cluster -broadcast-domain cluster -ports _node1：port_`

.. 显示 node1 和 node3 的运行状况：
+
`cluster show -node _node1_-fields health`

.. 每个集群 LIF 都必须侦听端口 7700 。验证集群 LIF 是否正在侦听端口 7700 ：
+
` ：：： > 网络连接侦听 show -vserver Cluster`

+
对于双节点集群，端口 7700 侦听集群端口是预期结果，如以下示例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. 如有必要，对于未侦听端口 7700 的每个集群 LIF ，将 LIF 的管理状态设置为 `down` ，然后设置 `up` ：
+
`：：> net int modify -vserver cluster -lif _cluster-lif_-status-admin down；net int modify -vserver cluster -lif _cluster-lif_-status-admin up`

+
重复子步骤（ f ）以验证集群 LIF 是否正在侦听端口 7700 。



. [[man_map_1_step3]] 修改托管数据 LIF 的物理端口的广播域成员资格。
+
.. 列出所有端口的可访问性状态：
+
`网络端口可访问性显示`

.. 通过在每个端口上运行以下命令，修复物理端口以及 VLAN 端口的可访问性，一次运行一个端口：
+
`re可访问性修复-node _node_name_-port _port_name_`

+
此时将显示类似以下内容的警告。查看并根据需要输入 `y` 或 `n` ：

+
[listing]
----
WARNING: Repairing port "node_name:port" might cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
.. 要使 ONTAP 能够完成修复，请在最后一个端口上运行 `reachability repair` 命令后等待大约一分钟。
.. 列出集群上的所有广播域：
+
`broadcast-domain show`

.. 在执行可访问性修复时， ONTAP 会尝试将端口放置在正确的广播域中。但是，如果无法确定某个端口的可访问性，并且该端口与任何现有广播域不对应，则 ONTAP 将为这些端口创建新的广播域。如果新创建的广播域的所有成员端口都将成为接口组的成员端口，则可以根据需要删除这些成员端口。删除广播域
+
`broadcast-domain delete -broadcast-domain _broadcast_domain_`

.. 查看接口组配置，并根据需要添加或删除成员端口。
+
将成员端口添加到接口组端口：

+
`ifgrp add-port -node _node_name_-ifgrp _ifgrp_port_-port _port_name_`

+
从接口组端口删除成员端口：

+
`ifgrp remove-port -node _node_name_-ifgrp _ifgrp_port_-port _port_name_`

.. 根据需要删除并重新创建 VLAN 端口。删除 VLAN 端口：
+
`vlan delete -node _node_name_-vlan-name _vlan_port_`

+
创建 VLAN 端口：

+
`vlan create -node _node_name_-vlan-name _vlan_port_`

+

NOTE: 根据要升级的系统的网络配置的复杂性，可能需要重复子步骤（ a ）到（ g ），直到所有端口都在需要时正确放置为止。



. 【第 4 步】如果系统上未配置任何 VLAN ，请转至 ,第 5 步。如果已配置 VLAN ，请还原先前在不再存在的端口上配置的或在已移至另一广播域的端口上配置的已替换 VLAN 。
+
.. 显示已替换的 VLAN ：
+
`cluster controller-replacement network placed-vlans show`

.. 将已替换的 VLAN 还原到所需的目标端口：
+
`displaced -vVLAN restore -node _node_name_-port _port_name_-destination-port _destination_port_`

.. 验证所有已替换的 VLAN 是否已还原：
+
`cluster controller-replacement network placed-vlans show`

.. VLAN 会在创建后大约一分钟自动放置到相应的广播域中。验证已还原的 VLAN 是否已放置在相应的广播域中：
+
`网络端口可访问性显示`



. 从ONTAP 9.8开始、如果在网络端口可访问性修复操作步骤 期间在广播域之间移动了LIF的主端口、则ONTAP 将自动修改LIF的主端口。如果 LIF 的主端口已移至另一个节点或未分配，则该 LIF 将显示为已替换的 LIF 。还原主端口不再存在或已重新定位到另一节点的已替换 LIF 的主端口。
+
.. 显示主端口可能已移至另一个节点或不再存在的 LIF ：
+
`displaced interface show`

.. 还原每个 LIF 的主端口：
+
`displaced interface restore -vserver _vserver_name_-lif-name _LIF_name_`

.. 验证是否已还原所有 LIF 主端口：
+
`displaced interface show`



+
如果所有端口均已正确配置并添加到正确的广播域中，则 `network port reachability show` 命令应将所有已连接端口的可访问性状态报告为 "ok" ，而对于没有物理连接的端口，此状态报告为 "no-reachability " 。如果任何端口报告的状态不是这两个端口，请按照中所述修复可访问性 ,第 3 步。

. [[man_map_1_step6]] 验证属于正确广播域的端口上的所有 LIF 是否已由管理员启动。
+
.. 检查是否存在任何已被管理员关闭的 LIF ：
+
`network interface show -vserver _vserver_name_-status-admin down`

.. 检查是否有任何 LIF 运行中断：
+
`network interface show -vserver _vserver_name_-status-oper down`

.. 修改任何需要修改的 LIF ，使其具有不同的主端口：
+
`network interface modify -vserver _vserver_name_-lif _LIF_name_-home-port _home_port_`

+

NOTE: 对于 iSCSI LIF ，修改主端口需要以管理员方式关闭 LIF 。

.. 还原不在其各自主端口主端口的 LIF ：
+
`网络接口还原 *`




