---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html 
keywords: move, aggregates, nas, lif, node2, node3, node4 
summary: 在运行 ONTAP 9.8 或更高版本的控制器上手动升级 ARL 期间，将 node3 上的 node2 NAS 数据 LIF 从 node3 移动到 node4 。 
---
= 将 node2 拥有的 NAS 数据 LIF 从 node3 移动到 node4 并验证 node4 上的 SAN LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
将端口从 node2 映射到 node4 之后，在将 node2 聚合从 node3 重新定位到 node4 之前，必须将节点 3 上当前由 node2 拥有的 NAS 数据 LIF 从 node3 移动到 node4 。您还必须验证 node4 上的 SAN LIF 。

在升级操作步骤期间，远程 LIF 处理 SAN LUN 的流量。升级期间，集群或服务运行状况无需移动 SAN LIF 。除非需要将 SAN LIF 映射到新端口，否则不会移动这些 LIF 。使 node4 联机后，您需要验证 LIF 是否运行正常并位于相应的端口上。

.步骤
. 通过在任一节点上输入以下命令并捕获输出，列出不属于 node3 的所有 NAS 数据 LIF ：
+
`network interface show -role data -curr-node node3 -is-home false`

. 【 ｛ 工作表 _step2_node2]] 如果为集群配置了 SAN LIF ，请在此记录 SAN LIF 和现有配置信息 link:worksheet_information_before_moving_san_lifs_node4.html["工作表"] 以供日后在操作步骤 中使用。
+
.. 列出 node3 上的 SAN LIF 并检查输出：
+
`network interface show -data-protocol fc*`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. 列出现有配置并检查输出：
+
`fcp adapter show -fields switch-port ， fc-wwpn`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 node2... | Description 


| 已配置接口组或 VLAN | 转至 ,第 4 步。 


| 未配置接口组或 VLAN | 跳过步骤 4 ，然后转到 ,第 5 步。 
|===
. [[man_lif_verif_4_Step3]] 执行以下步骤，将最初位于 node2 上的接口组和 VLAN 上托管的任何 NAS 数据 LIF 从 node3 迁移到 node4 。
+
.. 【 man_lif_verif_4_substepa 】通过为每个 LIF 输入以下命令，将先前属于接口组上 node2 的 node3 上托管的任何 LIF 迁移到 node4 上能够在同一网络上托管 LIF 的端口：
+
`network interface migrate -vserver _vserver_name_-lif _lif_name_-destination-node node4–destination-port _netport_ifgrp_`

.. 在中修改 LIF 的主端口和主节点 ,子步骤 A 输入以下命令，将 LIF 设置为当前托管 LIF 的端口和节点，每个 LIF 设置为一次：
+
`network interface modify -vserver _vserver_name_-lif _datalif_name_-home-node node4 home-port _netport_ifgrp_`

.. 【 man_lif_verif_4_substepc]] 通过为每个 LIF 输入以下命令，将先前属于 VLAN 端口上 node2 的 node3 上托管的任何 LIF 迁移到 node4 上能够在同一网络上托管 LIF 的端口：
+
`network interface migrate -vserver _vserver_name_-lif _datalif_name_-destination-node node4–destination-port _netport_ifgrp_`

.. 在中修改 LIF 的主端口和主节点 ,子步骤 c 输入以下命令，将 LIF 设置为当前托管 LIF 的端口和节点，每个 LIF 设置为一次：
+
`network interface modify -vserver _vserver_name_-lif _datalif_name_-home-node _node4_ home-port _netport_ifgrp_`



. 【 man_lif_verif_4_Step4]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果集群配置为 ... | 那么 ... 


| NAS | 完成 ,第 6 步 到 ,第 9 步，跳过步骤 10 并完成 ,第 11 步 到 ,第 14 步。 


| SAN | 跳过步骤 6 到步骤 9 并完成 ,第 10 步 到 ,第 14 步。 


| NAS 和 SAN | 完成 ,第 6 步 到 ,第 14 步。 
|===
. 【 man_lif_verif_4_Step5]] 如果您的平台上的数据端口不同，请输入以下命令将这些端口添加到广播域：
+
`network port broadcast-domain add-ports -ipspace _ipspace_name_-broadcast-domain mgmt ports _node：port_`

+
以下示例将节点 "6280-1 " 上的端口 "e0a" 和节点 "8060-1 " 上的端口 "e0i" 添加到 IP 空间默认值中的广播域管理中：

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default  -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. 输入以下命令，将每个 NAS 数据 LIF 迁移到 node4 ，每个 LIF 一次：
+
`network interface migrate -vserver _vserver-name_-lif _datalif-name_-destination-node _node4_-destination-port _netport_ifgrp_-home-node _node4_`

. 确保数据迁移持久：
+
`network interface modify -vserver _vserver_name_-lif _datalif_name_-home-port _netport_ifgrp_`

. 【 man_lif_verif_4_Step8]] 输入以下命令列出所有网络端口并检查其输出，以验证所有链路的状态是否为 `up` ：
+
`network port show`

+
以下示例显示了 `network port show` 命令的输出，其中一些 LIF 已启动，另一些 LIF 已关闭：

+
[listing]
----
cluster::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node3
       a0a       Default      -                up       1500  auto/1000
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0a-1     Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
node4
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
12 entries were displayed.
----
. 【 man_lif_verif_4_Step9]] 如果 `network port show` 命令的输出显示了新节点中不可用且旧节点中存在的网络端口，请通过完成以下子步骤删除旧网络端口：
+
.. 输入以下命令，输入高级权限级别：
+
`set -privilege advanced`

.. 为每个旧网络端口输入以下命令一次：
+
`network port delete -node _node_name_-port _port_name_`

.. 输入以下命令，返回到管理员级别：
+
`set -privilege admin`



. 【 man_lif_verif_4_Step10]] 完成以下子步骤，确认 SAN LIF 位于 node4 上的正确端口上：
+
.. 输入以下命令并检查其输出：
+
`network interface show -data-protocol iscsi_FCP -home-node node4`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster::> network interface show -data-protocol iscsi|fcp -home-node node4
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            a0a          up/down  10.63.0.53/24      node4         a0a     true
            data1        up/up    10.63.0.50/18      node4         e0c     true
            rads1        up/up    10.63.0.51/18      node4         e1a     true
            rads2        up/down  10.63.0.52/24      node4         e1b     true
vs1
            lif1         up/up    172.17.176.120/24  node4         e0c     true
            lif2         up/up    172.17.176.121/24  node4
----
.. 通过将 `fcp adapter show` 命令的输出与您在工作表中记录的新配置信息进行比较，验证新的 `adapter` 和 `switch-port` 配置是否正确 ,第 2 步。
+
列出 node4 上的新 SAN LIF 配置：

+
`fcp adapter show -fields switch-port ， fc-wwpn`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----
+

NOTE: 如果新配置中的 SAN LIF 不在仍连接到同一个 `s交换机端口` 发生原因 的适配器上，则在重新启动节点时，它可能会导致系统中断。

.. 如果 node4 中的任何 SAN LIF 或 SAN LIF 组位于 node2 上不存在的端口上，请输入以下命令之一将其移动到 node4 上的相应端口：
+
... 将 LIF 状态设置为 down ：
+
`network interface modify -vserver _vserver_name_-lif _lif_name_-status-admin down`

... 从端口集中删除 LIF ：
+
`portset remove -vserver _vserver_name_-portset _portset_name_-port-name _port_name_`

... 输入以下命令之一：
+
**** 移动单个 LIF ：
+
`network interface modify -lif _lif_name_-home-port _new_home_port_`

**** 将一个不存在或不正确的端口上的所有 LIF 移动到新端口：
+
`network interface modify｛-home-port _port_on_node2_-home-node _node2_-role data｝-home-port _new_home_port_on_node4_`

**** 将 LIF 重新添加到端口集：
+
`portset add -vserver _vserver_name_-portset _portset_name_-port-name _port_name_`







+

NOTE: 您必须将 SAN LIF 移动到与原始端口具有相同链路速度的端口。

. 输入以下命令，将所有 LIF 的状态修改为 `up` ，以便 LIF 可以在节点上接受和发送流量：
+
`network interface modify -vserver _vserver_name_-home-port _port_name_-home-node _node4_ lif _lif_name_-status-admin up`

. 在任一节点上输入以下命令并检查输出，以验证是否已将任何 SAN LIF 移动到正确的端口，以及 LIF 的状态是否为 `up` ：
+
`network interface show -home-node _node4_-role data`

. [[man_lif_verif_4_Step13]] 如果任何 LIF 已关闭，请通过输入以下命令将 LIF 的管理状态设置为 `up` ，每个 LIF 一次：
+
`network interface modify -vserver _vserver_name_-lif _lif_name_-status-admin up`


