---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node1_node2.html 
keywords: nas, node1, node2, lifs, cluster, san 
summary: 在运行 ONTAP 9.8 或更高版本的控制器上手动升级 ARL 期间，如果您使用的是双节点集群，请将 node1 的数据 LIF 移至 node2 ；如果您的集群具有两个以上的节点，则将其移至第三个节点。 
---
= 将 node1 拥有的 NAS 数据 LIF 移动到 node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在将 node1 替换为 node3 之前，如果您使用的是双节点集群，则必须将 node1 拥有的 NAS 数据 LIF 移动到 node2 ；如果您的集群具有两个以上的节点，则必须将此数据 LIF 移动到第三个节点。您使用的方法取决于集群是为 NAS 配置还是为 SAN 配置的。

在升级操作步骤期间，远程 LIF 处理 SAN LUN 的流量。升级期间，集群或服务运行状况无需移动 SAN LIF 。使 node3 联机后，您必须验证 LIF 是否运行正常并位于相应的端口上。

.步骤
. 输入以下命令并捕获输出，列出 node1 上托管的所有 NAS 数据 LIF ：
+
`network interface show -data-protocol nfs|cifs -curr-node node1`

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. 【第 2 步】修改 node1 和 node2 上所有 LIF 的自动还原设置：
+
`network interface modify -vserver vserver_name -lif LIF_name -auto-revert false`

. 【第 3 步】执行以下步骤，迁移节点 1 上接口组和 VLAN 上托管的任何 NAS 数据 LIF ：
+
.. 【 ｛ substepa ｝ 】通过为每个 LIF 输入以下命令，将任何接口组上托管的 LIF 以及 node1 上的 VLAN 迁移到 node2 上能够在与接口组相同的网络上托管 LIF 的端口：
+
`network interface migrate -vserver vserver_name -lif LIF_name -destination-node node2 – destination-port netport_ifgrp`

.. 在中修改 LIF 和 VLAN 的主端口和主节点 <<substepa,子步骤 A>> 输入以下命令，将 LIF 设置为当前托管 LIF 的端口和节点，每个 LIF 设置为一次：
+
`network interface modify -vserver vserver_name -lif LIF_name -home-node node2 - home-port netport_ifgrp`



. 【第 4 步】执行以下操作之一：
+
[cols="20,80"]
|===
| 如果集群配置为 ... | 那么 ... 


| NAS | 完成 <<man_lif_1_2_step5,第 5 步>> 到 <<man_lif_1_2_step8,第 8 步>>。 


| SAN | 禁用节点上的所有 SAN LIF 以将其关闭以进行升级： `network interface modify -vserver vserver-name -lif LIF_name -home-node node_to_upgrade -home-port netports|ifgrp -status-admin down` 
|===
. 【 man_lif_1_2_step5]] 通过输入以下命令将 NAS 数据 LIF 从 node1 迁移到 node2 ，每个数据 LIF 输入一次：
+
`network interface migrate -vserver vserver-name -lif LIF_name -destination-node node2 -destination-port data_port`

. 【第 6 步】输入以下命令并检查其输出，通过在任一节点上输入以下命令并检查输出来验证 LIF 是否已移至正确的端口以及 LIF 的状态是否为 up ：
+
`network interface show -curr-node node2 -data-protocol nfs|cifs`

. 【第 7 步】修改已迁移 LIF 的主节点：
+
`network interface modify -vserver vserver-name -lif LIF_name -home-node node2 -home-port port_name`

. 【 man_lif_1_2_step8]] 验证 LIF 是否正在使用此端口作为其主端口或当前端口。如果端口不是主端口或当前端口，请转到 <<man_lif_1_2_step9,第 9 步>>：
+
`network interface show -home-node node2 -home-port port_name`

+
`network interface show -curr-node node_name -curr-port port_name`

. 【 ｛ man_lif_1_2_step9]] 如果 LIF 使用此端口作为主端口或当前端口，请修改此 LIF 以使用其他端口：
+
`network interface migrate -vserver vserver-name -lif LIF_name -destination – node node_name -destination-port port_name`

+
`network interface modify -vserver vserver-name -lif LIF_name -home – node node_name -home-port port_name`

. 【第 10 步】如果任何 LIF 已关闭，请输入以下命令，将 LIF 的管理状态设置为 "up" ，每个 LIF 一次：
+
`network interface modify -vserver vserver-name -lif LIF_name -home-node nodename -status-admin up`

+

NOTE: 对于 MetroCluster 配置，您可能无法更改端口的广播域，因为它与托管目标 Storage Virtual Machine （ SVM ） LIF 的端口相关联。从远程站点上对应的源 SVM 输入以下命令，将目标 LIF 重新分配到相应的端口： `MetroCluster vserver resync -vserver vserver_name`

. 【第 11 步】输入以下命令并检查其输出，以验证 node1 上是否没有剩余数据 LIF ：
+
`network interface show -curr-node node1 -role data`


