---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/relocate_non_root_aggr_node2_node3.html 
keywords: non-root, non-root, aggregates, relocate, node2, node3 
summary: 在运行 ONTAP 9.8 或更高版本的控制器上手动升级 ARL 期间，发送 node2 的 AutoSupport 消息并手动将 node2 的非根聚合重新定位到 node3 。 
---
= 将非根聚合从 node2 重新定位到 node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要将node2替换为node4、您需要先为node2发送AutoSupport消息、然后将node2拥有的非根聚合重新定位到node3。


CAUTION: 在此过程中、请勿将聚合从node3重新定位到node2。这样做会导致聚合脱机、并导致重新定位的聚合发生数据中断。

[[verify-partner-sys-id]]
.步骤
. 请确认节点3上的合作伙伴系统ID设置是否正确：
+
.. 输入高级权限级别：
+
`set -privilege advanced`

.. 显示node3上的配对系统ID：
+
`ha interconnect config show -node <node3-node1>`

+
系统将显示类似于以下示例的输出：

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. 如果node3的"配对系统ID"不正确：
+
.. 暂停node3：
+
`halt`

.. 在Loader提示符处、设置正确的"Partner-sysd"值。
+
node3 "Partner-sysid"是node2的系统ID，可在的输出中找到 `ha interconnect config show`<<verify-partner-sys-id,第 1 步>>。

.. 保存设置：
+
`saveenv`

.. 在Loader提示符处、将node3启动到启动菜单中：
+
`boot_ontap 菜单`

.. 登录到 node3 。


. 向NetApp发送node2的AutoSupport消息：
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. 验证是否已发送 AutoSupport 消息：
+
`system node autosupport show -node <node2> -instance`

+
字段 " 上次发送主题： " 和 " 上次发送时间： " 包含上次发送消息的消息标题以及消息发送时间。

. [[relocate-step5]]重新定位非根聚合：
+
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 列出 Node2 所拥有的聚合：
+
`storage aggregate show -owner-name <node2>`

.. 启动聚合重新定位：
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: 此命令仅查找非根聚合。

.. 出现提示时，输入 `y` 。
+
重新定位在后台进行。重新定位聚合可能需要几秒到几分钟的时间。此时间既包括客户端中断，也包括非中断部分。此命令不会重新定位任何脱机聚合或受限聚合。

.. 返回到管理权限级别：
+
`set -privilege admin`



. 验证 node2 的重新定位状态：
+
`storage aggregate relocation show -node <node2>`

+
重新定位聚合后、输出将显示该聚合的"Done (完成)"。

+

NOTE: 您必须等待 node2 所拥有的所有聚合都重新定位到 node3 ，然后再继续下一步。

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果重新定位 ... | 那么 ... 


| 所有聚合均已成功 | 转到。 <<man_relocate_2_3_step8,第 8 步>> 


| 任何聚合失败或被否决  a| 
.. 显示详细的状态消息：
+
`storage aggregate show -instance`

+
您还可以检查 EMS 日志以查看所需的更正操作。

+

NOTE: `event log show`命令可列出已发生的任何错误。

.. 执行更正操作。
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 重新定位任何出现故障或被否决的聚合：
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. 出现提示时，输入 `y` 。
.. 返回到管理权限级别：
+
`set -privilege admin`



如有必要，您可以使用以下方法之一强制执行重新定位：

** 通过覆盖否决检查：
+
`s存储聚合重新定位 start -override-vetoes true -no-controller-upgrade`

** 通过覆盖目标检查：
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



有关 storage aggregate relocation 命令的详细信息，请转至 link:other_references.html["参考资料"] 要使用 cli_ 和 _disk ONTAP 9 命令链接到 _disk 和聚合管理：手册页参考 _ 。

|===
. 【 man_relocate_2_3_step8]] 验证 node3 上的所有非根聚合是否联机：
+
`storage aggregate show -node <node3> -state offline -root false`

+
如果任何聚合已脱机或变为外部聚合，则必须使其联机，每个聚合一次：

+
`storage aggregate online -aggregate <aggregate_name>`

. 验证 node3 上的所有卷是否均已联机：
+
`volume show -node <node3> -state offline`

+
如果 node3 上的任何卷脱机，则必须使其联机，每个卷一次：

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. 验证node2是否不拥有任何联机非根聚合：
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
命令输出不应显示联机非根聚合，因为所有非根联机聚合都已重新定位到 node3 。


