---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: 在运行 ONTAP 9.8 或更高版本的控制器上手动升级 ARL 期间，配置 Node3 板载 FC 端口， UTA/UTA2 端口或 UTA/UTA2 卡。 
---
= 在 node3 上设置 FC 或 UTA/UTA2 配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果 node3 具有板载 FC 端口，板载统一目标适配器（ UTA/UTA2 ）端口或 UTA/UTA2 卡，则必须先配置这些设置，然后才能完成其余操作步骤。

.关于此任务
您可能需要完成 <<在 node3 上配置 FC 端口>>或 <<检查并配置 node3 上的 UTA/UTA2 端口>>或这两个部分。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代 CNA 适配器和端口。但是，命令行界面使用术语 "CNA" 。

* 如果 node3 没有板载 FC 端口，板载 UTA/UTA2 端口或 UTA/UTA2 卡，并且您要升级具有存储磁盘的系统，则可以跳至 link:map_ports_node1_node3.html["将端口从 node1 映射到 node3"]。
* 但是，如果您使用的是 V 系列系统或安装了 FlexArray 虚拟化软件和存储阵列的系统，并且 node3 没有板载 FC 端口，板载 UTA/UTA 端口或 UTA/UTA2 卡，请返回 _Install and boot node3_ 并在中继续 link:install_boot_node3.html#step22["第 22 步"]。


.选项：
* <<在 node3 上配置 FC 端口>>
* <<检查并配置 node3 上的 UTA/UTA2 端口>>




== 在 node3 上配置 FC 端口

如果 node3 具有板载或 FC 适配器上的 FC 端口，则必须先在节点上设置端口配置，然后再将其投入使用，因为这些端口未经过预配置。如果未配置端口，则可能会发生服务中断。

.开始之前
您必须具有保存在中的 node1 中的 FC 端口设置值 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.关于此任务
如果您的系统没有 FC 配置，则可以跳过此部分。如果您的系统具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则可以在中对其进行配置 <<检查并配置 node3 上的 UTA/UTA2 端口>>。


NOTE: * 重要信息 * ：如果您的系统具有存储磁盘，请在集群提示符处输入本节中的命令。如果您使用的是 V 系列系统或 FlexArray 虚拟化软件并连接到存储阵列，请在维护模式下在此部分中输入命令。

.步骤
. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| 具有存储磁盘 | 转至 <<man_config_3_step5,第 5 步>> 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 转至 <<man_config_3_step2,第 2 步>> 
|===
. 【 man_config_3_step2]] 启动 node3 和访问维护模式：
+
`boot_ontap maint`

. 【第 3 步】执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| 具有存储磁盘 | 输入以下命令： `ssystem node hardware unified-connect show` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列。 | 输入以下命令 `ucadmin show` 
|===
+
系统将显示有关系统上所有 FC 和融合网络适配器的信息。

. 【第 4 步】将 node3 的 FC 设置与先前从 node1 捕获的设置进行比较。
. [[man_config_3_step5]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 新节点上的默认 FC 设置 | 那么 ... 


| 与您在 node1 上捕获的相同 | 转至 <<man_config_3_step11,第 11 步>>。 


| 与您在 node1 上捕获的不同 | 转至 <<man_config_3_step6,第 6 步>>。 
|===
. 【 man_config_3_step6]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| 具有存储磁盘  a| 
根据需要输入以下命令之一，修改 node3 上的 FC 端口：

** 要对目标端口进行编程：`ssystem node hardware unified-connect modify -type |-t target -adapter _port_name_`
** 要对启动程序端口进行编程：`ssystem node hardware unified-connect modify -type |-t initiator -adapter _port_name_`


` -t` 是 FC4 类型： target 或 initiator 。



| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 根据需要输入以下命令、修改node3上的FC端口：`ucadmin modify -m fc -t initiator -f _adapter_port_name_``-t`是FC4类型、目标或启动程序。* 注 * ：必须将 FC 端口编程为启动程序。 
|===
. 【第 7 步】执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| 具有存储磁盘 | 输入以下命令并检查输出，以验证新设置： `ssystem node hardware unified-connect show` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 输入以下命令并检查输出，以验证新设置： `ucadmin show` 
|===
. 【第 8 步】输入以下命令退出维护模式：
+
`halt`

. 【第 9 步】输入命令后，请等待系统在启动环境提示符处停止。
. 【第 10 步】执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| 是 V 系列系统或具有运行集群模式 Data ONTAP 8.3 的 FlexArray 虚拟化软件 | 在启动环境提示符处启动 node3 并访问维护： `boot_ontap maint` 


| 不是 V 系列系统或没有 FlexArray 虚拟化软件 | 在启动环境提示符处启动 node3 ： `boot_ontap` 
|===
. 【 man_config_3_step11]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要升级的系统 ... | 那么 ... 


| 具有存储磁盘  a| 
** 如果 node3 具有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请转至 <<检查并配置 node3 上的 UTA/UTA2 端口>>。
** 如果 node3 没有 UTA/UTA2 卡或 UTA/UTA2 板载端口，请跳过 <<检查并配置 node3 上的 UTA/UTA2 端口>> 然后转到 link:map_ports_node1_node3.html["将端口从 node1 映射到 node3"]。




| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列  a| 
** 如果 node3 具有卡或板载端口，请转至 <<检查并配置 node3 上的 UTA/UTA2 端口>>。
** 如果 node3 没有卡或板载端口，请跳过 <<检查并配置 node3 上的 UTA/UTA2 端口>>，并返回到 _Install 和 boot node3_ ，然后在继续 link:install_boot_node3.html#step7["第 7 步"]。


|===




== 检查并配置 node3 上的 UTA/UTA2 端口

如果 node3 具有板载 UTA/UTA2 端口或 UTA/UTA2 卡，则必须检查这些端口的配置，并可能对其进行重新配置，具体取决于您希望如何使用升级后的系统。

.开始之前
您必须为 UTA/UTA2 端口配备正确的 SFP+ 模块。

.关于此任务
如果要对 FC 使用统一目标适配器（ UTA/UTA2 ）端口，则必须先验证此端口的配置方式。


NOTE: NetApp 营销材料可能会使用术语 UTA2 来指代 CNA 适配器和端口。但是，命令行界面使用术语 CNA 。

您可以使用 `ucadmin show` 命令验证当前端口配置：

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
UTA/UTA2 端口可以配置为原生 FC 模式或 UTA/UTA2 模式。FC 模式支持 FC 启动程序和 FC 目标； UTA/UTA2 模式支持并发 NIC 和 FCoE 流量共享相同的 10GbE SFP+ 接口并支持 FC 目标。

UTA/UTA2 端口可能位于适配器或控制器上，并且具有以下配置，但您应检查 node3 上的 UTA/UTA2 端口的配置，并根据需要进行更改：

* 订购控制器时订购的 UTA/UTA2 卡会在发货前配置为具有您请求的个性化设置。
* 与控制器分开订购的 UTA/UTA2 卡附带了默认的 FC 目标特性。
* 新控制器上的板载 UTA/UTA2 端口会在发货前配置为具有您请求的个性化设置。
+

NOTE: * 注意 * ：如果您的系统具有存储磁盘，则必须在集群提示符处输入本节中的命令，除非系统指示您进入维护模式。如果您使用的是 Vseries 系统或 FlexArray 虚拟化软件并连接到存储阵列，则必须在维护模式提示符处在此部分中输入命令。要配置 UTA/UTA2 端口，您必须处于维护模式。



.步骤
. 在node3上输入以下命令以检查端口当前的配置方式：
+
[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘 | `ssystem node hardware unified-connect show` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | `ucadmin show` 
|===
+
系统将显示类似于以下示例的输出：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending  Admin
Adapter  Mode     Type       Mode     Type     Status
-------  -------  ---------  -------  -------  ------
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
0e       fc       initiator  -        -        online
0f       fc       initiator  -        -        online
0g       cna      target     -        -        online
0h       cna      target     -        -        online
*>
----
. 【第 2 步】如果当前 SFP+ 模块与所需用途不匹配，请将其更换为正确的 SFP+ 模块。
+
请联系您的 NetApp 代表以获取正确的 SFP+ 模块。

. `s步骤 3]] 查看` system node hardware unified-connect show `或` ucadmin show 命令的输出，以确定 UTA/UTA2 端口是否具有所需的个性化设置。
. 【第 4 步】执行以下操作之一：
+
[cols="35,65"]
|===
| 如果 UTA/UTA2 端口 ... | 那么 ... 


| 没有所需的个性化设置 | 转至 <<man_check_3_step5,第 5 步>>。 


| 拥有所需的个性化特性 | 跳过步骤 5 到步骤 12 ，然后转到 <<man_check_3_step13,第 13 步>>。 
|===
. [[man_check_3_step5]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘，并且正在运行集群模式 Data ONTAP 8.3 | 启动 node3 并进入维护模式： `boot_ontap maint` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 转至 <<man_check_3_step6,第 6 步>>。您应已处于维护模式。 
|===
. 【 man_check_3_step6]] 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果要配置 | 那么 ... 


| UTA/UTA2 卡上的端口 | 转至 <<man_check_3_step7,第 7 步>>。 


| 板载 UTA/UTA2 端口 | 跳过第 7 步，转到 <<man_check_3_step8,第 8 步>>。 
|===
. [[man_check_3_step7]] 如果适配器处于启动程序模式，并且 UTA/UTA2 端口联机，请使 UTA/UTA2 端口脱机：
+
`storage disable adapter _adapter_name_`

+
目标模式下的适配器会在维护模式下自动脱机。

. [[man_check_3_step8]] 如果当前配置与所需用途不匹配，请根据需要更改配置：
+
`ucadmin modify -m fc|cna -t initiators|target _adapter_name_`

+
** ` -m` 是特性模式， `fc` 或 `CNA` 。
** ` -t` 是 FC4 类型， `target` 或 `initiator` 。
+

NOTE: 您需要对磁带驱动器， FlexArray 虚拟化系统和 MetroCluster 配置使用 FC 启动程序。您需要对 SAN 客户端使用 FC 目标。



. 验证设置：
+
`ucadmin show`

. 验证设置：
+
[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘  a| 
.. 停止系统：
+
`halt`

+
系统将在启动环境提示符处停止。

.. 输入以下命令：
+
`boot_ontap`





| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 重新启动至维护模式： `boot_netapp maint` 
|===
. 【第 11 步】验证设置：
+
[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘 | `ssystem node hardware unified-connect show` 


| 是 V 系列或具有 FlexArray 虚拟化软件并连接到存储阵列 | `ucadmin show` 
|===
+
以下示例中的输出显示， FC4 类型的适配器 "1b" 更改为 `initiator` ，适配器 "2a" 和 "2b" 的模式更改为 `CNA` ：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
         Current  Current    Pending  Pending    Admin
Adapter  Mode     Type       Mode     Type       Status
-------  -------  ---------  -------  ---------  ------
1a       fc       initiator  -        -          online
1b       fc       target     -        initiator  online
2a       fc       target     cna      -          online
2b       fc       target     cna      -          online
*>
----
. 【第 12a 步】输入以下命令之一，使所有目标端口联机，每个端口输入一次：
+
[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘 | `network fcp adapter modify -node _node_name_-adapter _adapter_name_-state up` 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | `FCP config _adapter_name_ up` 
|===
. 【 man_check_3_step13]] 为端口布线。
. 【第 14 步】执行以下操作之一：
+
[cols="35,65"]
|===
| 如果系统 ... | 那么 ... 


| 具有存储磁盘 | 转至 link:map_ports_node1_node3.html["将端口从 node1 映射到 node3"]。 


| 是 V 系列系统或具有 FlexArray 虚拟化软件并连接到存储阵列 | 返回到 _Install 和 boot node3_ 并在中继续 link:install_boot_node3.html#step7["第 7 步"]。 
|===

