---
sidebar: sidebar 
permalink: upgrade-arl/index.html 
keywords: aggregate, relocation, moving, manual, upgrade, relocate, hardware 
summary: 使用聚合重新定位升级控制器硬件 
---
= 概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此内容介绍了如何使用聚合重新定位（ Aggregate Relocation ， ARL ）在不造成中断的情况下升级控制器硬件。

有关升级控制器硬件的其他方法、请参见 link:../upgrade/upgrade-decide-to-use-this-guide.html["通过移动卷或存储进行升级"]。

通过将非根聚合从原始节点迁移到同一集群中的新节点，您可以无中断地升级一对运行 ONTAP 的节点上的控制器硬件。升级期间，可以访问要升级的节点上托管的数据。

ARL 利用 HA 配置，您可以将非根聚合的所有权从一个节点移动到另一个节点，前提是它们在同一集群中共享存储。

您可以通过两种 ARL 方法使用系统命令或执行手动升级来升级控制器硬件。开始之前，您必须确认为控制器硬件升级选择了正确的内容。

如果您要使用 system 命令执行升级，请参见下表：

[cols="30,70"]
|===
| 如果您运行的是此 ONTAP 版本… | 要使用 system 命令进行升级，请使用… 


| 9.10.1 或更高版本 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html["使用system controller Replace命令升级同一机箱中的控制器型号"^]

对于某些型号和ONTAP软件版本、您可以使用此操作步骤将配置为全SAN阵列(ASA)的AFF控制器升级为ASA控制器。 link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html["了解更多信息。"]。 


| 9.8 或更高版本 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/index.html["使用 system controller replace 命令升级运行 ONTAP 9.8 或更高版本的控制器硬件"] 


| 9.5 到 9.7 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/index.html["使用 system controller replace 命令将运行 ONTAP 9.5 的控制器硬件升级到 ONTAP 9.7"] 
|===
如果要执行手动升级，请参见下表：

[cols="30,70"]
|===
| 如果您运行的是此 ONTAP 版本… | 要手动升级，请使用… 


| 9.8 或更高版本 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/index.html["手动升级运行 ONTAP 9.8 或更高版本的控制器硬件"] 


| 9.0 到 9.7 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/index.html["手动升级运行 ONTAP 9.7 或更早版本的控制器硬件"] 
|===